// Code generated by scripts/gen_backgrounds; DO NOT EDIT.
// Source: portal/svelte/src/lib/backgrounds.json
// Regenerate: go generate ./internal/portal/...  (or: make backgrounds-check)

package portal

// backgroundSkillsByID holds each background's two fixed PHB skill
// proficiencies, keyed by the builder's kebab-case slug.
var backgroundSkillsByID = map[string][]string{
	"acolyte":       {"insight", "religion"},
	"charlatan":     {"deception", "sleight-of-hand"},
	"criminal":      {"deception", "stealth"},
	"entertainer":   {"acrobatics", "performance"},
	"folk-hero":     {"animal-handling", "survival"},
	"guild-artisan": {"insight", "persuasion"},
	"hermit":        {"medicine", "religion"},
	"noble":         {"history", "persuasion"},
	"outlander":     {"athletics", "survival"},
	"sage":          {"arcana", "history"},
	"sailor":        {"athletics", "perception"},
	"soldier":       {"athletics", "intimidation"},
	"urchin":        {"sleight-of-hand", "stealth"},
}

// backgroundEquipmentByID holds each background's SRD starting-equipment pack,
// keyed by the builder's kebab-case slug.
var backgroundEquipmentByID = map[string][]string{
	"acolyte":       {"holy-symbol", "prayer-book", "incense:5", "vestments", "common-clothes"},
	"charlatan":     {"fine-clothes", "disguise-kit", "con-tools"},
	"criminal":      {"crowbar", "dark-common-clothes", "thieves-tools"},
	"entertainer":   {"musical-instrument", "costume", "common-clothes"},
	"folk-hero":     {"artisans-tools", "shovel", "iron-pot", "common-clothes"},
	"guild-artisan": {"artisans-tools", "letter-of-introduction", "travelers-clothes"},
	"hermit":        {"scroll-case", "winter-blanket", "herbalism-kit", "common-clothes"},
	"noble":         {"fine-clothes", "signet-ring", "scroll-of-pedigree"},
	"outlander":     {"staff", "hunting-trap", "trophy", "travelers-clothes"},
	"sage":          {"ink-bottle", "quill", "small-knife", "letter", "common-clothes"},
	"sailor":        {"belaying-pin", "silk-rope-50ft", "common-clothes"},
	"soldier":       {"insignia-of-rank", "trophy", "dice-set", "common-clothes"},
	"urchin":        {"small-knife", "map-of-city", "pet-mouse", "token", "common-clothes"},
}
