package homebrew

import (
	"context"
	"database/sql"

	"github.com/google/uuid"

	"github.com/ab/dndnd/internal/refdata"
)

// CreateCreatureParams describes the writable fields when creating a
// homebrew creature. The id, campaign_id, homebrew, and source columns
// are managed by the service and ignored if provided.
type CreateCreatureParams = refdata.UpsertCreatureParams

func (s *Service) creatureOps() typeOps[refdata.UpsertCreatureParams, refdata.Creature] {
	return typeOps[refdata.UpsertCreatureParams, refdata.Creature]{
		get:    s.store.GetCreature,
		upsert: s.store.UpsertCreature,
		deleteHomebrew: func(ctx context.Context, id string, campaignID uuid.UUID) (int64, error) {
			return s.store.DeleteHomebrewCreature(ctx, refdata.DeleteHomebrewCreatureParams{
				ID:         id,
				CampaignID: uuid.NullUUID{UUID: campaignID, Valid: true},
			})
		},
		nameOf: func(p refdata.UpsertCreatureParams) string { return p.Name },
		setIdentity: func(p *refdata.UpsertCreatureParams, id string, cid uuid.NullUUID, hb sql.NullBool, src sql.NullString) {
			p.ID, p.CampaignID, p.Homebrew, p.Source = id, cid, hb, src
		},
		ownership: func(r refdata.Creature) (sql.NullBool, uuid.NullUUID) { return r.Homebrew, r.CampaignID },
	}
}

// CreateHomebrewCreature inserts a new homebrew creature owned by the
// given campaign. A new id is generated by the service.
func (s *Service) CreateHomebrewCreature(ctx context.Context, campaignID uuid.UUID, params CreateCreatureParams) (refdata.Creature, error) {
	return genericCreate(ctx, s, s.creatureOps(), campaignID, params)
}

// UpdateHomebrewCreature updates an existing homebrew creature, refusing
// SRD entries and entries owned by other campaigns.
func (s *Service) UpdateHomebrewCreature(ctx context.Context, campaignID uuid.UUID, id string, params CreateCreatureParams) (refdata.Creature, error) {
	return genericUpdate(ctx, s, s.creatureOps(), campaignID, id, params)
}

// DeleteHomebrewCreature removes a homebrew creature owned by the
// campaign. SRD rows and rows in other campaigns return ErrNotFound.
func (s *Service) DeleteHomebrewCreature(ctx context.Context, campaignID uuid.UUID, id string) error {
	return genericDelete(ctx, s, s.creatureOps(), campaignID, id)
}
