package homebrew

import (
	"context"

	"github.com/google/uuid"

	"github.com/ab/dndnd/internal/refdata"
)

// CreateCreatureParams describes the writable fields when creating a
// homebrew creature. The id, campaign_id, homebrew, and source columns
// are managed by the service and ignored if provided.
type CreateCreatureParams = refdata.UpsertCreatureParams

// CreateHomebrewCreature inserts a new homebrew creature owned by the
// given campaign. A new id is generated by the service.
func (s *Service) CreateHomebrewCreature(ctx context.Context, campaignID uuid.UUID, params CreateCreatureParams) (refdata.Creature, error) {
	if err := s.requireCreate(campaignID, params.Name); err != nil {
		return refdata.Creature{}, err
	}
	params.ID = s.idGen()
	params.CampaignID, params.Homebrew, params.Source = s.homebrewCols(campaignID)
	if err := s.store.UpsertCreature(ctx, params); err != nil {
		return refdata.Creature{}, err
	}
	return s.fetchCreature(ctx, params.ID, campaignID)
}

// UpdateHomebrewCreature updates an existing homebrew creature, refusing
// SRD entries and entries owned by other campaigns.
func (s *Service) UpdateHomebrewCreature(ctx context.Context, campaignID uuid.UUID, id string, params CreateCreatureParams) (refdata.Creature, error) {
	if err := s.requireUpdate(campaignID, id, params.Name); err != nil {
		return refdata.Creature{}, err
	}
	existing, err := s.store.GetCreature(ctx, id)
	if err != nil {
		return refdata.Creature{}, translateGetErr(err)
	}
	if err := ownsRow(existing.Homebrew, existing.CampaignID, campaignID); err != nil {
		return refdata.Creature{}, err
	}
	params.ID = id
	params.CampaignID, params.Homebrew, params.Source = s.homebrewCols(campaignID)
	if err := s.store.UpsertCreature(ctx, params); err != nil {
		return refdata.Creature{}, err
	}
	return s.fetchCreature(ctx, id, campaignID)
}

// DeleteHomebrewCreature removes a homebrew creature owned by the
// campaign. SRD rows and rows in other campaigns return ErrNotFound.
func (s *Service) DeleteHomebrewCreature(ctx context.Context, campaignID uuid.UUID, id string) error {
	if err := s.requireDelete(campaignID, id); err != nil {
		return err
	}
	rows, err := s.store.DeleteHomebrewCreature(ctx, refdata.DeleteHomebrewCreatureParams{
		ID:         id,
		CampaignID: uuid.NullUUID{UUID: campaignID, Valid: true},
	})
	if err != nil {
		return err
	}
	if rows == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Service) fetchCreature(ctx context.Context, id string, campaignID uuid.UUID) (refdata.Creature, error) {
	c, err := s.store.GetCreature(ctx, id)
	if err != nil {
		return refdata.Creature{}, translateGetErr(err)
	}
	if err := ownsRow(c.Homebrew, c.CampaignID, campaignID); err != nil {
		return refdata.Creature{}, err
	}
	return c, nil
}
