// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_log.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createActionLog = `-- name: CreateActionLog :one
INSERT INTO action_log (turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at
`

type CreateActionLogParams struct {
	TurnID      uuid.NullUUID         `json:"turn_id"`
	EncounterID uuid.NullUUID         `json:"encounter_id"`
	ActionType  string                `json:"action_type"`
	ActorID     uuid.NullUUID         `json:"actor_id"`
	TargetID    uuid.NullUUID         `json:"target_id"`
	Description sql.NullString        `json:"description"`
	BeforeState json.RawMessage       `json:"before_state"`
	AfterState  json.RawMessage       `json:"after_state"`
	DiceRolls   pqtype.NullRawMessage `json:"dice_rolls"`
}

func (q *Queries) CreateActionLog(ctx context.Context, arg CreateActionLogParams) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, createActionLog,
		arg.TurnID,
		arg.EncounterID,
		arg.ActionType,
		arg.ActorID,
		arg.TargetID,
		arg.Description,
		arg.BeforeState,
		arg.AfterState,
		arg.DiceRolls,
	)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.EncounterID,
		&i.ActionType,
		&i.ActorID,
		&i.TargetID,
		&i.Description,
		&i.BeforeState,
		&i.AfterState,
		&i.DiceRolls,
		&i.CreatedAt,
	)
	return i, err
}

const listActionLogByEncounterID = `-- name: ListActionLogByEncounterID :many
SELECT id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at FROM action_log WHERE encounter_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListActionLogByEncounterID(ctx context.Context, encounterID uuid.NullUUID) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.EncounterID,
			&i.ActionType,
			&i.ActorID,
			&i.TargetID,
			&i.Description,
			&i.BeforeState,
			&i.AfterState,
			&i.DiceRolls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogByTurnID = `-- name: ListActionLogByTurnID :many
SELECT id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at FROM action_log WHERE turn_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListActionLogByTurnID(ctx context.Context, turnID uuid.NullUUID) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogByTurnID, turnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.EncounterID,
			&i.ActionType,
			&i.ActorID,
			&i.TargetID,
			&i.Description,
			&i.BeforeState,
			&i.AfterState,
			&i.DiceRolls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogSinceTurn = `-- name: ListActionLogSinceTurn :many
SELECT id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at FROM action_log
WHERE encounter_id = $1
  AND target_id = $2
  AND created_at > $3
ORDER BY created_at ASC
`

type ListActionLogSinceTurnParams struct {
	EncounterID uuid.NullUUID `json:"encounter_id"`
	TargetID    uuid.NullUUID `json:"target_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

func (q *Queries) ListActionLogSinceTurn(ctx context.Context, arg ListActionLogSinceTurnParams) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogSinceTurn, arg.EncounterID, arg.TargetID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.EncounterID,
			&i.ActionType,
			&i.ActorID,
			&i.TargetID,
			&i.Description,
			&i.BeforeState,
			&i.AfterState,
			&i.DiceRolls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogWithRounds = `-- name: ListActionLogWithRounds :many
SELECT al.id, al.turn_id, al.encounter_id, al.action_type, al.actor_id, al.target_id,
       al.description, al.before_state, al.after_state, al.dice_rolls, al.created_at,
       t.round_number, t.combatant_id as turn_combatant_id
FROM action_log al
JOIN turns t ON al.turn_id = t.id
WHERE al.encounter_id = $1
ORDER BY t.round_number ASC, al.created_at ASC
`

type ListActionLogWithRoundsRow struct {
	ID              uuid.UUID             `json:"id"`
	TurnID          uuid.NullUUID         `json:"turn_id"`
	EncounterID     uuid.NullUUID         `json:"encounter_id"`
	ActionType      string                `json:"action_type"`
	ActorID         uuid.NullUUID         `json:"actor_id"`
	TargetID        uuid.NullUUID         `json:"target_id"`
	Description     sql.NullString        `json:"description"`
	BeforeState     json.RawMessage       `json:"before_state"`
	AfterState      json.RawMessage       `json:"after_state"`
	DiceRolls       pqtype.NullRawMessage `json:"dice_rolls"`
	CreatedAt       time.Time             `json:"created_at"`
	RoundNumber     int32                 `json:"round_number"`
	TurnCombatantID uuid.UUID             `json:"turn_combatant_id"`
}

func (q *Queries) ListActionLogWithRounds(ctx context.Context, encounterID uuid.NullUUID) ([]ListActionLogWithRoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogWithRounds, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionLogWithRoundsRow{}
	for rows.Next() {
		var i ListActionLogWithRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.EncounterID,
			&i.ActionType,
			&i.ActorID,
			&i.TargetID,
			&i.Description,
			&i.BeforeState,
			&i.AfterState,
			&i.DiceRolls,
			&i.CreatedAt,
			&i.RoundNumber,
			&i.TurnCombatantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
