// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_log.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createActionLog = `-- name: CreateActionLog :one
INSERT INTO action_log (turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at
`

type CreateActionLogParams struct {
	TurnID      uuid.UUID             `json:"turn_id"`
	EncounterID uuid.UUID             `json:"encounter_id"`
	ActionType  string                `json:"action_type"`
	ActorID     uuid.UUID             `json:"actor_id"`
	TargetID    uuid.NullUUID         `json:"target_id"`
	Description sql.NullString        `json:"description"`
	BeforeState json.RawMessage       `json:"before_state"`
	AfterState  json.RawMessage       `json:"after_state"`
	DiceRolls   pqtype.NullRawMessage `json:"dice_rolls"`
}

func (q *Queries) CreateActionLog(ctx context.Context, arg CreateActionLogParams) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, createActionLog,
		arg.TurnID,
		arg.EncounterID,
		arg.ActionType,
		arg.ActorID,
		arg.TargetID,
		arg.Description,
		arg.BeforeState,
		arg.AfterState,
		arg.DiceRolls,
	)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.EncounterID,
		&i.ActionType,
		&i.ActorID,
		&i.TargetID,
		&i.Description,
		&i.BeforeState,
		&i.AfterState,
		&i.DiceRolls,
		&i.CreatedAt,
	)
	return i, err
}

const listActionLogByEncounterID = `-- name: ListActionLogByEncounterID :many
SELECT id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at FROM action_log WHERE encounter_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListActionLogByEncounterID(ctx context.Context, encounterID uuid.UUID) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.EncounterID,
			&i.ActionType,
			&i.ActorID,
			&i.TargetID,
			&i.Description,
			&i.BeforeState,
			&i.AfterState,
			&i.DiceRolls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogByTurnID = `-- name: ListActionLogByTurnID :many
SELECT id, turn_id, encounter_id, action_type, actor_id, target_id, description, before_state, after_state, dice_rolls, created_at FROM action_log WHERE turn_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListActionLogByTurnID(ctx context.Context, turnID uuid.UUID) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionLogByTurnID, turnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.EncounterID,
			&i.ActionType,
			&i.ActorID,
			&i.TargetID,
			&i.Description,
			&i.BeforeState,
			&i.AfterState,
			&i.DiceRolls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
