// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: armor.sql

package refdata

import (
	"context"
	"database/sql"
)

const countArmor = `-- name: CountArmor :one
SELECT count(*) FROM armor
`

func (q *Queries) CountArmor(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArmor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArmor = `-- name: GetArmor :one
SELECT id, name, ac_base, ac_dex_bonus, ac_dex_max, strength_req, stealth_disadv, armor_type, weight_lb, created_at, updated_at FROM armor WHERE id = $1
`

func (q *Queries) GetArmor(ctx context.Context, id string) (Armor, error) {
	row := q.db.QueryRowContext(ctx, getArmor, id)
	var i Armor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AcBase,
		&i.AcDexBonus,
		&i.AcDexMax,
		&i.StrengthReq,
		&i.StealthDisadv,
		&i.ArmorType,
		&i.WeightLb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArmor = `-- name: ListArmor :many
SELECT id, name, ac_base, ac_dex_bonus, ac_dex_max, strength_req, stealth_disadv, armor_type, weight_lb, created_at, updated_at FROM armor ORDER BY name
`

func (q *Queries) ListArmor(ctx context.Context) ([]Armor, error) {
	rows, err := q.db.QueryContext(ctx, listArmor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Armor{}
	for rows.Next() {
		var i Armor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AcBase,
			&i.AcDexBonus,
			&i.AcDexMax,
			&i.StrengthReq,
			&i.StealthDisadv,
			&i.ArmorType,
			&i.WeightLb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArmor = `-- name: UpsertArmor :exec
INSERT INTO armor (id, name, ac_base, ac_dex_bonus, ac_dex_max, strength_req, stealth_disadv, armor_type, weight_lb)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    ac_base = EXCLUDED.ac_base,
    ac_dex_bonus = EXCLUDED.ac_dex_bonus,
    ac_dex_max = EXCLUDED.ac_dex_max,
    strength_req = EXCLUDED.strength_req,
    stealth_disadv = EXCLUDED.stealth_disadv,
    armor_type = EXCLUDED.armor_type,
    weight_lb = EXCLUDED.weight_lb,
    updated_at = now()
`

type UpsertArmorParams struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	AcBase        int32           `json:"ac_base"`
	AcDexBonus    sql.NullBool    `json:"ac_dex_bonus"`
	AcDexMax      sql.NullInt32   `json:"ac_dex_max"`
	StrengthReq   sql.NullInt32   `json:"strength_req"`
	StealthDisadv sql.NullBool    `json:"stealth_disadv"`
	ArmorType     string          `json:"armor_type"`
	WeightLb      sql.NullFloat64 `json:"weight_lb"`
}

func (q *Queries) UpsertArmor(ctx context.Context, arg UpsertArmorParams) error {
	_, err := q.db.ExecContext(ctx, upsertArmor,
		arg.ID,
		arg.Name,
		arg.AcBase,
		arg.AcDexBonus,
		arg.AcDexMax,
		arg.StrengthReq,
		arg.StealthDisadv,
		arg.ArmorType,
		arg.WeightLb,
	)
	return err
}
