// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (campaign_id, type, original_name, mime_type, byte_size, storage_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, type, original_name, mime_type, byte_size, storage_path, created_at, updated_at
`

type CreateAssetParams struct {
	CampaignID   uuid.UUID `json:"campaign_id"`
	Type         string    `json:"type"`
	OriginalName string    `json:"original_name"`
	MimeType     string    `json:"mime_type"`
	ByteSize     int64     `json:"byte_size"`
	StoragePath  string    `json:"storage_path"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.CampaignID,
		arg.Type,
		arg.OriginalName,
		arg.MimeType,
		arg.ByteSize,
		arg.StoragePath,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Type,
		&i.OriginalName,
		&i.MimeType,
		&i.ByteSize,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, id)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, campaign_id, type, original_name, mime_type, byte_size, storage_path, created_at, updated_at FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Type,
		&i.OriginalName,
		&i.MimeType,
		&i.ByteSize,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetsByCampaignID = `-- name: ListAssetsByCampaignID :many
SELECT id, campaign_id, type, original_name, mime_type, byte_size, storage_path, created_at, updated_at FROM assets WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAssetsByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Type,
			&i.OriginalName,
			&i.MimeType,
			&i.ByteSize,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
