// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (guild_id, dm_user_id, name, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, guild_id, dm_user_id, name, settings, status, created_at, updated_at
`

type CreateCampaignParams struct {
	GuildID  string                `json:"guild_id"`
	DmUserID string                `json:"dm_user_id"`
	Name     string                `json:"name"`
	Settings pqtype.NullRawMessage `json:"settings"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.GuildID,
		arg.DmUserID,
		arg.Name,
		arg.Settings,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCampaign = `-- name: GetActiveCampaign :one
SELECT active_campaign_id FROM dm_active_campaign WHERE dm_user_id = $1
`

// Returns the DM's stored active campaign id, or sql.ErrNoRows when the DM has
// never made an explicit selection (the resolver then falls back to most-recent).
func (q *Queries) GetActiveCampaign(ctx context.Context, dmUserID string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getActiveCampaign, dmUserID)
	var active_campaign_id uuid.UUID
	err := row.Scan(&active_campaign_id)
	return active_campaign_id, err
}

const getCampaignByGuildID = `-- name: GetCampaignByGuildID :one
SELECT id, guild_id, dm_user_id, name, settings, status, created_at, updated_at FROM campaigns WHERE guild_id = $1
`

func (q *Queries) GetCampaignByGuildID(ctx context.Context, guildID string) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByGuildID, guildID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, guild_id, dm_user_id, name, settings, status, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, guild_id, dm_user_id, name, settings, status, created_at, updated_at FROM campaigns ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.DmUserID,
			&i.Name,
			&i.Settings,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveCampaign = `-- name: SetActiveCampaign :exec
INSERT INTO dm_active_campaign (dm_user_id, active_campaign_id, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (dm_user_id)
DO UPDATE SET active_campaign_id = EXCLUDED.active_campaign_id, updated_at = now()
`

type SetActiveCampaignParams struct {
	DmUserID         string    `json:"dm_user_id"`
	ActiveCampaignID uuid.UUID `json:"active_campaign_id"`
}

// Records (or replaces) the DM's explicitly-selected active campaign so the
// dashboard stops silently following created_at DESC (T20 / Finding 12).
func (q *Queries) SetActiveCampaign(ctx context.Context, arg SetActiveCampaignParams) error {
	_, err := q.db.ExecContext(ctx, setActiveCampaign, arg.DmUserID, arg.ActiveCampaignID)
	return err
}

const updateCampaignName = `-- name: UpdateCampaignName :one
UPDATE campaigns SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, guild_id, dm_user_id, name, settings, status, created_at, updated_at
`

type UpdateCampaignNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateCampaignName(ctx context.Context, arg UpdateCampaignNameParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignName, arg.ID, arg.Name)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignSettings = `-- name: UpdateCampaignSettings :one
UPDATE campaigns SET settings = $2, updated_at = now()
WHERE id = $1
RETURNING id, guild_id, dm_user_id, name, settings, status, created_at, updated_at
`

type UpdateCampaignSettingsParams struct {
	ID       uuid.UUID             `json:"id"`
	Settings pqtype.NullRawMessage `json:"settings"`
}

func (q *Queries) UpdateCampaignSettings(ctx context.Context, arg UpdateCampaignSettingsParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignSettings, arg.ID, arg.Settings)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, guild_id, dm_user_id, name, settings, status, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
