// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countCharactersByCampaign = `-- name: CountCharactersByCampaign :one
SELECT count(*) FROM characters WHERE campaign_id = $1
`

func (q *Queries) CountCharactersByCampaign(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCharactersByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    campaign_id, name, race, classes, level, ability_scores,
    hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft,
    proficiency_bonus, equipped_main_hand, equipped_off_hand,
    equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining,
    feature_uses, features, proficiencies, gold, attunement_slots,
    languages, inventory, character_data, ddb_url, homebrew
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18, $19,
    $20, $21, $22, $23, $24,
    $25, $26, $27, $28, $29
) RETURNING id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id
`

type CreateCharacterParams struct {
	CampaignID       uuid.UUID             `json:"campaign_id"`
	Name             string                `json:"name"`
	Race             string                `json:"race"`
	Classes          json.RawMessage       `json:"classes"`
	Level            int32                 `json:"level"`
	AbilityScores    json.RawMessage       `json:"ability_scores"`
	HpMax            int32                 `json:"hp_max"`
	HpCurrent        int32                 `json:"hp_current"`
	TempHp           int32                 `json:"temp_hp"`
	Ac               int32                 `json:"ac"`
	AcFormula        sql.NullString        `json:"ac_formula"`
	SpeedFt          int32                 `json:"speed_ft"`
	ProficiencyBonus int32                 `json:"proficiency_bonus"`
	EquippedMainHand sql.NullString        `json:"equipped_main_hand"`
	EquippedOffHand  sql.NullString        `json:"equipped_off_hand"`
	EquippedArmor    sql.NullString        `json:"equipped_armor"`
	SpellSlots       pqtype.NullRawMessage `json:"spell_slots"`
	PactMagicSlots   pqtype.NullRawMessage `json:"pact_magic_slots"`
	HitDiceRemaining json.RawMessage       `json:"hit_dice_remaining"`
	FeatureUses      pqtype.NullRawMessage `json:"feature_uses"`
	Features         pqtype.NullRawMessage `json:"features"`
	Proficiencies    pqtype.NullRawMessage `json:"proficiencies"`
	Gold             int32                 `json:"gold"`
	AttunementSlots  pqtype.NullRawMessage `json:"attunement_slots"`
	Languages        []string              `json:"languages"`
	Inventory        pqtype.NullRawMessage `json:"inventory"`
	CharacterData    pqtype.NullRawMessage `json:"character_data"`
	DdbUrl           sql.NullString        `json:"ddb_url"`
	Homebrew         sql.NullBool          `json:"homebrew"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.CampaignID,
		arg.Name,
		arg.Race,
		arg.Classes,
		arg.Level,
		arg.AbilityScores,
		arg.HpMax,
		arg.HpCurrent,
		arg.TempHp,
		arg.Ac,
		arg.AcFormula,
		arg.SpeedFt,
		arg.ProficiencyBonus,
		arg.EquippedMainHand,
		arg.EquippedOffHand,
		arg.EquippedArmor,
		arg.SpellSlots,
		arg.PactMagicSlots,
		arg.HitDiceRemaining,
		arg.FeatureUses,
		arg.Features,
		arg.Proficiencies,
		arg.Gold,
		arg.AttunementSlots,
		pq.Array(arg.Languages),
		arg.Inventory,
		arg.CharacterData,
		arg.DdbUrl,
		arg.Homebrew,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id FROM characters WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const getCharacterCardMessageID = `-- name: GetCharacterCardMessageID :one
SELECT card_message_id FROM characters WHERE id = $1
`

func (q *Queries) GetCharacterCardMessageID(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCharacterCardMessageID, id)
	var card_message_id sql.NullString
	err := row.Scan(&card_message_id)
	return card_message_id, err
}

const listCharactersByCampaign = `-- name: ListCharactersByCampaign :many
SELECT id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id FROM characters WHERE campaign_id = $1 ORDER BY name
`

func (q *Queries) ListCharactersByCampaign(ctx context.Context, campaignID uuid.UUID) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Race,
			&i.Classes,
			&i.Level,
			&i.AbilityScores,
			&i.HpMax,
			&i.HpCurrent,
			&i.TempHp,
			&i.Ac,
			&i.AcFormula,
			&i.SpeedFt,
			&i.ProficiencyBonus,
			&i.EquippedMainHand,
			&i.EquippedOffHand,
			&i.EquippedArmor,
			&i.SpellSlots,
			&i.PactMagicSlots,
			&i.HitDiceRemaining,
			&i.FeatureUses,
			&i.Features,
			&i.Proficiencies,
			&i.Gold,
			&i.AttunementSlots,
			pq.Array(&i.Languages),
			&i.Inventory,
			&i.CharacterData,
			&i.DdbUrl,
			&i.Homebrew,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterCardMessageID = `-- name: SetCharacterCardMessageID :exec
UPDATE characters SET card_message_id = $2, updated_at = now() WHERE id = $1
`

type SetCharacterCardMessageIDParams struct {
	ID            uuid.UUID      `json:"id"`
	CardMessageID sql.NullString `json:"card_message_id"`
}

func (q *Queries) SetCharacterCardMessageID(ctx context.Context, arg SetCharacterCardMessageIDParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterCardMessageID, arg.ID, arg.CardMessageID)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters SET
    name = $2,
    race = $3,
    classes = $4,
    level = $5,
    ability_scores = $6,
    hp_max = $7,
    hp_current = $8,
    temp_hp = $9,
    ac = $10,
    ac_formula = $11,
    speed_ft = $12,
    proficiency_bonus = $13,
    equipped_main_hand = $14,
    equipped_off_hand = $15,
    equipped_armor = $16,
    spell_slots = $17,
    pact_magic_slots = $18,
    hit_dice_remaining = $19,
    feature_uses = $20,
    features = $21,
    proficiencies = $22,
    gold = $23,
    attunement_slots = $24,
    languages = $25,
    inventory = $26,
    character_data = $27,
    ddb_url = $28,
    homebrew = $29,
    updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id
`

type UpdateCharacterParams struct {
	ID               uuid.UUID             `json:"id"`
	Name             string                `json:"name"`
	Race             string                `json:"race"`
	Classes          json.RawMessage       `json:"classes"`
	Level            int32                 `json:"level"`
	AbilityScores    json.RawMessage       `json:"ability_scores"`
	HpMax            int32                 `json:"hp_max"`
	HpCurrent        int32                 `json:"hp_current"`
	TempHp           int32                 `json:"temp_hp"`
	Ac               int32                 `json:"ac"`
	AcFormula        sql.NullString        `json:"ac_formula"`
	SpeedFt          int32                 `json:"speed_ft"`
	ProficiencyBonus int32                 `json:"proficiency_bonus"`
	EquippedMainHand sql.NullString        `json:"equipped_main_hand"`
	EquippedOffHand  sql.NullString        `json:"equipped_off_hand"`
	EquippedArmor    sql.NullString        `json:"equipped_armor"`
	SpellSlots       pqtype.NullRawMessage `json:"spell_slots"`
	PactMagicSlots   pqtype.NullRawMessage `json:"pact_magic_slots"`
	HitDiceRemaining json.RawMessage       `json:"hit_dice_remaining"`
	FeatureUses      pqtype.NullRawMessage `json:"feature_uses"`
	Features         pqtype.NullRawMessage `json:"features"`
	Proficiencies    pqtype.NullRawMessage `json:"proficiencies"`
	Gold             int32                 `json:"gold"`
	AttunementSlots  pqtype.NullRawMessage `json:"attunement_slots"`
	Languages        []string              `json:"languages"`
	Inventory        pqtype.NullRawMessage `json:"inventory"`
	CharacterData    pqtype.NullRawMessage `json:"character_data"`
	DdbUrl           sql.NullString        `json:"ddb_url"`
	Homebrew         sql.NullBool          `json:"homebrew"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacter,
		arg.ID,
		arg.Name,
		arg.Race,
		arg.Classes,
		arg.Level,
		arg.AbilityScores,
		arg.HpMax,
		arg.HpCurrent,
		arg.TempHp,
		arg.Ac,
		arg.AcFormula,
		arg.SpeedFt,
		arg.ProficiencyBonus,
		arg.EquippedMainHand,
		arg.EquippedOffHand,
		arg.EquippedArmor,
		arg.SpellSlots,
		arg.PactMagicSlots,
		arg.HitDiceRemaining,
		arg.FeatureUses,
		arg.Features,
		arg.Proficiencies,
		arg.Gold,
		arg.AttunementSlots,
		pq.Array(arg.Languages),
		arg.Inventory,
		arg.CharacterData,
		arg.DdbUrl,
		arg.Homebrew,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const updateCharacterData = `-- name: UpdateCharacterData :one
UPDATE characters SET character_data = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id
`

type UpdateCharacterDataParams struct {
	ID            uuid.UUID             `json:"id"`
	CharacterData pqtype.NullRawMessage `json:"character_data"`
}

func (q *Queries) UpdateCharacterData(ctx context.Context, arg UpdateCharacterDataParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterData, arg.ID, arg.CharacterData)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const updateCharacterFeatureUses = `-- name: UpdateCharacterFeatureUses :one
UPDATE characters SET feature_uses = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id
`

type UpdateCharacterFeatureUsesParams struct {
	ID          uuid.UUID             `json:"id"`
	FeatureUses pqtype.NullRawMessage `json:"feature_uses"`
}

func (q *Queries) UpdateCharacterFeatureUses(ctx context.Context, arg UpdateCharacterFeatureUsesParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterFeatureUses, arg.ID, arg.FeatureUses)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const updateCharacterPactMagicSlots = `-- name: UpdateCharacterPactMagicSlots :one
UPDATE characters SET pact_magic_slots = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id
`

type UpdateCharacterPactMagicSlotsParams struct {
	ID             uuid.UUID             `json:"id"`
	PactMagicSlots pqtype.NullRawMessage `json:"pact_magic_slots"`
}

func (q *Queries) UpdateCharacterPactMagicSlots(ctx context.Context, arg UpdateCharacterPactMagicSlotsParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterPactMagicSlots, arg.ID, arg.PactMagicSlots)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const updateCharacterSpellSlots = `-- name: UpdateCharacterSpellSlots :one
UPDATE characters SET spell_slots = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id
`

type UpdateCharacterSpellSlotsParams struct {
	ID         uuid.UUID             `json:"id"`
	SpellSlots pqtype.NullRawMessage `json:"spell_slots"`
}

func (q *Queries) UpdateCharacterSpellSlots(ctx context.Context, arg UpdateCharacterSpellSlotsParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterSpellSlots, arg.ID, arg.SpellSlots)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}
