// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character_drafts.sql

package refdata

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getCharacterDraft = `-- name: GetCharacterDraft :one
SELECT draft FROM character_drafts
WHERE campaign_id = $1 AND discord_user_id = $2 AND mode = $3
`

type GetCharacterDraftParams struct {
	CampaignID    uuid.UUID `json:"campaign_id"`
	DiscordUserID string    `json:"discord_user_id"`
	Mode          string    `json:"mode"`
}

// Returns the stored builder draft blob for (campaign, player, mode), or
// sql.ErrNoRows when none exists.
func (q *Queries) GetCharacterDraft(ctx context.Context, arg GetCharacterDraftParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getCharacterDraft, arg.CampaignID, arg.DiscordUserID, arg.Mode)
	var draft json.RawMessage
	err := row.Scan(&draft)
	return draft, err
}

const upsertCharacterDraft = `-- name: UpsertCharacterDraft :exec
INSERT INTO character_drafts (campaign_id, discord_user_id, mode, draft, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (campaign_id, discord_user_id, mode)
DO UPDATE SET draft = EXCLUDED.draft, updated_at = now()
`

type UpsertCharacterDraftParams struct {
	CampaignID    uuid.UUID       `json:"campaign_id"`
	DiscordUserID string          `json:"discord_user_id"`
	Mode          string          `json:"mode"`
	Draft         json.RawMessage `json:"draft"`
}

// Persists the player's in-progress builder draft, replacing any prior draft
// for the same (campaign, player, mode). Called from the submit path so the
// "request changes" cycle and cross-device resume can rehydrate the form
// (T11 / Finding 4·b).
func (q *Queries) UpsertCharacterDraft(ctx context.Context, arg UpsertCharacterDraftParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacterDraft,
		arg.CampaignID,
		arg.DiscordUserID,
		arg.Mode,
		arg.Draft,
	)
	return err
}
