// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package refdata

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countClasses = `-- name: CountClasses :one
SELECT count(*) FROM classes
`

func (q *Queries) CountClasses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClasses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClass = `-- name: GetClass :one
SELECT id, name, hit_die, primary_ability, save_proficiencies, armor_proficiencies, weapon_proficiencies, skill_choices, spellcasting, features_by_level, attacks_per_action, subclass_level, subclasses, multiclass_prereqs, multiclass_proficiencies, created_at, updated_at FROM classes WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id string) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HitDie,
		&i.PrimaryAbility,
		pq.Array(&i.SaveProficiencies),
		pq.Array(&i.ArmorProficiencies),
		pq.Array(&i.WeaponProficiencies),
		&i.SkillChoices,
		&i.Spellcasting,
		&i.FeaturesByLevel,
		&i.AttacksPerAction,
		&i.SubclassLevel,
		&i.Subclasses,
		&i.MulticlassPrereqs,
		&i.MulticlassProficiencies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, hit_die, primary_ability, save_proficiencies, armor_proficiencies, weapon_proficiencies, skill_choices, spellcasting, features_by_level, attacks_per_action, subclass_level, subclasses, multiclass_prereqs, multiclass_proficiencies, created_at, updated_at FROM classes ORDER BY name
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HitDie,
			&i.PrimaryAbility,
			pq.Array(&i.SaveProficiencies),
			pq.Array(&i.ArmorProficiencies),
			pq.Array(&i.WeaponProficiencies),
			&i.SkillChoices,
			&i.Spellcasting,
			&i.FeaturesByLevel,
			&i.AttacksPerAction,
			&i.SubclassLevel,
			&i.Subclasses,
			&i.MulticlassPrereqs,
			&i.MulticlassProficiencies,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClass = `-- name: UpsertClass :exec
INSERT INTO classes (id, name, hit_die, primary_ability, save_proficiencies, armor_proficiencies, weapon_proficiencies, skill_choices, spellcasting, features_by_level, attacks_per_action, subclass_level, subclasses, multiclass_prereqs, multiclass_proficiencies)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    hit_die = EXCLUDED.hit_die,
    primary_ability = EXCLUDED.primary_ability,
    save_proficiencies = EXCLUDED.save_proficiencies,
    armor_proficiencies = EXCLUDED.armor_proficiencies,
    weapon_proficiencies = EXCLUDED.weapon_proficiencies,
    skill_choices = EXCLUDED.skill_choices,
    spellcasting = EXCLUDED.spellcasting,
    features_by_level = EXCLUDED.features_by_level,
    attacks_per_action = EXCLUDED.attacks_per_action,
    subclass_level = EXCLUDED.subclass_level,
    subclasses = EXCLUDED.subclasses,
    multiclass_prereqs = EXCLUDED.multiclass_prereqs,
    multiclass_proficiencies = EXCLUDED.multiclass_proficiencies,
    updated_at = now()
`

type UpsertClassParams struct {
	ID                      string                `json:"id"`
	Name                    string                `json:"name"`
	HitDie                  string                `json:"hit_die"`
	PrimaryAbility          string                `json:"primary_ability"`
	SaveProficiencies       []string              `json:"save_proficiencies"`
	ArmorProficiencies      []string              `json:"armor_proficiencies"`
	WeaponProficiencies     []string              `json:"weapon_proficiencies"`
	SkillChoices            pqtype.NullRawMessage `json:"skill_choices"`
	Spellcasting            pqtype.NullRawMessage `json:"spellcasting"`
	FeaturesByLevel         json.RawMessage       `json:"features_by_level"`
	AttacksPerAction        json.RawMessage       `json:"attacks_per_action"`
	SubclassLevel           int32                 `json:"subclass_level"`
	Subclasses              json.RawMessage       `json:"subclasses"`
	MulticlassPrereqs       pqtype.NullRawMessage `json:"multiclass_prereqs"`
	MulticlassProficiencies pqtype.NullRawMessage `json:"multiclass_proficiencies"`
}

func (q *Queries) UpsertClass(ctx context.Context, arg UpsertClassParams) error {
	_, err := q.db.ExecContext(ctx, upsertClass,
		arg.ID,
		arg.Name,
		arg.HitDie,
		arg.PrimaryAbility,
		pq.Array(arg.SaveProficiencies),
		pq.Array(arg.ArmorProficiencies),
		pq.Array(arg.WeaponProficiencies),
		arg.SkillChoices,
		arg.Spellcasting,
		arg.FeaturesByLevel,
		arg.AttacksPerAction,
		arg.SubclassLevel,
		arg.Subclasses,
		arg.MulticlassPrereqs,
		arg.MulticlassProficiencies,
	)
	return err
}
