// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: combatants.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCombatant = `-- name: CreateCombatant :one
INSERT INTO combatants (
    encounter_id, character_id, creature_ref_id, short_id, display_name,
    initiative_roll, initiative_order, position_col, position_row, altitude_ft,
    hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves,
    is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining,
    rage_attacked_this_round, rage_took_damage_this_round,
    is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22,
    $23, $24,
    $25, $26, $27, $28
)
RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type CreateCombatantParams struct {
	EncounterID             uuid.UUID             `json:"encounter_id"`
	CharacterID             uuid.NullUUID         `json:"character_id"`
	CreatureRefID           sql.NullString        `json:"creature_ref_id"`
	ShortID                 string                `json:"short_id"`
	DisplayName             string                `json:"display_name"`
	InitiativeRoll          int32                 `json:"initiative_roll"`
	InitiativeOrder         int32                 `json:"initiative_order"`
	PositionCol             string                `json:"position_col"`
	PositionRow             int32                 `json:"position_row"`
	AltitudeFt              int32                 `json:"altitude_ft"`
	HpMax                   int32                 `json:"hp_max"`
	HpCurrent               int32                 `json:"hp_current"`
	TempHp                  int32                 `json:"temp_hp"`
	Ac                      int32                 `json:"ac"`
	Conditions              json.RawMessage       `json:"conditions"`
	ExhaustionLevel         int32                 `json:"exhaustion_level"`
	DeathSaves              pqtype.NullRawMessage `json:"death_saves"`
	IsVisible               bool                  `json:"is_visible"`
	IsAlive                 bool                  `json:"is_alive"`
	IsNpc                   bool                  `json:"is_npc"`
	IsRaging                bool                  `json:"is_raging"`
	RageRoundsRemaining     sql.NullInt32         `json:"rage_rounds_remaining"`
	RageAttackedThisRound   bool                  `json:"rage_attacked_this_round"`
	RageTookDamageThisRound bool                  `json:"rage_took_damage_this_round"`
	IsWildShaped            bool                  `json:"is_wild_shaped"`
	WildShapeCreatureRef    sql.NullString        `json:"wild_shape_creature_ref"`
	WildShapeOriginal       pqtype.NullRawMessage `json:"wild_shape_original"`
	SummonerID              uuid.NullUUID         `json:"summoner_id"`
}

func (q *Queries) CreateCombatant(ctx context.Context, arg CreateCombatantParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, createCombatant,
		arg.EncounterID,
		arg.CharacterID,
		arg.CreatureRefID,
		arg.ShortID,
		arg.DisplayName,
		arg.InitiativeRoll,
		arg.InitiativeOrder,
		arg.PositionCol,
		arg.PositionRow,
		arg.AltitudeFt,
		arg.HpMax,
		arg.HpCurrent,
		arg.TempHp,
		arg.Ac,
		arg.Conditions,
		arg.ExhaustionLevel,
		arg.DeathSaves,
		arg.IsVisible,
		arg.IsAlive,
		arg.IsNpc,
		arg.IsRaging,
		arg.RageRoundsRemaining,
		arg.RageAttackedThisRound,
		arg.RageTookDamageThisRound,
		arg.IsWildShaped,
		arg.WildShapeCreatureRef,
		arg.WildShapeOriginal,
		arg.SummonerID,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCombatant = `-- name: DeleteCombatant :exec
DELETE FROM combatants WHERE id = $1
`

func (q *Queries) DeleteCombatant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCombatant, id)
	return err
}

const getCombatant = `-- name: GetCombatant :one
SELECT id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at FROM combatants WHERE id = $1
`

func (q *Queries) GetCombatant(ctx context.Context, id uuid.UUID) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, getCombatant, id)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCombatantsByEncounterID = `-- name: ListCombatantsByEncounterID :many
SELECT id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at FROM combatants WHERE encounter_id = $1 ORDER BY initiative_order ASC
`

func (q *Queries) ListCombatantsByEncounterID(ctx context.Context, encounterID uuid.UUID) ([]Combatant, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Combatant{}
	for rows.Next() {
		var i Combatant
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CharacterID,
			&i.CreatureRefID,
			&i.ShortID,
			&i.DisplayName,
			&i.InitiativeRoll,
			&i.InitiativeOrder,
			&i.PositionCol,
			&i.PositionRow,
			&i.AltitudeFt,
			&i.HpMax,
			&i.HpCurrent,
			&i.TempHp,
			&i.Ac,
			&i.Conditions,
			&i.ExhaustionLevel,
			&i.DeathSaves,
			&i.IsVisible,
			&i.IsAlive,
			&i.IsNpc,
			&i.IsRaging,
			&i.RageRoundsRemaining,
			&i.RageAttackedThisRound,
			&i.RageTookDamageThisRound,
			&i.IsWildShaped,
			&i.WildShapeCreatureRef,
			&i.WildShapeOriginal,
			&i.SummonerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCombatantConditions = `-- name: UpdateCombatantConditions :one
UPDATE combatants SET conditions = $2, exhaustion_level = $3, updated_at = now()
WHERE id = $1 RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type UpdateCombatantConditionsParams struct {
	ID              uuid.UUID       `json:"id"`
	Conditions      json.RawMessage `json:"conditions"`
	ExhaustionLevel int32           `json:"exhaustion_level"`
}

func (q *Queries) UpdateCombatantConditions(ctx context.Context, arg UpdateCombatantConditionsParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatantConditions, arg.ID, arg.Conditions, arg.ExhaustionLevel)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatantDeathSaves = `-- name: UpdateCombatantDeathSaves :one
UPDATE combatants SET death_saves = $2, updated_at = now()
WHERE id = $1 RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type UpdateCombatantDeathSavesParams struct {
	ID         uuid.UUID             `json:"id"`
	DeathSaves pqtype.NullRawMessage `json:"death_saves"`
}

func (q *Queries) UpdateCombatantDeathSaves(ctx context.Context, arg UpdateCombatantDeathSavesParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatantDeathSaves, arg.ID, arg.DeathSaves)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatantHP = `-- name: UpdateCombatantHP :one
UPDATE combatants SET hp_current = $2, temp_hp = $3, is_alive = $4, updated_at = now()
WHERE id = $1 RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type UpdateCombatantHPParams struct {
	ID        uuid.UUID `json:"id"`
	HpCurrent int32     `json:"hp_current"`
	TempHp    int32     `json:"temp_hp"`
	IsAlive   bool      `json:"is_alive"`
}

func (q *Queries) UpdateCombatantHP(ctx context.Context, arg UpdateCombatantHPParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatantHP,
		arg.ID,
		arg.HpCurrent,
		arg.TempHp,
		arg.IsAlive,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatantInitiative = `-- name: UpdateCombatantInitiative :one
UPDATE combatants SET initiative_roll = $2, initiative_order = $3, updated_at = now()
WHERE id = $1 RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type UpdateCombatantInitiativeParams struct {
	ID              uuid.UUID `json:"id"`
	InitiativeRoll  int32     `json:"initiative_roll"`
	InitiativeOrder int32     `json:"initiative_order"`
}

func (q *Queries) UpdateCombatantInitiative(ctx context.Context, arg UpdateCombatantInitiativeParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatantInitiative, arg.ID, arg.InitiativeRoll, arg.InitiativeOrder)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatantPosition = `-- name: UpdateCombatantPosition :one
UPDATE combatants SET position_col = $2, position_row = $3, altitude_ft = $4, updated_at = now()
WHERE id = $1 RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type UpdateCombatantPositionParams struct {
	ID          uuid.UUID `json:"id"`
	PositionCol string    `json:"position_col"`
	PositionRow int32     `json:"position_row"`
	AltitudeFt  int32     `json:"altitude_ft"`
}

func (q *Queries) UpdateCombatantPosition(ctx context.Context, arg UpdateCombatantPositionParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatantPosition,
		arg.ID,
		arg.PositionCol,
		arg.PositionRow,
		arg.AltitudeFt,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCombatantRage = `-- name: UpdateCombatantRage :one
UPDATE combatants SET
    is_raging = $2,
    rage_rounds_remaining = $3,
    rage_attacked_this_round = $4,
    rage_took_damage_this_round = $5,
    updated_at = now()
WHERE id = $1 RETURNING id, encounter_id, character_id, creature_ref_id, short_id, display_name, initiative_roll, initiative_order, position_col, position_row, altitude_ft, hp_max, hp_current, temp_hp, ac, conditions, exhaustion_level, death_saves, is_visible, is_alive, is_npc, is_raging, rage_rounds_remaining, rage_attacked_this_round, rage_took_damage_this_round, is_wild_shaped, wild_shape_creature_ref, wild_shape_original, summoner_id, created_at, updated_at
`

type UpdateCombatantRageParams struct {
	ID                      uuid.UUID     `json:"id"`
	IsRaging                bool          `json:"is_raging"`
	RageRoundsRemaining     sql.NullInt32 `json:"rage_rounds_remaining"`
	RageAttackedThisRound   bool          `json:"rage_attacked_this_round"`
	RageTookDamageThisRound bool          `json:"rage_took_damage_this_round"`
}

func (q *Queries) UpdateCombatantRage(ctx context.Context, arg UpdateCombatantRageParams) (Combatant, error) {
	row := q.db.QueryRowContext(ctx, updateCombatantRage,
		arg.ID,
		arg.IsRaging,
		arg.RageRoundsRemaining,
		arg.RageAttackedThisRound,
		arg.RageTookDamageThisRound,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.CreatureRefID,
		&i.ShortID,
		&i.DisplayName,
		&i.InitiativeRoll,
		&i.InitiativeOrder,
		&i.PositionCol,
		&i.PositionRow,
		&i.AltitudeFt,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.Conditions,
		&i.ExhaustionLevel,
		&i.DeathSaves,
		&i.IsVisible,
		&i.IsAlive,
		&i.IsNpc,
		&i.IsRaging,
		&i.RageRoundsRemaining,
		&i.RageAttackedThisRound,
		&i.RageTookDamageThisRound,
		&i.IsWildShaped,
		&i.WildShapeCreatureRef,
		&i.WildShapeOriginal,
		&i.SummonerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
