// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conditions.sql

package refdata

import (
	"context"
	"encoding/json"
)

const countConditions = `-- name: CountConditions :one
SELECT count(*) FROM conditions_ref
`

func (q *Queries) CountConditions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConditions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCondition = `-- name: GetCondition :one
SELECT id, name, description, mechanical_effects, created_at, updated_at FROM conditions_ref WHERE id = $1
`

func (q *Queries) GetCondition(ctx context.Context, id string) (ConditionsRef, error) {
	row := q.db.QueryRowContext(ctx, getCondition, id)
	var i ConditionsRef
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MechanicalEffects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConditions = `-- name: ListConditions :many
SELECT id, name, description, mechanical_effects, created_at, updated_at FROM conditions_ref ORDER BY name
`

func (q *Queries) ListConditions(ctx context.Context) ([]ConditionsRef, error) {
	rows, err := q.db.QueryContext(ctx, listConditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConditionsRef{}
	for rows.Next() {
		var i ConditionsRef
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MechanicalEffects,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCondition = `-- name: UpsertCondition :exec
INSERT INTO conditions_ref (id, name, description, mechanical_effects)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    mechanical_effects = EXCLUDED.mechanical_effects,
    updated_at = now()
`

type UpsertConditionParams struct {
	ID                string          `json:"id"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	MechanicalEffects json.RawMessage `json:"mechanical_effects"`
}

func (q *Queries) UpsertCondition(ctx context.Context, arg UpsertConditionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCondition,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MechanicalEffects,
	)
	return err
}
