// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creatures.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countCreatures = `-- name: CountCreatures :one
SELECT count(*) FROM creatures
`

func (q *Queries) CountCreatures(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCreatures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHomebrewCreature = `-- name: DeleteHomebrewCreature :execrows
DELETE FROM creatures WHERE id = $1 AND homebrew = true AND campaign_id = $2
`

type DeleteHomebrewCreatureParams struct {
	ID         string        `json:"id"`
	CampaignID uuid.NullUUID `json:"campaign_id"`
}

func (q *Queries) DeleteHomebrewCreature(ctx context.Context, arg DeleteHomebrewCreatureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHomebrewCreature, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCreature = `-- name: GetCreature :one
SELECT id, campaign_id, name, size, type, alignment, ac, ac_type, hp_formula, hp_average, speed, ability_scores, saving_throws, skills, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, cr, attacks, abilities, homebrew, source, created_at, updated_at, bonus_actions FROM creatures WHERE id = $1
`

func (q *Queries) GetCreature(ctx context.Context, id string) (Creature, error) {
	row := q.db.QueryRowContext(ctx, getCreature, id)
	var i Creature
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Size,
		&i.Type,
		&i.Alignment,
		&i.Ac,
		&i.AcType,
		&i.HpFormula,
		&i.HpAverage,
		&i.Speed,
		&i.AbilityScores,
		&i.SavingThrows,
		&i.Skills,
		pq.Array(&i.DamageResistances),
		pq.Array(&i.DamageImmunities),
		pq.Array(&i.DamageVulnerabilities),
		pq.Array(&i.ConditionImmunities),
		&i.Senses,
		pq.Array(&i.Languages),
		&i.Cr,
		&i.Attacks,
		&i.Abilities,
		&i.Homebrew,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BonusActions,
	)
	return i, err
}

const listCreatures = `-- name: ListCreatures :many
SELECT id, campaign_id, name, size, type, alignment, ac, ac_type, hp_formula, hp_average, speed, ability_scores, saving_throws, skills, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, cr, attacks, abilities, homebrew, source, created_at, updated_at, bonus_actions FROM creatures ORDER BY name
`

func (q *Queries) ListCreatures(ctx context.Context) ([]Creature, error) {
	rows, err := q.db.QueryContext(ctx, listCreatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Creature{}
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Alignment,
			&i.Ac,
			&i.AcType,
			&i.HpFormula,
			&i.HpAverage,
			&i.Speed,
			&i.AbilityScores,
			&i.SavingThrows,
			&i.Skills,
			pq.Array(&i.DamageResistances),
			pq.Array(&i.DamageImmunities),
			pq.Array(&i.DamageVulnerabilities),
			pq.Array(&i.ConditionImmunities),
			&i.Senses,
			pq.Array(&i.Languages),
			&i.Cr,
			&i.Attacks,
			&i.Abilities,
			&i.Homebrew,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BonusActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreaturesByCR = `-- name: ListCreaturesByCR :many
SELECT id, campaign_id, name, size, type, alignment, ac, ac_type, hp_formula, hp_average, speed, ability_scores, saving_throws, skills, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, cr, attacks, abilities, homebrew, source, created_at, updated_at, bonus_actions FROM creatures WHERE cr = $1 ORDER BY name
`

func (q *Queries) ListCreaturesByCR(ctx context.Context, cr string) ([]Creature, error) {
	rows, err := q.db.QueryContext(ctx, listCreaturesByCR, cr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Creature{}
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Alignment,
			&i.Ac,
			&i.AcType,
			&i.HpFormula,
			&i.HpAverage,
			&i.Speed,
			&i.AbilityScores,
			&i.SavingThrows,
			&i.Skills,
			pq.Array(&i.DamageResistances),
			pq.Array(&i.DamageImmunities),
			pq.Array(&i.DamageVulnerabilities),
			pq.Array(&i.ConditionImmunities),
			&i.Senses,
			pq.Array(&i.Languages),
			&i.Cr,
			&i.Attacks,
			&i.Abilities,
			&i.Homebrew,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BonusActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreaturesByType = `-- name: ListCreaturesByType :many
SELECT id, campaign_id, name, size, type, alignment, ac, ac_type, hp_formula, hp_average, speed, ability_scores, saving_throws, skills, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, cr, attacks, abilities, homebrew, source, created_at, updated_at, bonus_actions FROM creatures WHERE type = $1 ORDER BY name
`

func (q *Queries) ListCreaturesByType(ctx context.Context, type_ string) ([]Creature, error) {
	rows, err := q.db.QueryContext(ctx, listCreaturesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Creature{}
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Size,
			&i.Type,
			&i.Alignment,
			&i.Ac,
			&i.AcType,
			&i.HpFormula,
			&i.HpAverage,
			&i.Speed,
			&i.AbilityScores,
			&i.SavingThrows,
			&i.Skills,
			pq.Array(&i.DamageResistances),
			pq.Array(&i.DamageImmunities),
			pq.Array(&i.DamageVulnerabilities),
			pq.Array(&i.ConditionImmunities),
			&i.Senses,
			pq.Array(&i.Languages),
			&i.Cr,
			&i.Attacks,
			&i.Abilities,
			&i.Homebrew,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BonusActions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCreature = `-- name: UpsertCreature :exec
INSERT INTO creatures (id, campaign_id, name, size, type, alignment, ac, ac_type, hp_formula, hp_average, speed, ability_scores, saving_throws, skills, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, cr, attacks, abilities, bonus_actions, homebrew, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
ON CONFLICT (id) DO UPDATE SET
    campaign_id = EXCLUDED.campaign_id,
    name = EXCLUDED.name,
    size = EXCLUDED.size,
    type = EXCLUDED.type,
    alignment = EXCLUDED.alignment,
    ac = EXCLUDED.ac,
    ac_type = EXCLUDED.ac_type,
    hp_formula = EXCLUDED.hp_formula,
    hp_average = EXCLUDED.hp_average,
    speed = EXCLUDED.speed,
    ability_scores = EXCLUDED.ability_scores,
    saving_throws = EXCLUDED.saving_throws,
    skills = EXCLUDED.skills,
    damage_resistances = EXCLUDED.damage_resistances,
    damage_immunities = EXCLUDED.damage_immunities,
    damage_vulnerabilities = EXCLUDED.damage_vulnerabilities,
    condition_immunities = EXCLUDED.condition_immunities,
    senses = EXCLUDED.senses,
    languages = EXCLUDED.languages,
    cr = EXCLUDED.cr,
    attacks = EXCLUDED.attacks,
    abilities = EXCLUDED.abilities,
    bonus_actions = EXCLUDED.bonus_actions,
    homebrew = EXCLUDED.homebrew,
    source = EXCLUDED.source,
    updated_at = now()
`

type UpsertCreatureParams struct {
	ID                    string                `json:"id"`
	CampaignID            uuid.NullUUID         `json:"campaign_id"`
	Name                  string                `json:"name"`
	Size                  string                `json:"size"`
	Type                  string                `json:"type"`
	Alignment             sql.NullString        `json:"alignment"`
	Ac                    int32                 `json:"ac"`
	AcType                sql.NullString        `json:"ac_type"`
	HpFormula             string                `json:"hp_formula"`
	HpAverage             int32                 `json:"hp_average"`
	Speed                 json.RawMessage       `json:"speed"`
	AbilityScores         json.RawMessage       `json:"ability_scores"`
	SavingThrows          pqtype.NullRawMessage `json:"saving_throws"`
	Skills                pqtype.NullRawMessage `json:"skills"`
	DamageResistances     []string              `json:"damage_resistances"`
	DamageImmunities      []string              `json:"damage_immunities"`
	DamageVulnerabilities []string              `json:"damage_vulnerabilities"`
	ConditionImmunities   []string              `json:"condition_immunities"`
	Senses                pqtype.NullRawMessage `json:"senses"`
	Languages             []string              `json:"languages"`
	Cr                    string                `json:"cr"`
	Attacks               json.RawMessage       `json:"attacks"`
	Abilities             pqtype.NullRawMessage `json:"abilities"`
	BonusActions          pqtype.NullRawMessage `json:"bonus_actions"`
	Homebrew              sql.NullBool          `json:"homebrew"`
	Source                sql.NullString        `json:"source"`
}

func (q *Queries) UpsertCreature(ctx context.Context, arg UpsertCreatureParams) error {
	_, err := q.db.ExecContext(ctx, upsertCreature,
		arg.ID,
		arg.CampaignID,
		arg.Name,
		arg.Size,
		arg.Type,
		arg.Alignment,
		arg.Ac,
		arg.AcType,
		arg.HpFormula,
		arg.HpAverage,
		arg.Speed,
		arg.AbilityScores,
		arg.SavingThrows,
		arg.Skills,
		pq.Array(arg.DamageResistances),
		pq.Array(arg.DamageImmunities),
		pq.Array(arg.DamageVulnerabilities),
		pq.Array(arg.ConditionImmunities),
		arg.Senses,
		pq.Array(arg.Languages),
		arg.Cr,
		arg.Attacks,
		arg.Abilities,
		arg.BonusActions,
		arg.Homebrew,
		arg.Source,
	)
	return err
}
