// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm_player_messages.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const insertDMPlayerMessage = `-- name: InsertDMPlayerMessage :one
INSERT INTO dm_player_messages (
    campaign_id,
    player_character_id,
    author_user_id,
    body,
    discord_message_ids
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, player_character_id, author_user_id, body, discord_message_ids, sent_at
`

type InsertDMPlayerMessageParams struct {
	CampaignID        uuid.UUID `json:"campaign_id"`
	PlayerCharacterID uuid.UUID `json:"player_character_id"`
	AuthorUserID      string    `json:"author_user_id"`
	Body              string    `json:"body"`
	DiscordMessageIds []string  `json:"discord_message_ids"`
}

func (q *Queries) InsertDMPlayerMessage(ctx context.Context, arg InsertDMPlayerMessageParams) (DmPlayerMessage, error) {
	row := q.db.QueryRowContext(ctx, insertDMPlayerMessage,
		arg.CampaignID,
		arg.PlayerCharacterID,
		arg.AuthorUserID,
		arg.Body,
		pq.Array(arg.DiscordMessageIds),
	)
	var i DmPlayerMessage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.PlayerCharacterID,
		&i.AuthorUserID,
		&i.Body,
		pq.Array(&i.DiscordMessageIds),
		&i.SentAt,
	)
	return i, err
}

const listDMPlayerMessages = `-- name: ListDMPlayerMessages :many
SELECT id, campaign_id, player_character_id, author_user_id, body, discord_message_ids, sent_at
FROM dm_player_messages
WHERE campaign_id = $1 AND player_character_id = $2
ORDER BY sent_at DESC
LIMIT $3 OFFSET $4
`

type ListDMPlayerMessagesParams struct {
	CampaignID        uuid.UUID `json:"campaign_id"`
	PlayerCharacterID uuid.UUID `json:"player_character_id"`
	Limit             int32     `json:"limit"`
	Offset            int32     `json:"offset"`
}

func (q *Queries) ListDMPlayerMessages(ctx context.Context, arg ListDMPlayerMessagesParams) ([]DmPlayerMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDMPlayerMessages,
		arg.CampaignID,
		arg.PlayerCharacterID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmPlayerMessage{}
	for rows.Next() {
		var i DmPlayerMessage
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.PlayerCharacterID,
			&i.AuthorUserID,
			&i.Body,
			pq.Array(&i.DiscordMessageIds),
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
