// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm_queue_items.sql

package refdata

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getDMQueueItem = `-- name: GetDMQueueItem :one
SELECT id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
FROM dm_queue_items
WHERE id = $1
`

func (q *Queries) GetDMQueueItem(ctx context.Context, id uuid.UUID) (DmQueueItem, error) {
	row := q.db.QueryRowContext(ctx, getDMQueueItem, id)
	var i DmQueueItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Kind,
		&i.PlayerName,
		&i.Summary,
		&i.ResolvePath,
		&i.Status,
		&i.Outcome,
		&i.Extra,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertDMQueueItem = `-- name: InsertDMQueueItem :one
INSERT INTO dm_queue_items (
    id,
    campaign_id,
    guild_id,
    channel_id,
    message_id,
    kind,
    player_name,
    summary,
    resolve_path,
    extra
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
`

type InsertDMQueueItemParams struct {
	ID          uuid.UUID       `json:"id"`
	CampaignID  uuid.UUID       `json:"campaign_id"`
	GuildID     string          `json:"guild_id"`
	ChannelID   string          `json:"channel_id"`
	MessageID   string          `json:"message_id"`
	Kind        string          `json:"kind"`
	PlayerName  string          `json:"player_name"`
	Summary     string          `json:"summary"`
	ResolvePath string          `json:"resolve_path"`
	Extra       json.RawMessage `json:"extra"`
}

func (q *Queries) InsertDMQueueItem(ctx context.Context, arg InsertDMQueueItemParams) (DmQueueItem, error) {
	row := q.db.QueryRowContext(ctx, insertDMQueueItem,
		arg.ID,
		arg.CampaignID,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.Kind,
		arg.PlayerName,
		arg.Summary,
		arg.ResolvePath,
		arg.Extra,
	)
	var i DmQueueItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Kind,
		&i.PlayerName,
		&i.Summary,
		&i.ResolvePath,
		&i.Status,
		&i.Outcome,
		&i.Extra,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listAllPendingDMQueueItems = `-- name: ListAllPendingDMQueueItems :many
SELECT id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
FROM dm_queue_items
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListAllPendingDMQueueItems(ctx context.Context) ([]DmQueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllPendingDMQueueItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmQueueItem{}
	for rows.Next() {
		var i DmQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.Kind,
			&i.PlayerName,
			&i.Summary,
			&i.ResolvePath,
			&i.Status,
			&i.Outcome,
			&i.Extra,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDMQueueItems = `-- name: ListPendingDMQueueItems :many
SELECT id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
FROM dm_queue_items
WHERE campaign_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingDMQueueItems(ctx context.Context, campaignID uuid.UUID) ([]DmQueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDMQueueItems, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmQueueItem{}
	for rows.Next() {
		var i DmQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.Kind,
			&i.PlayerName,
			&i.Summary,
			&i.ResolvePath,
			&i.Status,
			&i.Outcome,
			&i.Extra,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDMQueueItemCancelled = `-- name: MarkDMQueueItemCancelled :one
UPDATE dm_queue_items
SET status = 'cancelled',
    outcome = $2,
    resolved_at = now()
WHERE id = $1
RETURNING id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
`

type MarkDMQueueItemCancelledParams struct {
	ID      uuid.UUID `json:"id"`
	Outcome string    `json:"outcome"`
}

func (q *Queries) MarkDMQueueItemCancelled(ctx context.Context, arg MarkDMQueueItemCancelledParams) (DmQueueItem, error) {
	row := q.db.QueryRowContext(ctx, markDMQueueItemCancelled, arg.ID, arg.Outcome)
	var i DmQueueItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Kind,
		&i.PlayerName,
		&i.Summary,
		&i.ResolvePath,
		&i.Status,
		&i.Outcome,
		&i.Extra,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const markDMQueueItemResolved = `-- name: MarkDMQueueItemResolved :one
UPDATE dm_queue_items
SET status = 'resolved',
    outcome = $2,
    resolved_at = now()
WHERE id = $1
RETURNING id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
`

type MarkDMQueueItemResolvedParams struct {
	ID      uuid.UUID `json:"id"`
	Outcome string    `json:"outcome"`
}

func (q *Queries) MarkDMQueueItemResolved(ctx context.Context, arg MarkDMQueueItemResolvedParams) (DmQueueItem, error) {
	row := q.db.QueryRowContext(ctx, markDMQueueItemResolved, arg.ID, arg.Outcome)
	var i DmQueueItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Kind,
		&i.PlayerName,
		&i.Summary,
		&i.ResolvePath,
		&i.Status,
		&i.Outcome,
		&i.Extra,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateDMQueueItemMessageID = `-- name: UpdateDMQueueItemMessageID :one
UPDATE dm_queue_items
SET message_id = $2
WHERE id = $1
RETURNING id, campaign_id, guild_id, channel_id, message_id, kind, player_name, summary, resolve_path, status, outcome, extra, created_at, resolved_at
`

type UpdateDMQueueItemMessageIDParams struct {
	ID        uuid.UUID `json:"id"`
	MessageID string    `json:"message_id"`
}

func (q *Queries) UpdateDMQueueItemMessageID(ctx context.Context, arg UpdateDMQueueItemMessageIDParams) (DmQueueItem, error) {
	row := q.db.QueryRowContext(ctx, updateDMQueueItemMessageID, arg.ID, arg.MessageID)
	var i DmQueueItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.Kind,
		&i.PlayerName,
		&i.Summary,
		&i.ResolvePath,
		&i.Status,
		&i.Outcome,
		&i.Extra,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
