// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encounter_templates.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createEncounterTemplate = `-- name: CreateEncounterTemplate :one
INSERT INTO encounter_templates (campaign_id, map_id, name, display_name, creatures)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, map_id, name, display_name, creatures, created_at, updated_at
`

type CreateEncounterTemplateParams struct {
	CampaignID  uuid.UUID       `json:"campaign_id"`
	MapID       uuid.NullUUID   `json:"map_id"`
	Name        string          `json:"name"`
	DisplayName sql.NullString  `json:"display_name"`
	Creatures   json.RawMessage `json:"creatures"`
}

func (q *Queries) CreateEncounterTemplate(ctx context.Context, arg CreateEncounterTemplateParams) (EncounterTemplate, error) {
	row := q.db.QueryRowContext(ctx, createEncounterTemplate,
		arg.CampaignID,
		arg.MapID,
		arg.Name,
		arg.DisplayName,
		arg.Creatures,
	)
	var i EncounterTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.Creatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEncounterTemplate = `-- name: DeleteEncounterTemplate :exec
DELETE FROM encounter_templates WHERE id = $1 AND campaign_id = $2
`

type DeleteEncounterTemplateParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) DeleteEncounterTemplate(ctx context.Context, arg DeleteEncounterTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteEncounterTemplate, arg.ID, arg.CampaignID)
	return err
}

const getEncounterTemplate = `-- name: GetEncounterTemplate :one
SELECT id, campaign_id, map_id, name, display_name, creatures, created_at, updated_at FROM encounter_templates WHERE id = $1 AND campaign_id = $2
`

type GetEncounterTemplateParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) GetEncounterTemplate(ctx context.Context, arg GetEncounterTemplateParams) (EncounterTemplate, error) {
	row := q.db.QueryRowContext(ctx, getEncounterTemplate, arg.ID, arg.CampaignID)
	var i EncounterTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.Creatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEncounterTemplateUnchecked = `-- name: GetEncounterTemplateUnchecked :one
SELECT id, campaign_id, map_id, name, display_name, creatures, created_at, updated_at FROM encounter_templates WHERE id = $1
`

func (q *Queries) GetEncounterTemplateUnchecked(ctx context.Context, id uuid.UUID) (EncounterTemplate, error) {
	row := q.db.QueryRowContext(ctx, getEncounterTemplateUnchecked, id)
	var i EncounterTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.Creatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEncounterTemplatesByCampaignID = `-- name: ListEncounterTemplatesByCampaignID :many
SELECT id, campaign_id, map_id, name, display_name, creatures, created_at, updated_at FROM encounter_templates WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEncounterTemplatesByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]EncounterTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterTemplatesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterTemplate{}
	for rows.Next() {
		var i EncounterTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.MapID,
			&i.Name,
			&i.DisplayName,
			&i.Creatures,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEncounterTemplate = `-- name: UpdateEncounterTemplate :one
UPDATE encounter_templates SET
    map_id = $2,
    name = $3,
    display_name = $4,
    creatures = $5,
    updated_at = now()
WHERE id = $1 AND campaign_id = $6
RETURNING id, campaign_id, map_id, name, display_name, creatures, created_at, updated_at
`

type UpdateEncounterTemplateParams struct {
	ID          uuid.UUID       `json:"id"`
	MapID       uuid.NullUUID   `json:"map_id"`
	Name        string          `json:"name"`
	DisplayName sql.NullString  `json:"display_name"`
	Creatures   json.RawMessage `json:"creatures"`
	CampaignID  uuid.UUID       `json:"campaign_id"`
}

func (q *Queries) UpdateEncounterTemplate(ctx context.Context, arg UpdateEncounterTemplateParams) (EncounterTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateEncounterTemplate,
		arg.ID,
		arg.MapID,
		arg.Name,
		arg.DisplayName,
		arg.Creatures,
		arg.CampaignID,
	)
	var i EncounterTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.Creatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
