// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encounters.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEncounter = `-- name: CreateEncounter :one
INSERT INTO encounters (campaign_id, map_id, name, display_name, template_id, status, round_number)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at
`

type CreateEncounterParams struct {
	CampaignID  uuid.UUID      `json:"campaign_id"`
	MapID       uuid.NullUUID  `json:"map_id"`
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	TemplateID  uuid.NullUUID  `json:"template_id"`
	Status      string         `json:"status"`
	RoundNumber int32          `json:"round_number"`
}

func (q *Queries) CreateEncounter(ctx context.Context, arg CreateEncounterParams) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, createEncounter,
		arg.CampaignID,
		arg.MapID,
		arg.Name,
		arg.DisplayName,
		arg.TemplateID,
		arg.Status,
		arg.RoundNumber,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.TemplateID,
		&i.Status,
		&i.RoundNumber,
		&i.CurrentTurnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEncounter = `-- name: DeleteEncounter :exec
DELETE FROM encounters WHERE id = $1
`

func (q *Queries) DeleteEncounter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEncounter, id)
	return err
}

const getActiveEncounterIDByCharacterID = `-- name: GetActiveEncounterIDByCharacterID :one
SELECT e.id FROM encounters e
JOIN combatants cb ON cb.encounter_id = e.id
WHERE cb.character_id = $1 AND e.status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveEncounterIDByCharacterID(ctx context.Context, characterID uuid.NullUUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getActiveEncounterIDByCharacterID, characterID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCampaignByEncounterID = `-- name: GetCampaignByEncounterID :one
SELECT c.id, c.guild_id, c.dm_user_id, c.name, c.settings, c.status, c.created_at, c.updated_at FROM campaigns c
JOIN encounters e ON e.campaign_id = c.id
WHERE e.id = $1
`

func (q *Queries) GetCampaignByEncounterID(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByEncounterID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DmUserID,
		&i.Name,
		&i.Settings,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEncounter = `-- name: GetEncounter :one
SELECT id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at FROM encounters WHERE id = $1
`

func (q *Queries) GetEncounter(ctx context.Context, id uuid.UUID) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, getEncounter, id)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.TemplateID,
		&i.Status,
		&i.RoundNumber,
		&i.CurrentTurnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMostRecentCompletedEncounter = `-- name: GetMostRecentCompletedEncounter :one
SELECT id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at FROM encounters
WHERE campaign_id = $1 AND status = 'completed'
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentCompletedEncounter(ctx context.Context, campaignID uuid.UUID) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, getMostRecentCompletedEncounter, campaignID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.TemplateID,
		&i.Status,
		&i.RoundNumber,
		&i.CurrentTurnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEncountersByCampaignID = `-- name: ListEncountersByCampaignID :many
SELECT id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at FROM encounters WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEncountersByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]Encounter, error) {
	rows, err := q.db.QueryContext(ctx, listEncountersByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Encounter{}
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.MapID,
			&i.Name,
			&i.DisplayName,
			&i.TemplateID,
			&i.Status,
			&i.RoundNumber,
			&i.CurrentTurnID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEncounterCurrentTurn = `-- name: UpdateEncounterCurrentTurn :one
UPDATE encounters SET current_turn_id = $2, updated_at = now() WHERE id = $1 RETURNING id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at
`

type UpdateEncounterCurrentTurnParams struct {
	ID            uuid.UUID     `json:"id"`
	CurrentTurnID uuid.NullUUID `json:"current_turn_id"`
}

func (q *Queries) UpdateEncounterCurrentTurn(ctx context.Context, arg UpdateEncounterCurrentTurnParams) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, updateEncounterCurrentTurn, arg.ID, arg.CurrentTurnID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.TemplateID,
		&i.Status,
		&i.RoundNumber,
		&i.CurrentTurnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEncounterRound = `-- name: UpdateEncounterRound :one
UPDATE encounters SET round_number = $2, updated_at = now() WHERE id = $1 RETURNING id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at
`

type UpdateEncounterRoundParams struct {
	ID          uuid.UUID `json:"id"`
	RoundNumber int32     `json:"round_number"`
}

func (q *Queries) UpdateEncounterRound(ctx context.Context, arg UpdateEncounterRoundParams) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, updateEncounterRound, arg.ID, arg.RoundNumber)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.TemplateID,
		&i.Status,
		&i.RoundNumber,
		&i.CurrentTurnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEncounterStatus = `-- name: UpdateEncounterStatus :one
UPDATE encounters SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, campaign_id, map_id, name, display_name, template_id, status, round_number, current_turn_id, created_at, updated_at
`

type UpdateEncounterStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEncounterStatus(ctx context.Context, arg UpdateEncounterStatusParams) (Encounter, error) {
	row := q.db.QueryRowContext(ctx, updateEncounterStatus, arg.ID, arg.Status)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.MapID,
		&i.Name,
		&i.DisplayName,
		&i.TemplateID,
		&i.Status,
		&i.RoundNumber,
		&i.CurrentTurnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
