// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encounter_zones.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createEncounterZone = `-- name: CreateEncounterZone :one
INSERT INTO encounter_zones (
    encounter_id, source_combatant_id, source_spell, shape,
    origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id,
    zone_type, overlay_color, marker_icon, requires_concentration,
    expires_at_round, zone_triggers, triggered_this_round
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, encounter_id, source_combatant_id, source_spell, shape, origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id, zone_type, overlay_color, marker_icon, requires_concentration, expires_at_round, zone_triggers, triggered_this_round, created_at
`

type CreateEncounterZoneParams struct {
	EncounterID           uuid.UUID             `json:"encounter_id"`
	SourceCombatantID     uuid.UUID             `json:"source_combatant_id"`
	SourceSpell           string                `json:"source_spell"`
	Shape                 string                `json:"shape"`
	OriginCol             string                `json:"origin_col"`
	OriginRow             int32                 `json:"origin_row"`
	Dimensions            json.RawMessage       `json:"dimensions"`
	AnchorMode            string                `json:"anchor_mode"`
	AnchorCombatantID     uuid.NullUUID         `json:"anchor_combatant_id"`
	ZoneType              string                `json:"zone_type"`
	OverlayColor          string                `json:"overlay_color"`
	MarkerIcon            sql.NullString        `json:"marker_icon"`
	RequiresConcentration bool                  `json:"requires_concentration"`
	ExpiresAtRound        sql.NullInt32         `json:"expires_at_round"`
	ZoneTriggers          pqtype.NullRawMessage `json:"zone_triggers"`
	TriggeredThisRound    pqtype.NullRawMessage `json:"triggered_this_round"`
}

func (q *Queries) CreateEncounterZone(ctx context.Context, arg CreateEncounterZoneParams) (EncounterZone, error) {
	row := q.db.QueryRowContext(ctx, createEncounterZone,
		arg.EncounterID,
		arg.SourceCombatantID,
		arg.SourceSpell,
		arg.Shape,
		arg.OriginCol,
		arg.OriginRow,
		arg.Dimensions,
		arg.AnchorMode,
		arg.AnchorCombatantID,
		arg.ZoneType,
		arg.OverlayColor,
		arg.MarkerIcon,
		arg.RequiresConcentration,
		arg.ExpiresAtRound,
		arg.ZoneTriggers,
		arg.TriggeredThisRound,
	)
	var i EncounterZone
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.SourceCombatantID,
		&i.SourceSpell,
		&i.Shape,
		&i.OriginCol,
		&i.OriginRow,
		&i.Dimensions,
		&i.AnchorMode,
		&i.AnchorCombatantID,
		&i.ZoneType,
		&i.OverlayColor,
		&i.MarkerIcon,
		&i.RequiresConcentration,
		&i.ExpiresAtRound,
		&i.ZoneTriggers,
		&i.TriggeredThisRound,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConcentrationZonesByCombatant = `-- name: DeleteConcentrationZonesByCombatant :execrows
DELETE FROM encounter_zones
WHERE source_combatant_id = $1 AND requires_concentration = true
`

func (q *Queries) DeleteConcentrationZonesByCombatant(ctx context.Context, sourceCombatantID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConcentrationZonesByCombatant, sourceCombatantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEncounterZone = `-- name: DeleteEncounterZone :exec
DELETE FROM encounter_zones WHERE id = $1
`

func (q *Queries) DeleteEncounterZone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEncounterZone, id)
	return err
}

const deleteEncounterZonesByEncounterID = `-- name: DeleteEncounterZonesByEncounterID :exec
DELETE FROM encounter_zones WHERE encounter_id = $1
`

func (q *Queries) DeleteEncounterZonesByEncounterID(ctx context.Context, encounterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEncounterZonesByEncounterID, encounterID)
	return err
}

const deleteExpiredZones = `-- name: DeleteExpiredZones :exec
DELETE FROM encounter_zones
WHERE encounter_id = $1 AND expires_at_round IS NOT NULL AND expires_at_round <= $2
`

type DeleteExpiredZonesParams struct {
	EncounterID    uuid.UUID     `json:"encounter_id"`
	ExpiresAtRound sql.NullInt32 `json:"expires_at_round"`
}

func (q *Queries) DeleteExpiredZones(ctx context.Context, arg DeleteExpiredZonesParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredZones, arg.EncounterID, arg.ExpiresAtRound)
	return err
}

const getEncounterZone = `-- name: GetEncounterZone :one
SELECT id, encounter_id, source_combatant_id, source_spell, shape, origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id, zone_type, overlay_color, marker_icon, requires_concentration, expires_at_round, zone_triggers, triggered_this_round, created_at FROM encounter_zones WHERE id = $1
`

func (q *Queries) GetEncounterZone(ctx context.Context, id uuid.UUID) (EncounterZone, error) {
	row := q.db.QueryRowContext(ctx, getEncounterZone, id)
	var i EncounterZone
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.SourceCombatantID,
		&i.SourceSpell,
		&i.Shape,
		&i.OriginCol,
		&i.OriginRow,
		&i.Dimensions,
		&i.AnchorMode,
		&i.AnchorCombatantID,
		&i.ZoneType,
		&i.OverlayColor,
		&i.MarkerIcon,
		&i.RequiresConcentration,
		&i.ExpiresAtRound,
		&i.ZoneTriggers,
		&i.TriggeredThisRound,
		&i.CreatedAt,
	)
	return i, err
}

const listConcentrationZonesByCombatant = `-- name: ListConcentrationZonesByCombatant :many
SELECT id, encounter_id, source_combatant_id, source_spell, shape, origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id, zone_type, overlay_color, marker_icon, requires_concentration, expires_at_round, zone_triggers, triggered_this_round, created_at FROM encounter_zones
WHERE source_combatant_id = $1 AND requires_concentration = true
ORDER BY created_at
`

func (q *Queries) ListConcentrationZonesByCombatant(ctx context.Context, sourceCombatantID uuid.UUID) ([]EncounterZone, error) {
	rows, err := q.db.QueryContext(ctx, listConcentrationZonesByCombatant, sourceCombatantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterZone{}
	for rows.Next() {
		var i EncounterZone
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.SourceCombatantID,
			&i.SourceSpell,
			&i.Shape,
			&i.OriginCol,
			&i.OriginRow,
			&i.Dimensions,
			&i.AnchorMode,
			&i.AnchorCombatantID,
			&i.ZoneType,
			&i.OverlayColor,
			&i.MarkerIcon,
			&i.RequiresConcentration,
			&i.ExpiresAtRound,
			&i.ZoneTriggers,
			&i.TriggeredThisRound,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterZonesByEncounterID = `-- name: ListEncounterZonesByEncounterID :many
SELECT id, encounter_id, source_combatant_id, source_spell, shape, origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id, zone_type, overlay_color, marker_icon, requires_concentration, expires_at_round, zone_triggers, triggered_this_round, created_at FROM encounter_zones WHERE encounter_id = $1 ORDER BY created_at
`

func (q *Queries) ListEncounterZonesByEncounterID(ctx context.Context, encounterID uuid.UUID) ([]EncounterZone, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterZonesByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterZone{}
	for rows.Next() {
		var i EncounterZone
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.SourceCombatantID,
			&i.SourceSpell,
			&i.Shape,
			&i.OriginCol,
			&i.OriginRow,
			&i.Dimensions,
			&i.AnchorMode,
			&i.AnchorCombatantID,
			&i.ZoneType,
			&i.OverlayColor,
			&i.MarkerIcon,
			&i.RequiresConcentration,
			&i.ExpiresAtRound,
			&i.ZoneTriggers,
			&i.TriggeredThisRound,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllTriggeredThisRound = `-- name: ResetAllTriggeredThisRound :exec
UPDATE encounter_zones
SET triggered_this_round = '{}'
WHERE encounter_id = $1
`

func (q *Queries) ResetAllTriggeredThisRound(ctx context.Context, encounterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetAllTriggeredThisRound, encounterID)
	return err
}

const updateEncounterZoneOrigin = `-- name: UpdateEncounterZoneOrigin :one
UPDATE encounter_zones
SET origin_col = $2, origin_row = $3
WHERE id = $1
RETURNING id, encounter_id, source_combatant_id, source_spell, shape, origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id, zone_type, overlay_color, marker_icon, requires_concentration, expires_at_round, zone_triggers, triggered_this_round, created_at
`

type UpdateEncounterZoneOriginParams struct {
	ID        uuid.UUID `json:"id"`
	OriginCol string    `json:"origin_col"`
	OriginRow int32     `json:"origin_row"`
}

func (q *Queries) UpdateEncounterZoneOrigin(ctx context.Context, arg UpdateEncounterZoneOriginParams) (EncounterZone, error) {
	row := q.db.QueryRowContext(ctx, updateEncounterZoneOrigin, arg.ID, arg.OriginCol, arg.OriginRow)
	var i EncounterZone
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.SourceCombatantID,
		&i.SourceSpell,
		&i.Shape,
		&i.OriginCol,
		&i.OriginRow,
		&i.Dimensions,
		&i.AnchorMode,
		&i.AnchorCombatantID,
		&i.ZoneType,
		&i.OverlayColor,
		&i.MarkerIcon,
		&i.RequiresConcentration,
		&i.ExpiresAtRound,
		&i.ZoneTriggers,
		&i.TriggeredThisRound,
		&i.CreatedAt,
	)
	return i, err
}

const updateEncounterZoneTriggeredThisRound = `-- name: UpdateEncounterZoneTriggeredThisRound :one
UPDATE encounter_zones
SET triggered_this_round = $2
WHERE id = $1
RETURNING id, encounter_id, source_combatant_id, source_spell, shape, origin_col, origin_row, dimensions, anchor_mode, anchor_combatant_id, zone_type, overlay_color, marker_icon, requires_concentration, expires_at_round, zone_triggers, triggered_this_round, created_at
`

type UpdateEncounterZoneTriggeredThisRoundParams struct {
	ID                 uuid.UUID             `json:"id"`
	TriggeredThisRound pqtype.NullRawMessage `json:"triggered_this_round"`
}

func (q *Queries) UpdateEncounterZoneTriggeredThisRound(ctx context.Context, arg UpdateEncounterZoneTriggeredThisRoundParams) (EncounterZone, error) {
	row := q.db.QueryRowContext(ctx, updateEncounterZoneTriggeredThisRound, arg.ID, arg.TriggeredThisRound)
	var i EncounterZone
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.SourceCombatantID,
		&i.SourceSpell,
		&i.Shape,
		&i.OriginCol,
		&i.OriginRow,
		&i.Dimensions,
		&i.AnchorMode,
		&i.AnchorCombatantID,
		&i.ZoneType,
		&i.OverlayColor,
		&i.MarkerIcon,
		&i.RequiresConcentration,
		&i.ExpiresAtRound,
		&i.ZoneTriggers,
		&i.TriggeredThisRound,
		&i.CreatedAt,
	)
	return i, err
}
