// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feats.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countFeats = `-- name: CountFeats :one
SELECT count(*) FROM feats
`

func (q *Queries) CountFeats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHomebrewFeat = `-- name: DeleteHomebrewFeat :execrows
DELETE FROM feats WHERE id = $1 AND homebrew = true AND campaign_id = $2
`

type DeleteHomebrewFeatParams struct {
	ID         string        `json:"id"`
	CampaignID uuid.NullUUID `json:"campaign_id"`
}

func (q *Queries) DeleteHomebrewFeat(ctx context.Context, arg DeleteHomebrewFeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHomebrewFeat, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFeat = `-- name: GetFeat :one
SELECT id, name, description, prerequisites, asi_bonus, mechanical_effect, created_at, updated_at, campaign_id, homebrew, source FROM feats WHERE id = $1
`

func (q *Queries) GetFeat(ctx context.Context, id string) (Feat, error) {
	row := q.db.QueryRowContext(ctx, getFeat, id)
	var i Feat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Prerequisites,
		&i.AsiBonus,
		&i.MechanicalEffect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
		&i.Homebrew,
		&i.Source,
	)
	return i, err
}

const listFeats = `-- name: ListFeats :many
SELECT id, name, description, prerequisites, asi_bonus, mechanical_effect, created_at, updated_at, campaign_id, homebrew, source FROM feats ORDER BY name
`

func (q *Queries) ListFeats(ctx context.Context) ([]Feat, error) {
	rows, err := q.db.QueryContext(ctx, listFeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feat{}
	for rows.Next() {
		var i Feat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Prerequisites,
			&i.AsiBonus,
			&i.MechanicalEffect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignID,
			&i.Homebrew,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeat = `-- name: UpsertFeat :exec
INSERT INTO feats (id, name, description, prerequisites, asi_bonus, mechanical_effect, campaign_id, homebrew, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    prerequisites = EXCLUDED.prerequisites,
    asi_bonus = EXCLUDED.asi_bonus,
    mechanical_effect = EXCLUDED.mechanical_effect,
    campaign_id = EXCLUDED.campaign_id,
    homebrew = EXCLUDED.homebrew,
    source = EXCLUDED.source,
    updated_at = now()
`

type UpsertFeatParams struct {
	ID               string                `json:"id"`
	Name             string                `json:"name"`
	Description      string                `json:"description"`
	Prerequisites    pqtype.NullRawMessage `json:"prerequisites"`
	AsiBonus         pqtype.NullRawMessage `json:"asi_bonus"`
	MechanicalEffect pqtype.NullRawMessage `json:"mechanical_effect"`
	CampaignID       uuid.NullUUID         `json:"campaign_id"`
	Homebrew         sql.NullBool          `json:"homebrew"`
	Source           sql.NullString        `json:"source"`
}

func (q *Queries) UpsertFeat(ctx context.Context, arg UpsertFeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeat,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Prerequisites,
		arg.AsiBonus,
		arg.MechanicalEffect,
		arg.CampaignID,
		arg.Homebrew,
		arg.Source,
	)
	return err
}
