// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: initiative_tracker_messages.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
)

const deleteInitiativeTrackerMessage = `-- name: DeleteInitiativeTrackerMessage :exec
DELETE FROM initiative_tracker_messages WHERE encounter_id = $1
`

func (q *Queries) DeleteInitiativeTrackerMessage(ctx context.Context, encounterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInitiativeTrackerMessage, encounterID)
	return err
}

const getInitiativeTrackerMessage = `-- name: GetInitiativeTrackerMessage :one
SELECT encounter_id, channel_id, message_id, updated_at
FROM initiative_tracker_messages
WHERE encounter_id = $1
`

func (q *Queries) GetInitiativeTrackerMessage(ctx context.Context, encounterID uuid.UUID) (InitiativeTrackerMessage, error) {
	row := q.db.QueryRowContext(ctx, getInitiativeTrackerMessage, encounterID)
	var i InitiativeTrackerMessage
	err := row.Scan(
		&i.EncounterID,
		&i.ChannelID,
		&i.MessageID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInitiativeTrackerMessage = `-- name: UpsertInitiativeTrackerMessage :exec
INSERT INTO initiative_tracker_messages (encounter_id, channel_id, message_id)
VALUES ($1, $2, $3)
ON CONFLICT (encounter_id) DO UPDATE SET
    channel_id = EXCLUDED.channel_id,
    message_id = EXCLUDED.message_id,
    updated_at = now()
`

type UpsertInitiativeTrackerMessageParams struct {
	EncounterID uuid.UUID `json:"encounter_id"`
	ChannelID   string    `json:"channel_id"`
	MessageID   string    `json:"message_id"`
}

func (q *Queries) UpsertInitiativeTrackerMessage(ctx context.Context, arg UpsertInitiativeTrackerMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertInitiativeTrackerMessage, arg.EncounterID, arg.ChannelID, arg.MessageID)
	return err
}
