// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package refdata

import (
	"context"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getItem = `-- name: GetItem :one
SELECT id, name, category, default_quantity, stackable, created_at, updated_at FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.DefaultQuantity,
		&i.Stackable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, category, default_quantity, stackable, created_at, updated_at FROM items ORDER BY name
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.DefaultQuantity,
			&i.Stackable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO items (id, name, category, default_quantity, stackable)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    default_quantity = EXCLUDED.default_quantity,
    stackable = EXCLUDED.stackable,
    updated_at = now()
`

type UpsertItemParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Category        string `json:"category"`
	DefaultQuantity int32  `json:"default_quantity"`
	Stackable       bool   `json:"stackable"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertItem,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.DefaultQuantity,
		arg.Stackable,
	)
	return err
}
