// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loot_pools.sql

package refdata

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimLootPoolItem = `-- name: ClaimLootPoolItem :one
UPDATE loot_pool_items SET claimed_by = $2, claimed_at = now(), updated_at = now()
WHERE id = $1 AND claimed_by IS NULL
RETURNING id, loot_pool_id, item_id, name, description, quantity, type, claimed_by, claimed_at, is_magic, magic_bonus, magic_properties, requires_attunement, rarity, created_at, updated_at
`

type ClaimLootPoolItemParams struct {
	ID        uuid.UUID     `json:"id"`
	ClaimedBy uuid.NullUUID `json:"claimed_by"`
}

func (q *Queries) ClaimLootPoolItem(ctx context.Context, arg ClaimLootPoolItemParams) (LootPoolItem, error) {
	row := q.db.QueryRowContext(ctx, claimLootPoolItem, arg.ID, arg.ClaimedBy)
	var i LootPoolItem
	err := row.Scan(
		&i.ID,
		&i.LootPoolID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Type,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.IsMagic,
		&i.MagicBonus,
		&i.MagicProperties,
		&i.RequiresAttunement,
		&i.Rarity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLootPool = `-- name: CreateLootPool :one
INSERT INTO loot_pools (encounter_id, campaign_id, gold_total, status)
VALUES ($1, $2, $3, 'open')
RETURNING id, encounter_id, campaign_id, gold_total, status, created_at, updated_at
`

type CreateLootPoolParams struct {
	EncounterID uuid.UUID `json:"encounter_id"`
	CampaignID  uuid.UUID `json:"campaign_id"`
	GoldTotal   int32     `json:"gold_total"`
}

func (q *Queries) CreateLootPool(ctx context.Context, arg CreateLootPoolParams) (LootPool, error) {
	row := q.db.QueryRowContext(ctx, createLootPool, arg.EncounterID, arg.CampaignID, arg.GoldTotal)
	var i LootPool
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CampaignID,
		&i.GoldTotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLootPoolItem = `-- name: CreateLootPoolItem :one
INSERT INTO loot_pool_items (
    loot_pool_id, item_id, name, description, quantity, type,
    is_magic, magic_bonus, magic_properties, requires_attunement, rarity
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, loot_pool_id, item_id, name, description, quantity, type, claimed_by, claimed_at, is_magic, magic_bonus, magic_properties, requires_attunement, rarity, created_at, updated_at
`

type CreateLootPoolItemParams struct {
	LootPoolID         uuid.UUID      `json:"loot_pool_id"`
	ItemID             sql.NullString `json:"item_id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	Quantity           int32          `json:"quantity"`
	Type               string         `json:"type"`
	IsMagic            bool           `json:"is_magic"`
	MagicBonus         int32          `json:"magic_bonus"`
	MagicProperties    string         `json:"magic_properties"`
	RequiresAttunement bool           `json:"requires_attunement"`
	Rarity             string         `json:"rarity"`
}

func (q *Queries) CreateLootPoolItem(ctx context.Context, arg CreateLootPoolItemParams) (LootPoolItem, error) {
	row := q.db.QueryRowContext(ctx, createLootPoolItem,
		arg.LootPoolID,
		arg.ItemID,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.Type,
		arg.IsMagic,
		arg.MagicBonus,
		arg.MagicProperties,
		arg.RequiresAttunement,
		arg.Rarity,
	)
	var i LootPoolItem
	err := row.Scan(
		&i.ID,
		&i.LootPoolID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Type,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.IsMagic,
		&i.MagicBonus,
		&i.MagicProperties,
		&i.RequiresAttunement,
		&i.Rarity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLootPool = `-- name: DeleteLootPool :exec
DELETE FROM loot_pools WHERE id = $1
`

func (q *Queries) DeleteLootPool(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLootPool, id)
	return err
}

const deleteLootPoolItem = `-- name: DeleteLootPoolItem :exec
DELETE FROM loot_pool_items WHERE id = $1
`

func (q *Queries) DeleteLootPoolItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLootPoolItem, id)
	return err
}

const deleteUnclaimedLootPoolItems = `-- name: DeleteUnclaimedLootPoolItems :exec
DELETE FROM loot_pool_items WHERE loot_pool_id = $1 AND claimed_by IS NULL
`

func (q *Queries) DeleteUnclaimedLootPoolItems(ctx context.Context, lootPoolID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUnclaimedLootPoolItems, lootPoolID)
	return err
}

const getLootPool = `-- name: GetLootPool :one
SELECT id, encounter_id, campaign_id, gold_total, status, created_at, updated_at FROM loot_pools WHERE id = $1
`

func (q *Queries) GetLootPool(ctx context.Context, id uuid.UUID) (LootPool, error) {
	row := q.db.QueryRowContext(ctx, getLootPool, id)
	var i LootPool
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CampaignID,
		&i.GoldTotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLootPoolByEncounter = `-- name: GetLootPoolByEncounter :one
SELECT id, encounter_id, campaign_id, gold_total, status, created_at, updated_at FROM loot_pools WHERE encounter_id = $1
`

func (q *Queries) GetLootPoolByEncounter(ctx context.Context, encounterID uuid.UUID) (LootPool, error) {
	row := q.db.QueryRowContext(ctx, getLootPoolByEncounter, encounterID)
	var i LootPool
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CampaignID,
		&i.GoldTotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLootPoolItem = `-- name: GetLootPoolItem :one
SELECT id, loot_pool_id, item_id, name, description, quantity, type, claimed_by, claimed_at, is_magic, magic_bonus, magic_properties, requires_attunement, rarity, created_at, updated_at FROM loot_pool_items WHERE id = $1
`

func (q *Queries) GetLootPoolItem(ctx context.Context, id uuid.UUID) (LootPoolItem, error) {
	row := q.db.QueryRowContext(ctx, getLootPoolItem, id)
	var i LootPoolItem
	err := row.Scan(
		&i.ID,
		&i.LootPoolID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Type,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.IsMagic,
		&i.MagicBonus,
		&i.MagicProperties,
		&i.RequiresAttunement,
		&i.Rarity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLootPoolItems = `-- name: ListLootPoolItems :many
SELECT id, loot_pool_id, item_id, name, description, quantity, type, claimed_by, claimed_at, is_magic, magic_bonus, magic_properties, requires_attunement, rarity, created_at, updated_at FROM loot_pool_items WHERE loot_pool_id = $1 ORDER BY created_at
`

func (q *Queries) ListLootPoolItems(ctx context.Context, lootPoolID uuid.UUID) ([]LootPoolItem, error) {
	rows, err := q.db.QueryContext(ctx, listLootPoolItems, lootPoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LootPoolItem{}
	for rows.Next() {
		var i LootPoolItem
		if err := rows.Scan(
			&i.ID,
			&i.LootPoolID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Type,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.IsMagic,
			&i.MagicBonus,
			&i.MagicProperties,
			&i.RequiresAttunement,
			&i.Rarity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerCharactersByCampaignApproved = `-- name: ListPlayerCharactersByCampaignApproved :many
SELECT pc.id, pc.campaign_id, pc.character_id, pc.discord_user_id, pc.status, pc.dm_feedback, pc.created_via, pc.created_at, pc.updated_at, c.name AS character_name, c.gold
FROM player_characters pc
JOIN characters c ON c.id = pc.character_id
WHERE pc.campaign_id = $1 AND pc.status = 'approved'
ORDER BY c.name
`

type ListPlayerCharactersByCampaignApprovedRow struct {
	ID            uuid.UUID      `json:"id"`
	CampaignID    uuid.UUID      `json:"campaign_id"`
	CharacterID   uuid.UUID      `json:"character_id"`
	DiscordUserID string         `json:"discord_user_id"`
	Status        string         `json:"status"`
	DmFeedback    sql.NullString `json:"dm_feedback"`
	CreatedVia    string         `json:"created_via"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	CharacterName string         `json:"character_name"`
	Gold          int32          `json:"gold"`
}

func (q *Queries) ListPlayerCharactersByCampaignApproved(ctx context.Context, campaignID uuid.UUID) ([]ListPlayerCharactersByCampaignApprovedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerCharactersByCampaignApproved, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerCharactersByCampaignApprovedRow{}
	for rows.Next() {
		var i ListPlayerCharactersByCampaignApprovedRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CharacterID,
			&i.DiscordUserID,
			&i.Status,
			&i.DmFeedback,
			&i.CreatedVia,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CharacterName,
			&i.Gold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLootPoolGold = `-- name: UpdateLootPoolGold :one
UPDATE loot_pools SET gold_total = $2, updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, campaign_id, gold_total, status, created_at, updated_at
`

type UpdateLootPoolGoldParams struct {
	ID        uuid.UUID `json:"id"`
	GoldTotal int32     `json:"gold_total"`
}

func (q *Queries) UpdateLootPoolGold(ctx context.Context, arg UpdateLootPoolGoldParams) (LootPool, error) {
	row := q.db.QueryRowContext(ctx, updateLootPoolGold, arg.ID, arg.GoldTotal)
	var i LootPool
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CampaignID,
		&i.GoldTotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLootPoolItem = `-- name: UpdateLootPoolItem :one
UPDATE loot_pool_items SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    quantity = COALESCE($4, quantity),
    updated_at = now()
WHERE id = $1
RETURNING id, loot_pool_id, item_id, name, description, quantity, type, claimed_by, claimed_at, is_magic, magic_bonus, magic_properties, requires_attunement, rarity, created_at, updated_at
`

type UpdateLootPoolItemParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Quantity    sql.NullInt32  `json:"quantity"`
}

func (q *Queries) UpdateLootPoolItem(ctx context.Context, arg UpdateLootPoolItemParams) (LootPoolItem, error) {
	row := q.db.QueryRowContext(ctx, updateLootPoolItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Quantity,
	)
	var i LootPoolItem
	err := row.Scan(
		&i.ID,
		&i.LootPoolID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Type,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.IsMagic,
		&i.MagicBonus,
		&i.MagicProperties,
		&i.RequiresAttunement,
		&i.Rarity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLootPoolStatus = `-- name: UpdateLootPoolStatus :one
UPDATE loot_pools SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, campaign_id, gold_total, status, created_at, updated_at
`

type UpdateLootPoolStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLootPoolStatus(ctx context.Context, arg UpdateLootPoolStatusParams) (LootPool, error) {
	row := q.db.QueryRowContext(ctx, updateLootPoolStatus, arg.ID, arg.Status)
	var i LootPool
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CampaignID,
		&i.GoldTotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
