// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_items.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countMagicItems = `-- name: CountMagicItems :one
SELECT count(*) FROM magic_items
`

func (q *Queries) CountMagicItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMagicItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHomebrewMagicItem = `-- name: DeleteHomebrewMagicItem :execrows
DELETE FROM magic_items WHERE id = $1 AND homebrew = true AND campaign_id = $2
`

type DeleteHomebrewMagicItemParams struct {
	ID         string        `json:"id"`
	CampaignID uuid.NullUUID `json:"campaign_id"`
}

func (q *Queries) DeleteHomebrewMagicItem(ctx context.Context, arg DeleteHomebrewMagicItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHomebrewMagicItem, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMagicItem = `-- name: GetMagicItem :one
SELECT id, campaign_id, name, base_item_type, base_item_id, rarity, requires_attunement, attunement_restriction, magic_bonus, passive_effects, active_abilities, charges, description, homebrew, source, created_at, updated_at FROM magic_items WHERE id = $1
`

func (q *Queries) GetMagicItem(ctx context.Context, id string) (MagicItem, error) {
	row := q.db.QueryRowContext(ctx, getMagicItem, id)
	var i MagicItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.BaseItemType,
		&i.BaseItemID,
		&i.Rarity,
		&i.RequiresAttunement,
		&i.AttunementRestriction,
		&i.MagicBonus,
		&i.PassiveEffects,
		&i.ActiveAbilities,
		&i.Charges,
		&i.Description,
		&i.Homebrew,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMagicItems = `-- name: ListMagicItems :many
SELECT id, campaign_id, name, base_item_type, base_item_id, rarity, requires_attunement, attunement_restriction, magic_bonus, passive_effects, active_abilities, charges, description, homebrew, source, created_at, updated_at FROM magic_items ORDER BY name
`

func (q *Queries) ListMagicItems(ctx context.Context) ([]MagicItem, error) {
	rows, err := q.db.QueryContext(ctx, listMagicItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicItem{}
	for rows.Next() {
		var i MagicItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.BaseItemType,
			&i.BaseItemID,
			&i.Rarity,
			&i.RequiresAttunement,
			&i.AttunementRestriction,
			&i.MagicBonus,
			&i.PassiveEffects,
			&i.ActiveAbilities,
			&i.Charges,
			&i.Description,
			&i.Homebrew,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMagicItemsByRarity = `-- name: ListMagicItemsByRarity :many
SELECT id, campaign_id, name, base_item_type, base_item_id, rarity, requires_attunement, attunement_restriction, magic_bonus, passive_effects, active_abilities, charges, description, homebrew, source, created_at, updated_at FROM magic_items WHERE rarity = $1 ORDER BY name
`

func (q *Queries) ListMagicItemsByRarity(ctx context.Context, rarity string) ([]MagicItem, error) {
	rows, err := q.db.QueryContext(ctx, listMagicItemsByRarity, rarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicItem{}
	for rows.Next() {
		var i MagicItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.BaseItemType,
			&i.BaseItemID,
			&i.Rarity,
			&i.RequiresAttunement,
			&i.AttunementRestriction,
			&i.MagicBonus,
			&i.PassiveEffects,
			&i.ActiveAbilities,
			&i.Charges,
			&i.Description,
			&i.Homebrew,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMagicItemsByType = `-- name: ListMagicItemsByType :many
SELECT id, campaign_id, name, base_item_type, base_item_id, rarity, requires_attunement, attunement_restriction, magic_bonus, passive_effects, active_abilities, charges, description, homebrew, source, created_at, updated_at FROM magic_items WHERE base_item_type = $1 ORDER BY name
`

func (q *Queries) ListMagicItemsByType(ctx context.Context, baseItemType sql.NullString) ([]MagicItem, error) {
	rows, err := q.db.QueryContext(ctx, listMagicItemsByType, baseItemType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicItem{}
	for rows.Next() {
		var i MagicItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.BaseItemType,
			&i.BaseItemID,
			&i.Rarity,
			&i.RequiresAttunement,
			&i.AttunementRestriction,
			&i.MagicBonus,
			&i.PassiveEffects,
			&i.ActiveAbilities,
			&i.Charges,
			&i.Description,
			&i.Homebrew,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMagicItem = `-- name: UpsertMagicItem :exec
INSERT INTO magic_items (id, campaign_id, name, base_item_type, base_item_id, rarity, requires_attunement, attunement_restriction, magic_bonus, passive_effects, active_abilities, charges, description, homebrew, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE SET
    campaign_id = EXCLUDED.campaign_id,
    name = EXCLUDED.name,
    base_item_type = EXCLUDED.base_item_type,
    base_item_id = EXCLUDED.base_item_id,
    rarity = EXCLUDED.rarity,
    requires_attunement = EXCLUDED.requires_attunement,
    attunement_restriction = EXCLUDED.attunement_restriction,
    magic_bonus = EXCLUDED.magic_bonus,
    passive_effects = EXCLUDED.passive_effects,
    active_abilities = EXCLUDED.active_abilities,
    charges = EXCLUDED.charges,
    description = EXCLUDED.description,
    homebrew = EXCLUDED.homebrew,
    source = EXCLUDED.source,
    updated_at = now()
`

type UpsertMagicItemParams struct {
	ID                    string                `json:"id"`
	CampaignID            uuid.NullUUID         `json:"campaign_id"`
	Name                  string                `json:"name"`
	BaseItemType          sql.NullString        `json:"base_item_type"`
	BaseItemID            sql.NullString        `json:"base_item_id"`
	Rarity                string                `json:"rarity"`
	RequiresAttunement    sql.NullBool          `json:"requires_attunement"`
	AttunementRestriction sql.NullString        `json:"attunement_restriction"`
	MagicBonus            sql.NullInt32         `json:"magic_bonus"`
	PassiveEffects        pqtype.NullRawMessage `json:"passive_effects"`
	ActiveAbilities       pqtype.NullRawMessage `json:"active_abilities"`
	Charges               pqtype.NullRawMessage `json:"charges"`
	Description           string                `json:"description"`
	Homebrew              sql.NullBool          `json:"homebrew"`
	Source                sql.NullString        `json:"source"`
}

func (q *Queries) UpsertMagicItem(ctx context.Context, arg UpsertMagicItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertMagicItem,
		arg.ID,
		arg.CampaignID,
		arg.Name,
		arg.BaseItemType,
		arg.BaseItemID,
		arg.Rarity,
		arg.RequiresAttunement,
		arg.AttunementRestriction,
		arg.MagicBonus,
		arg.PassiveEffects,
		arg.ActiveAbilities,
		arg.Charges,
		arg.Description,
		arg.Homebrew,
		arg.Source,
	)
	return err
}
