// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maps.sql

package refdata

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createMap = `-- name: CreateMap :one
INSERT INTO maps (campaign_id, name, width_squares, height_squares, tiled_json, background_image_id, tileset_refs)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, name, width_squares, height_squares, tiled_json, background_image_id, tileset_refs, created_at, updated_at
`

type CreateMapParams struct {
	CampaignID        uuid.UUID             `json:"campaign_id"`
	Name              string                `json:"name"`
	WidthSquares      int32                 `json:"width_squares"`
	HeightSquares     int32                 `json:"height_squares"`
	TiledJson         json.RawMessage       `json:"tiled_json"`
	BackgroundImageID uuid.NullUUID         `json:"background_image_id"`
	TilesetRefs       pqtype.NullRawMessage `json:"tileset_refs"`
}

func (q *Queries) CreateMap(ctx context.Context, arg CreateMapParams) (Map, error) {
	row := q.db.QueryRowContext(ctx, createMap,
		arg.CampaignID,
		arg.Name,
		arg.WidthSquares,
		arg.HeightSquares,
		arg.TiledJson,
		arg.BackgroundImageID,
		arg.TilesetRefs,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.WidthSquares,
		&i.HeightSquares,
		&i.TiledJson,
		&i.BackgroundImageID,
		&i.TilesetRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMap = `-- name: DeleteMap :exec
DELETE FROM maps WHERE id = $1 AND campaign_id = $2
`

type DeleteMapParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) DeleteMap(ctx context.Context, arg DeleteMapParams) error {
	_, err := q.db.ExecContext(ctx, deleteMap, arg.ID, arg.CampaignID)
	return err
}

const getMapByID = `-- name: GetMapByID :one
SELECT id, campaign_id, name, width_squares, height_squares, tiled_json, background_image_id, tileset_refs, created_at, updated_at FROM maps WHERE id = $1 AND campaign_id = $2
`

type GetMapByIDParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) GetMapByID(ctx context.Context, arg GetMapByIDParams) (Map, error) {
	row := q.db.QueryRowContext(ctx, getMapByID, arg.ID, arg.CampaignID)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.WidthSquares,
		&i.HeightSquares,
		&i.TiledJson,
		&i.BackgroundImageID,
		&i.TilesetRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapByIDUnchecked = `-- name: GetMapByIDUnchecked :one
SELECT id, campaign_id, name, width_squares, height_squares, tiled_json, background_image_id, tileset_refs, created_at, updated_at FROM maps WHERE id = $1
`

func (q *Queries) GetMapByIDUnchecked(ctx context.Context, id uuid.UUID) (Map, error) {
	row := q.db.QueryRowContext(ctx, getMapByIDUnchecked, id)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.WidthSquares,
		&i.HeightSquares,
		&i.TiledJson,
		&i.BackgroundImageID,
		&i.TilesetRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMapsByCampaignID = `-- name: ListMapsByCampaignID :many
SELECT id, campaign_id, name, width_squares, height_squares, tiled_json, background_image_id, tileset_refs, created_at, updated_at FROM maps WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMapsByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]Map, error) {
	rows, err := q.db.QueryContext(ctx, listMapsByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Map{}
	for rows.Next() {
		var i Map
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.WidthSquares,
			&i.HeightSquares,
			&i.TiledJson,
			&i.BackgroundImageID,
			&i.TilesetRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMap = `-- name: UpdateMap :one
UPDATE maps SET
    name = $2,
    width_squares = $3,
    height_squares = $4,
    tiled_json = $5,
    background_image_id = $6,
    tileset_refs = $7,
    updated_at = now()
WHERE id = $1 AND campaign_id = $8
RETURNING id, campaign_id, name, width_squares, height_squares, tiled_json, background_image_id, tileset_refs, created_at, updated_at
`

type UpdateMapParams struct {
	ID                uuid.UUID             `json:"id"`
	Name              string                `json:"name"`
	WidthSquares      int32                 `json:"width_squares"`
	HeightSquares     int32                 `json:"height_squares"`
	TiledJson         json.RawMessage       `json:"tiled_json"`
	BackgroundImageID uuid.NullUUID         `json:"background_image_id"`
	TilesetRefs       pqtype.NullRawMessage `json:"tileset_refs"`
	CampaignID        uuid.UUID             `json:"campaign_id"`
}

func (q *Queries) UpdateMap(ctx context.Context, arg UpdateMapParams) (Map, error) {
	row := q.db.QueryRowContext(ctx, updateMap,
		arg.ID,
		arg.Name,
		arg.WidthSquares,
		arg.HeightSquares,
		arg.TiledJson,
		arg.BackgroundImageID,
		arg.TilesetRefs,
		arg.CampaignID,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.WidthSquares,
		&i.HeightSquares,
		&i.TiledJson,
		&i.BackgroundImageID,
		&i.TilesetRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
