// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package refdata

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActionLog struct {
	ID          uuid.UUID             `json:"id"`
	TurnID      uuid.UUID             `json:"turn_id"`
	EncounterID uuid.UUID             `json:"encounter_id"`
	ActionType  string                `json:"action_type"`
	ActorID     uuid.UUID             `json:"actor_id"`
	TargetID    uuid.NullUUID         `json:"target_id"`
	Description sql.NullString        `json:"description"`
	BeforeState json.RawMessage       `json:"before_state"`
	AfterState  json.RawMessage       `json:"after_state"`
	DiceRolls   pqtype.NullRawMessage `json:"dice_rolls"`
	CreatedAt   time.Time             `json:"created_at"`
}

type Armor struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	AcBase        int32           `json:"ac_base"`
	AcDexBonus    sql.NullBool    `json:"ac_dex_bonus"`
	AcDexMax      sql.NullInt32   `json:"ac_dex_max"`
	StrengthReq   sql.NullInt32   `json:"strength_req"`
	StealthDisadv sql.NullBool    `json:"stealth_disadv"`
	ArmorType     string          `json:"armor_type"`
	WeightLb      sql.NullFloat64 `json:"weight_lb"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Asset struct {
	ID           uuid.UUID `json:"id"`
	CampaignID   uuid.UUID `json:"campaign_id"`
	Type         string    `json:"type"`
	OriginalName string    `json:"original_name"`
	MimeType     string    `json:"mime_type"`
	ByteSize     int64     `json:"byte_size"`
	StoragePath  string    `json:"storage_path"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Campaign struct {
	ID        uuid.UUID             `json:"id"`
	GuildID   string                `json:"guild_id"`
	DmUserID  string                `json:"dm_user_id"`
	Name      string                `json:"name"`
	Settings  pqtype.NullRawMessage `json:"settings"`
	Status    string                `json:"status"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}

type Character struct {
	ID               uuid.UUID             `json:"id"`
	CampaignID       uuid.UUID             `json:"campaign_id"`
	Name             string                `json:"name"`
	Race             string                `json:"race"`
	Classes          json.RawMessage       `json:"classes"`
	Level            int32                 `json:"level"`
	AbilityScores    json.RawMessage       `json:"ability_scores"`
	HpMax            int32                 `json:"hp_max"`
	HpCurrent        int32                 `json:"hp_current"`
	TempHp           int32                 `json:"temp_hp"`
	Ac               int32                 `json:"ac"`
	AcFormula        sql.NullString        `json:"ac_formula"`
	SpeedFt          int32                 `json:"speed_ft"`
	ProficiencyBonus int32                 `json:"proficiency_bonus"`
	EquippedMainHand sql.NullString        `json:"equipped_main_hand"`
	EquippedOffHand  sql.NullString        `json:"equipped_off_hand"`
	EquippedArmor    sql.NullString        `json:"equipped_armor"`
	SpellSlots       pqtype.NullRawMessage `json:"spell_slots"`
	PactMagicSlots   pqtype.NullRawMessage `json:"pact_magic_slots"`
	HitDiceRemaining json.RawMessage       `json:"hit_dice_remaining"`
	FeatureUses      pqtype.NullRawMessage `json:"feature_uses"`
	Features         pqtype.NullRawMessage `json:"features"`
	Proficiencies    pqtype.NullRawMessage `json:"proficiencies"`
	Gold             int32                 `json:"gold"`
	AttunementSlots  pqtype.NullRawMessage `json:"attunement_slots"`
	Languages        []string              `json:"languages"`
	Inventory        pqtype.NullRawMessage `json:"inventory"`
	CharacterData    pqtype.NullRawMessage `json:"character_data"`
	DdbUrl           sql.NullString        `json:"ddb_url"`
	Homebrew         sql.NullBool          `json:"homebrew"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
	CardMessageID    sql.NullString        `json:"card_message_id"`
}

type Class struct {
	ID                      string                `json:"id"`
	Name                    string                `json:"name"`
	HitDie                  string                `json:"hit_die"`
	PrimaryAbility          string                `json:"primary_ability"`
	SaveProficiencies       []string              `json:"save_proficiencies"`
	ArmorProficiencies      []string              `json:"armor_proficiencies"`
	WeaponProficiencies     []string              `json:"weapon_proficiencies"`
	SkillChoices            pqtype.NullRawMessage `json:"skill_choices"`
	Spellcasting            pqtype.NullRawMessage `json:"spellcasting"`
	FeaturesByLevel         json.RawMessage       `json:"features_by_level"`
	AttacksPerAction        json.RawMessage       `json:"attacks_per_action"`
	SubclassLevel           int32                 `json:"subclass_level"`
	Subclasses              json.RawMessage       `json:"subclasses"`
	MulticlassPrereqs       pqtype.NullRawMessage `json:"multiclass_prereqs"`
	MulticlassProficiencies pqtype.NullRawMessage `json:"multiclass_proficiencies"`
	CreatedAt               time.Time             `json:"created_at"`
	UpdatedAt               time.Time             `json:"updated_at"`
}

type Combatant struct {
	ID                         uuid.UUID             `json:"id"`
	EncounterID                uuid.UUID             `json:"encounter_id"`
	CharacterID                uuid.NullUUID         `json:"character_id"`
	CreatureRefID              sql.NullString        `json:"creature_ref_id"`
	ShortID                    string                `json:"short_id"`
	DisplayName                string                `json:"display_name"`
	InitiativeRoll             int32                 `json:"initiative_roll"`
	InitiativeOrder            int32                 `json:"initiative_order"`
	PositionCol                string                `json:"position_col"`
	PositionRow                int32                 `json:"position_row"`
	AltitudeFt                 int32                 `json:"altitude_ft"`
	HpMax                      int32                 `json:"hp_max"`
	HpCurrent                  int32                 `json:"hp_current"`
	TempHp                     int32                 `json:"temp_hp"`
	Ac                         int32                 `json:"ac"`
	Conditions                 json.RawMessage       `json:"conditions"`
	ExhaustionLevel            int32                 `json:"exhaustion_level"`
	DeathSaves                 pqtype.NullRawMessage `json:"death_saves"`
	IsVisible                  bool                  `json:"is_visible"`
	IsAlive                    bool                  `json:"is_alive"`
	IsNpc                      bool                  `json:"is_npc"`
	IsRaging                   bool                  `json:"is_raging"`
	RageRoundsRemaining        sql.NullInt32         `json:"rage_rounds_remaining"`
	RageAttackedThisRound      bool                  `json:"rage_attacked_this_round"`
	RageTookDamageThisRound    bool                  `json:"rage_took_damage_this_round"`
	IsWildShaped               bool                  `json:"is_wild_shaped"`
	WildShapeCreatureRef       sql.NullString        `json:"wild_shape_creature_ref"`
	WildShapeOriginal          pqtype.NullRawMessage `json:"wild_shape_original"`
	SummonerID                 uuid.NullUUID         `json:"summoner_id"`
	CreatedAt                  time.Time             `json:"created_at"`
	UpdatedAt                  time.Time             `json:"updated_at"`
	BardicInspirationDie       sql.NullString        `json:"bardic_inspiration_die"`
	BardicInspirationSource    sql.NullString        `json:"bardic_inspiration_source"`
	BardicInspirationGrantedAt sql.NullTime          `json:"bardic_inspiration_granted_at"`
	ConsecutiveAutoResolves    int32                 `json:"consecutive_auto_resolves"`
	IsAbsent                   bool                  `json:"is_absent"`
}

type ConditionsRef struct {
	ID                string          `json:"id"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	MechanicalEffects json.RawMessage `json:"mechanical_effects"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Creature struct {
	ID                    string                `json:"id"`
	CampaignID            uuid.NullUUID         `json:"campaign_id"`
	Name                  string                `json:"name"`
	Size                  string                `json:"size"`
	Type                  string                `json:"type"`
	Alignment             sql.NullString        `json:"alignment"`
	Ac                    int32                 `json:"ac"`
	AcType                sql.NullString        `json:"ac_type"`
	HpFormula             string                `json:"hp_formula"`
	HpAverage             int32                 `json:"hp_average"`
	Speed                 json.RawMessage       `json:"speed"`
	AbilityScores         json.RawMessage       `json:"ability_scores"`
	SavingThrows          pqtype.NullRawMessage `json:"saving_throws"`
	Skills                pqtype.NullRawMessage `json:"skills"`
	DamageResistances     []string              `json:"damage_resistances"`
	DamageImmunities      []string              `json:"damage_immunities"`
	DamageVulnerabilities []string              `json:"damage_vulnerabilities"`
	ConditionImmunities   []string              `json:"condition_immunities"`
	Senses                pqtype.NullRawMessage `json:"senses"`
	Languages             []string              `json:"languages"`
	Cr                    string                `json:"cr"`
	Attacks               json.RawMessage       `json:"attacks"`
	Abilities             pqtype.NullRawMessage `json:"abilities"`
	Homebrew              sql.NullBool          `json:"homebrew"`
	Source                sql.NullString        `json:"source"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
}

type Encounter struct {
	ID            uuid.UUID      `json:"id"`
	CampaignID    uuid.UUID      `json:"campaign_id"`
	MapID         uuid.NullUUID  `json:"map_id"`
	Name          string         `json:"name"`
	DisplayName   sql.NullString `json:"display_name"`
	TemplateID    uuid.NullUUID  `json:"template_id"`
	Status        string         `json:"status"`
	RoundNumber   int32          `json:"round_number"`
	CurrentTurnID uuid.NullUUID  `json:"current_turn_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type EncounterTemplate struct {
	ID          uuid.UUID       `json:"id"`
	CampaignID  uuid.UUID       `json:"campaign_id"`
	MapID       uuid.NullUUID   `json:"map_id"`
	Name        string          `json:"name"`
	DisplayName sql.NullString  `json:"display_name"`
	Creatures   json.RawMessage `json:"creatures"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type EncounterZone struct {
	ID                    uuid.UUID             `json:"id"`
	EncounterID           uuid.UUID             `json:"encounter_id"`
	SourceCombatantID     uuid.UUID             `json:"source_combatant_id"`
	SourceSpell           string                `json:"source_spell"`
	Shape                 string                `json:"shape"`
	OriginCol             string                `json:"origin_col"`
	OriginRow             int32                 `json:"origin_row"`
	Dimensions            json.RawMessage       `json:"dimensions"`
	AnchorMode            string                `json:"anchor_mode"`
	AnchorCombatantID     uuid.NullUUID         `json:"anchor_combatant_id"`
	ZoneType              string                `json:"zone_type"`
	OverlayColor          string                `json:"overlay_color"`
	MarkerIcon            sql.NullString        `json:"marker_icon"`
	RequiresConcentration bool                  `json:"requires_concentration"`
	ExpiresAtRound        sql.NullInt32         `json:"expires_at_round"`
	ZoneTriggers          pqtype.NullRawMessage `json:"zone_triggers"`
	TriggeredThisRound    pqtype.NullRawMessage `json:"triggered_this_round"`
	CreatedAt             time.Time             `json:"created_at"`
}

type Feat struct {
	ID               string                `json:"id"`
	Name             string                `json:"name"`
	Description      string                `json:"description"`
	Prerequisites    pqtype.NullRawMessage `json:"prerequisites"`
	AsiBonus         pqtype.NullRawMessage `json:"asi_bonus"`
	MechanicalEffect pqtype.NullRawMessage `json:"mechanical_effect"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type LootPool struct {
	ID          uuid.UUID `json:"id"`
	EncounterID uuid.UUID `json:"encounter_id"`
	CampaignID  uuid.UUID `json:"campaign_id"`
	GoldTotal   int32     `json:"gold_total"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type LootPoolItem struct {
	ID                 uuid.UUID      `json:"id"`
	LootPoolID         uuid.UUID      `json:"loot_pool_id"`
	ItemID             sql.NullString `json:"item_id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	Quantity           int32          `json:"quantity"`
	Type               string         `json:"type"`
	ClaimedBy          uuid.NullUUID  `json:"claimed_by"`
	ClaimedAt          sql.NullTime   `json:"claimed_at"`
	IsMagic            bool           `json:"is_magic"`
	MagicBonus         int32          `json:"magic_bonus"`
	MagicProperties    string         `json:"magic_properties"`
	RequiresAttunement bool           `json:"requires_attunement"`
	Rarity             string         `json:"rarity"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type MagicItem struct {
	ID                    string                `json:"id"`
	CampaignID            uuid.NullUUID         `json:"campaign_id"`
	Name                  string                `json:"name"`
	BaseItemType          sql.NullString        `json:"base_item_type"`
	BaseItemID            sql.NullString        `json:"base_item_id"`
	Rarity                string                `json:"rarity"`
	RequiresAttunement    sql.NullBool          `json:"requires_attunement"`
	AttunementRestriction sql.NullString        `json:"attunement_restriction"`
	MagicBonus            sql.NullInt32         `json:"magic_bonus"`
	PassiveEffects        pqtype.NullRawMessage `json:"passive_effects"`
	ActiveAbilities       pqtype.NullRawMessage `json:"active_abilities"`
	Charges               pqtype.NullRawMessage `json:"charges"`
	Description           string                `json:"description"`
	Homebrew              sql.NullBool          `json:"homebrew"`
	Source                sql.NullString        `json:"source"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
}

type Map struct {
	ID                uuid.UUID             `json:"id"`
	CampaignID        uuid.UUID             `json:"campaign_id"`
	Name              string                `json:"name"`
	WidthSquares      int32                 `json:"width_squares"`
	HeightSquares     int32                 `json:"height_squares"`
	TiledJson         json.RawMessage       `json:"tiled_json"`
	BackgroundImageID uuid.NullUUID         `json:"background_image_id"`
	TilesetRefs       pqtype.NullRawMessage `json:"tileset_refs"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type PendingAction struct {
	ID               uuid.UUID `json:"id"`
	EncounterID      uuid.UUID `json:"encounter_id"`
	CombatantID      uuid.UUID `json:"combatant_id"`
	ActionText       string    `json:"action_text"`
	DmQueueMessageID string    `json:"dm_queue_message_id"`
	DmQueueChannelID string    `json:"dm_queue_channel_id"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type PendingSafe struct {
	ID          uuid.UUID     `json:"id"`
	EncounterID uuid.UUID     `json:"encounter_id"`
	CombatantID uuid.UUID     `json:"combatant_id"`
	Ability     string        `json:"ability"`
	Dc          int32         `json:"dc"`
	Source      string        `json:"source"`
	Status      string        `json:"status"`
	RollResult  sql.NullInt32 `json:"roll_result"`
	Success     sql.NullBool  `json:"success"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type PlayerCharacter struct {
	ID            uuid.UUID      `json:"id"`
	CampaignID    uuid.UUID      `json:"campaign_id"`
	CharacterID   uuid.UUID      `json:"character_id"`
	DiscordUserID string         `json:"discord_user_id"`
	Status        string         `json:"status"`
	DmFeedback    sql.NullString `json:"dm_feedback"`
	CreatedVia    string         `json:"created_via"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Race struct {
	ID             string                `json:"id"`
	Name           string                `json:"name"`
	SpeedFt        int32                 `json:"speed_ft"`
	Size           string                `json:"size"`
	AbilityBonuses json.RawMessage       `json:"ability_bonuses"`
	DarkvisionFt   int32                 `json:"darkvision_ft"`
	Traits         json.RawMessage       `json:"traits"`
	Languages      []string              `json:"languages"`
	Subraces       pqtype.NullRawMessage `json:"subraces"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type ReactionDeclaration struct {
	ID                     uuid.UUID      `json:"id"`
	EncounterID            uuid.UUID      `json:"encounter_id"`
	CombatantID            uuid.UUID      `json:"combatant_id"`
	Description            string         `json:"description"`
	Status                 string         `json:"status"`
	CreatedAt              time.Time      `json:"created_at"`
	UsedAt                 sql.NullTime   `json:"used_at"`
	UsedOnRound            sql.NullInt32  `json:"used_on_round"`
	IsReadiedAction        bool           `json:"is_readied_action"`
	SpellName              sql.NullString `json:"spell_name"`
	SpellSlotLevel         sql.NullInt32  `json:"spell_slot_level"`
	CounterspellEnemySpell sql.NullString `json:"counterspell_enemy_spell"`
	CounterspellEnemyLevel sql.NullInt32  `json:"counterspell_enemy_level"`
	CounterspellSlotUsed   sql.NullInt32  `json:"counterspell_slot_used"`
	CounterspellStatus     sql.NullString `json:"counterspell_status"`
	CounterspellDc         sql.NullInt32  `json:"counterspell_dc"`
}

type Session struct {
	ID             uuid.UUID    `json:"id"`
	DiscordUserID  string       `json:"discord_user_id"`
	AccessToken    string       `json:"access_token"`
	RefreshToken   string       `json:"refresh_token"`
	TokenExpiresAt sql.NullTime `json:"token_expires_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	ExpiresAt      time.Time    `json:"expires_at"`
}

type Spell struct {
	ID                  string                `json:"id"`
	Name                string                `json:"name"`
	Level               int32                 `json:"level"`
	School              string                `json:"school"`
	CastingTime         string                `json:"casting_time"`
	RangeFt             sql.NullInt32         `json:"range_ft"`
	RangeType           string                `json:"range_type"`
	Components          []string              `json:"components"`
	MaterialDescription sql.NullString        `json:"material_description"`
	MaterialCostGp      sql.NullFloat64       `json:"material_cost_gp"`
	MaterialConsumed    sql.NullBool          `json:"material_consumed"`
	Duration            string                `json:"duration"`
	Concentration       sql.NullBool          `json:"concentration"`
	Ritual              sql.NullBool          `json:"ritual"`
	Description         string                `json:"description"`
	HigherLevels        sql.NullString        `json:"higher_levels"`
	Damage              pqtype.NullRawMessage `json:"damage"`
	Healing             pqtype.NullRawMessage `json:"healing"`
	SaveAbility         sql.NullString        `json:"save_ability"`
	SaveEffect          sql.NullString        `json:"save_effect"`
	AttackType          sql.NullString        `json:"attack_type"`
	AreaOfEffect        pqtype.NullRawMessage `json:"area_of_effect"`
	ConditionsApplied   []string              `json:"conditions_applied"`
	Teleport            pqtype.NullRawMessage `json:"teleport"`
	ResolutionMode      string                `json:"resolution_mode"`
	Classes             []string              `json:"classes"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
}

type Turn struct {
	ID                   uuid.UUID    `json:"id"`
	EncounterID          uuid.UUID    `json:"encounter_id"`
	CombatantID          uuid.UUID    `json:"combatant_id"`
	RoundNumber          int32        `json:"round_number"`
	Status               string       `json:"status"`
	MovementRemainingFt  int32        `json:"movement_remaining_ft"`
	ActionUsed           bool         `json:"action_used"`
	BonusActionUsed      bool         `json:"bonus_action_used"`
	BonusActionSpellCast bool         `json:"bonus_action_spell_cast"`
	ActionSpellCast      bool         `json:"action_spell_cast"`
	ReactionUsed         bool         `json:"reaction_used"`
	FreeInteractUsed     bool         `json:"free_interact_used"`
	AttacksRemaining     int32        `json:"attacks_remaining"`
	HasDisengaged        bool         `json:"has_disengaged"`
	ActionSurged         bool         `json:"action_surged"`
	StartedAt            sql.NullTime `json:"started_at"`
	TimeoutAt            sql.NullTime `json:"timeout_at"`
	CompletedAt          sql.NullTime `json:"completed_at"`
	CreatedAt            time.Time    `json:"created_at"`
	HasStoodThisTurn     bool         `json:"has_stood_this_turn"`
	NudgeSentAt          sql.NullTime `json:"nudge_sent_at"`
	WarningSentAt        sql.NullTime `json:"warning_sent_at"`
	DmDecisionSentAt     sql.NullTime `json:"dm_decision_sent_at"`
	DmDecisionDeadline   sql.NullTime `json:"dm_decision_deadline"`
	WaitExtended         bool         `json:"wait_extended"`
	AutoResolved         bool         `json:"auto_resolved"`
}

type Weapon struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Damage          string          `json:"damage"`
	DamageType      string          `json:"damage_type"`
	WeightLb        sql.NullFloat64 `json:"weight_lb"`
	Properties      []string        `json:"properties"`
	RangeNormalFt   sql.NullInt32   `json:"range_normal_ft"`
	RangeLongFt     sql.NullInt32   `json:"range_long_ft"`
	VersatileDamage sql.NullString  `json:"versatile_damage"`
	WeaponType      string          `json:"weapon_type"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
