// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package refdata

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Armor struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	AcBase        int32           `json:"ac_base"`
	AcDexBonus    sql.NullBool    `json:"ac_dex_bonus"`
	AcDexMax      sql.NullInt32   `json:"ac_dex_max"`
	StrengthReq   sql.NullInt32   `json:"strength_req"`
	StealthDisadv sql.NullBool    `json:"stealth_disadv"`
	ArmorType     string          `json:"armor_type"`
	WeightLb      sql.NullFloat64 `json:"weight_lb"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Campaign struct {
	ID        uuid.UUID             `json:"id"`
	GuildID   string                `json:"guild_id"`
	DmUserID  string                `json:"dm_user_id"`
	Name      string                `json:"name"`
	Settings  pqtype.NullRawMessage `json:"settings"`
	Status    string                `json:"status"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}

type ConditionsRef struct {
	ID                string          `json:"id"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	MechanicalEffects json.RawMessage `json:"mechanical_effects"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Session struct {
	ID             uuid.UUID    `json:"id"`
	DiscordUserID  string       `json:"discord_user_id"`
	AccessToken    string       `json:"access_token"`
	RefreshToken   string       `json:"refresh_token"`
	TokenExpiresAt sql.NullTime `json:"token_expires_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	ExpiresAt      time.Time    `json:"expires_at"`
}

type Weapon struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Damage          string          `json:"damage"`
	DamageType      string          `json:"damage_type"`
	WeightLb        sql.NullFloat64 `json:"weight_lb"`
	Properties      []string        `json:"properties"`
	RangeNormalFt   sql.NullInt32   `json:"range_normal_ft"`
	RangeLongFt     sql.NullInt32   `json:"range_long_ft"`
	VersatileDamage sql.NullString  `json:"versatile_damage"`
	WeaponType      string          `json:"weapon_type"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
