// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package refdata

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Armor struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	AcBase        int32           `json:"ac_base"`
	AcDexBonus    sql.NullBool    `json:"ac_dex_bonus"`
	AcDexMax      sql.NullInt32   `json:"ac_dex_max"`
	StrengthReq   sql.NullInt32   `json:"strength_req"`
	StealthDisadv sql.NullBool    `json:"stealth_disadv"`
	ArmorType     string          `json:"armor_type"`
	WeightLb      sql.NullFloat64 `json:"weight_lb"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Campaign struct {
	ID        uuid.UUID             `json:"id"`
	GuildID   string                `json:"guild_id"`
	DmUserID  string                `json:"dm_user_id"`
	Name      string                `json:"name"`
	Settings  pqtype.NullRawMessage `json:"settings"`
	Status    string                `json:"status"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}

type Character struct {
	ID               uuid.UUID             `json:"id"`
	CampaignID       uuid.UUID             `json:"campaign_id"`
	Name             string                `json:"name"`
	Race             string                `json:"race"`
	Classes          json.RawMessage       `json:"classes"`
	Level            int32                 `json:"level"`
	AbilityScores    json.RawMessage       `json:"ability_scores"`
	HpMax            int32                 `json:"hp_max"`
	HpCurrent        int32                 `json:"hp_current"`
	TempHp           int32                 `json:"temp_hp"`
	Ac               int32                 `json:"ac"`
	AcFormula        sql.NullString        `json:"ac_formula"`
	SpeedFt          int32                 `json:"speed_ft"`
	ProficiencyBonus int32                 `json:"proficiency_bonus"`
	EquippedMainHand sql.NullString        `json:"equipped_main_hand"`
	EquippedOffHand  sql.NullString        `json:"equipped_off_hand"`
	EquippedArmor    sql.NullString        `json:"equipped_armor"`
	SpellSlots       pqtype.NullRawMessage `json:"spell_slots"`
	PactMagicSlots   pqtype.NullRawMessage `json:"pact_magic_slots"`
	HitDiceRemaining json.RawMessage       `json:"hit_dice_remaining"`
	FeatureUses      pqtype.NullRawMessage `json:"feature_uses"`
	Features         pqtype.NullRawMessage `json:"features"`
	Proficiencies    pqtype.NullRawMessage `json:"proficiencies"`
	Gold             int32                 `json:"gold"`
	AttunementSlots  pqtype.NullRawMessage `json:"attunement_slots"`
	Languages        []string              `json:"languages"`
	Inventory        pqtype.NullRawMessage `json:"inventory"`
	CharacterData    pqtype.NullRawMessage `json:"character_data"`
	DdbUrl           sql.NullString        `json:"ddb_url"`
	Homebrew         sql.NullBool          `json:"homebrew"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type Class struct {
	ID                      string                `json:"id"`
	Name                    string                `json:"name"`
	HitDie                  string                `json:"hit_die"`
	PrimaryAbility          string                `json:"primary_ability"`
	SaveProficiencies       []string              `json:"save_proficiencies"`
	ArmorProficiencies      []string              `json:"armor_proficiencies"`
	WeaponProficiencies     []string              `json:"weapon_proficiencies"`
	SkillChoices            pqtype.NullRawMessage `json:"skill_choices"`
	Spellcasting            pqtype.NullRawMessage `json:"spellcasting"`
	FeaturesByLevel         json.RawMessage       `json:"features_by_level"`
	AttacksPerAction        json.RawMessage       `json:"attacks_per_action"`
	SubclassLevel           int32                 `json:"subclass_level"`
	Subclasses              json.RawMessage       `json:"subclasses"`
	MulticlassPrereqs       pqtype.NullRawMessage `json:"multiclass_prereqs"`
	MulticlassProficiencies pqtype.NullRawMessage `json:"multiclass_proficiencies"`
	CreatedAt               time.Time             `json:"created_at"`
	UpdatedAt               time.Time             `json:"updated_at"`
}

type ConditionsRef struct {
	ID                string          `json:"id"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	MechanicalEffects json.RawMessage `json:"mechanical_effects"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Creature struct {
	ID                    string                `json:"id"`
	CampaignID            uuid.NullUUID         `json:"campaign_id"`
	Name                  string                `json:"name"`
	Size                  string                `json:"size"`
	Type                  string                `json:"type"`
	Alignment             sql.NullString        `json:"alignment"`
	Ac                    int32                 `json:"ac"`
	AcType                sql.NullString        `json:"ac_type"`
	HpFormula             string                `json:"hp_formula"`
	HpAverage             int32                 `json:"hp_average"`
	Speed                 json.RawMessage       `json:"speed"`
	AbilityScores         json.RawMessage       `json:"ability_scores"`
	SavingThrows          pqtype.NullRawMessage `json:"saving_throws"`
	Skills                pqtype.NullRawMessage `json:"skills"`
	DamageResistances     []string              `json:"damage_resistances"`
	DamageImmunities      []string              `json:"damage_immunities"`
	DamageVulnerabilities []string              `json:"damage_vulnerabilities"`
	ConditionImmunities   []string              `json:"condition_immunities"`
	Senses                pqtype.NullRawMessage `json:"senses"`
	Languages             []string              `json:"languages"`
	Cr                    string                `json:"cr"`
	Attacks               json.RawMessage       `json:"attacks"`
	Abilities             pqtype.NullRawMessage `json:"abilities"`
	Homebrew              sql.NullBool          `json:"homebrew"`
	Source                sql.NullString        `json:"source"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
}

type Feat struct {
	ID               string                `json:"id"`
	Name             string                `json:"name"`
	Description      string                `json:"description"`
	Prerequisites    pqtype.NullRawMessage `json:"prerequisites"`
	AsiBonus         pqtype.NullRawMessage `json:"asi_bonus"`
	MechanicalEffect pqtype.NullRawMessage `json:"mechanical_effect"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type MagicItem struct {
	ID                    string                `json:"id"`
	CampaignID            uuid.NullUUID         `json:"campaign_id"`
	Name                  string                `json:"name"`
	BaseItemType          sql.NullString        `json:"base_item_type"`
	BaseItemID            sql.NullString        `json:"base_item_id"`
	Rarity                string                `json:"rarity"`
	RequiresAttunement    sql.NullBool          `json:"requires_attunement"`
	AttunementRestriction sql.NullString        `json:"attunement_restriction"`
	MagicBonus            sql.NullInt32         `json:"magic_bonus"`
	PassiveEffects        pqtype.NullRawMessage `json:"passive_effects"`
	ActiveAbilities       pqtype.NullRawMessage `json:"active_abilities"`
	Charges               pqtype.NullRawMessage `json:"charges"`
	Description           string                `json:"description"`
	Homebrew              sql.NullBool          `json:"homebrew"`
	Source                sql.NullString        `json:"source"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
}

type PlayerCharacter struct {
	ID            uuid.UUID      `json:"id"`
	CampaignID    uuid.UUID      `json:"campaign_id"`
	CharacterID   uuid.UUID      `json:"character_id"`
	DiscordUserID string         `json:"discord_user_id"`
	Status        string         `json:"status"`
	DmFeedback    sql.NullString `json:"dm_feedback"`
	CreatedVia    string         `json:"created_via"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Race struct {
	ID             string                `json:"id"`
	Name           string                `json:"name"`
	SpeedFt        int32                 `json:"speed_ft"`
	Size           string                `json:"size"`
	AbilityBonuses json.RawMessage       `json:"ability_bonuses"`
	DarkvisionFt   int32                 `json:"darkvision_ft"`
	Traits         json.RawMessage       `json:"traits"`
	Languages      []string              `json:"languages"`
	Subraces       pqtype.NullRawMessage `json:"subraces"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type Session struct {
	ID             uuid.UUID    `json:"id"`
	DiscordUserID  string       `json:"discord_user_id"`
	AccessToken    string       `json:"access_token"`
	RefreshToken   string       `json:"refresh_token"`
	TokenExpiresAt sql.NullTime `json:"token_expires_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	ExpiresAt      time.Time    `json:"expires_at"`
}

type Spell struct {
	ID                  string                `json:"id"`
	Name                string                `json:"name"`
	Level               int32                 `json:"level"`
	School              string                `json:"school"`
	CastingTime         string                `json:"casting_time"`
	RangeFt             sql.NullInt32         `json:"range_ft"`
	RangeType           string                `json:"range_type"`
	Components          []string              `json:"components"`
	MaterialDescription sql.NullString        `json:"material_description"`
	MaterialCostGp      sql.NullFloat64       `json:"material_cost_gp"`
	MaterialConsumed    sql.NullBool          `json:"material_consumed"`
	Duration            string                `json:"duration"`
	Concentration       sql.NullBool          `json:"concentration"`
	Ritual              sql.NullBool          `json:"ritual"`
	Description         string                `json:"description"`
	HigherLevels        sql.NullString        `json:"higher_levels"`
	Damage              pqtype.NullRawMessage `json:"damage"`
	Healing             pqtype.NullRawMessage `json:"healing"`
	SaveAbility         sql.NullString        `json:"save_ability"`
	SaveEffect          sql.NullString        `json:"save_effect"`
	AttackType          sql.NullString        `json:"attack_type"`
	AreaOfEffect        pqtype.NullRawMessage `json:"area_of_effect"`
	ConditionsApplied   []string              `json:"conditions_applied"`
	Teleport            pqtype.NullRawMessage `json:"teleport"`
	ResolutionMode      string                `json:"resolution_mode"`
	Classes             []string              `json:"classes"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
}

type Weapon struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Damage          string          `json:"damage"`
	DamageType      string          `json:"damage_type"`
	WeightLb        sql.NullFloat64 `json:"weight_lb"`
	Properties      []string        `json:"properties"`
	RangeNormalFt   sql.NullInt32   `json:"range_normal_ft"`
	RangeLongFt     sql.NullInt32   `json:"range_long_ft"`
	VersatileDamage sql.NullString  `json:"versatile_damage"`
	WeaponType      string          `json:"weapon_type"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
