// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: narration_posts.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const insertNarrationPost = `-- name: InsertNarrationPost :one
INSERT INTO narration_posts (
    campaign_id,
    author_user_id,
    body,
    attachment_asset_ids,
    discord_message_ids
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, author_user_id, body, attachment_asset_ids, discord_message_ids, posted_at
`

type InsertNarrationPostParams struct {
	CampaignID         uuid.UUID   `json:"campaign_id"`
	AuthorUserID       string      `json:"author_user_id"`
	Body               string      `json:"body"`
	AttachmentAssetIds []uuid.UUID `json:"attachment_asset_ids"`
	DiscordMessageIds  []string    `json:"discord_message_ids"`
}

func (q *Queries) InsertNarrationPost(ctx context.Context, arg InsertNarrationPostParams) (NarrationPost, error) {
	row := q.db.QueryRowContext(ctx, insertNarrationPost,
		arg.CampaignID,
		arg.AuthorUserID,
		arg.Body,
		pq.Array(arg.AttachmentAssetIds),
		pq.Array(arg.DiscordMessageIds),
	)
	var i NarrationPost
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AuthorUserID,
		&i.Body,
		pq.Array(&i.AttachmentAssetIds),
		pq.Array(&i.DiscordMessageIds),
		&i.PostedAt,
	)
	return i, err
}

const listNarrationPostsByCampaign = `-- name: ListNarrationPostsByCampaign :many
SELECT id, campaign_id, author_user_id, body, attachment_asset_ids, discord_message_ids, posted_at
FROM narration_posts
WHERE campaign_id = $1
ORDER BY posted_at DESC
LIMIT $2 OFFSET $3
`

type ListNarrationPostsByCampaignParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListNarrationPostsByCampaign(ctx context.Context, arg ListNarrationPostsByCampaignParams) ([]NarrationPost, error) {
	rows, err := q.db.QueryContext(ctx, listNarrationPostsByCampaign, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NarrationPost{}
	for rows.Next() {
		var i NarrationPost
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AuthorUserID,
			&i.Body,
			pq.Array(&i.AttachmentAssetIds),
			pq.Array(&i.DiscordMessageIds),
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
