// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: narration_templates.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
)

const deleteNarrationTemplate = `-- name: DeleteNarrationTemplate :exec
DELETE FROM narration_templates
WHERE id = $1
`

func (q *Queries) DeleteNarrationTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNarrationTemplate, id)
	return err
}

const getNarrationTemplate = `-- name: GetNarrationTemplate :one
SELECT id, campaign_id, name, category, body, created_at, updated_at
FROM narration_templates
WHERE id = $1
`

func (q *Queries) GetNarrationTemplate(ctx context.Context, id uuid.UUID) (NarrationTemplate, error) {
	row := q.db.QueryRowContext(ctx, getNarrationTemplate, id)
	var i NarrationTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Category,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNarrationTemplate = `-- name: InsertNarrationTemplate :one
INSERT INTO narration_templates (campaign_id, name, category, body)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, name, category, body, created_at, updated_at
`

type InsertNarrationTemplateParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Name       string    `json:"name"`
	Category   string    `json:"category"`
	Body       string    `json:"body"`
}

func (q *Queries) InsertNarrationTemplate(ctx context.Context, arg InsertNarrationTemplateParams) (NarrationTemplate, error) {
	row := q.db.QueryRowContext(ctx, insertNarrationTemplate,
		arg.CampaignID,
		arg.Name,
		arg.Category,
		arg.Body,
	)
	var i NarrationTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Category,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNarrationTemplatesByCampaign = `-- name: ListNarrationTemplatesByCampaign :many
SELECT id, campaign_id, name, category, body, created_at, updated_at
FROM narration_templates
WHERE campaign_id = $1
  AND ($2::text = '' OR category = $2::text)
  AND ($3::text = '' OR name ILIKE '%' || $3::text || '%' OR body ILIKE '%' || $3::text || '%')
ORDER BY category ASC, name ASC
`

type ListNarrationTemplatesByCampaignParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Category   string    `json:"category"`
	Search     string    `json:"search"`
}

func (q *Queries) ListNarrationTemplatesByCampaign(ctx context.Context, arg ListNarrationTemplatesByCampaignParams) ([]NarrationTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listNarrationTemplatesByCampaign, arg.CampaignID, arg.Category, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NarrationTemplate{}
	for rows.Next() {
		var i NarrationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Category,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNarrationTemplate = `-- name: UpdateNarrationTemplate :one
UPDATE narration_templates
SET name       = $2,
    category   = $3,
    body       = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, category, body, created_at, updated_at
`

type UpdateNarrationTemplateParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Category string    `json:"category"`
	Body     string    `json:"body"`
}

func (q *Queries) UpdateNarrationTemplate(ctx context.Context, arg UpdateNarrationTemplateParams) (NarrationTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateNarrationTemplate,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Body,
	)
	var i NarrationTemplate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Category,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
