// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: open5e_custom_sources.sql

package refdata

import (
	"context"
)

const deleteOpen5eCustomSource = `-- name: DeleteOpen5eCustomSource :execrows
DELETE FROM open5e_custom_sources WHERE slug = $1
`

func (q *Queries) DeleteOpen5eCustomSource(ctx context.Context, slug string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOpen5eCustomSource, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listOpen5eCustomSources = `-- name: ListOpen5eCustomSources :many
SELECT slug, title, publisher, description, created_at FROM open5e_custom_sources ORDER BY title
`

func (q *Queries) ListOpen5eCustomSources(ctx context.Context) ([]Open5eCustomSource, error) {
	rows, err := q.db.QueryContext(ctx, listOpen5eCustomSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Open5eCustomSource{}
	for rows.Next() {
		var i Open5eCustomSource
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Publisher,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOpen5eCustomSource = `-- name: UpsertOpen5eCustomSource :one
INSERT INTO open5e_custom_sources (slug, title, publisher, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
  SET title = EXCLUDED.title,
      publisher = EXCLUDED.publisher,
      description = EXCLUDED.description
RETURNING slug, title, publisher, description, created_at
`

type UpsertOpen5eCustomSourceParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Publisher   string `json:"publisher"`
	Description string `json:"description"`
}

func (q *Queries) UpsertOpen5eCustomSource(ctx context.Context, arg UpsertOpen5eCustomSourceParams) (Open5eCustomSource, error) {
	row := q.db.QueryRowContext(ctx, upsertOpen5eCustomSource,
		arg.Slug,
		arg.Title,
		arg.Publisher,
		arg.Description,
	)
	var i Open5eCustomSource
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Publisher,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
