// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_initiatives.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearAndReturnPendingInitiatives = `-- name: ClearAndReturnPendingInitiatives :many
DELETE FROM pending_initiatives
WHERE campaign_id = $1
RETURNING character_id, roll, dm_queue_item_id
`

type ClearAndReturnPendingInitiativesRow struct {
	CharacterID   uuid.UUID      `json:"character_id"`
	Roll          int32          `json:"roll"`
	DmQueueItemID sql.NullString `json:"dm_queue_item_id"`
}

// APP-5: StartCombat consumes every staged roll for the campaign and clears the
// rows in one statement — read-and-delete atomically, so nothing leaks into the
// next combat and the start path pays a single round trip.
func (q *Queries) ClearAndReturnPendingInitiatives(ctx context.Context, campaignID uuid.UUID) ([]ClearAndReturnPendingInitiativesRow, error) {
	rows, err := q.db.QueryContext(ctx, clearAndReturnPendingInitiatives, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearAndReturnPendingInitiativesRow{}
	for rows.Next() {
		var i ClearAndReturnPendingInitiativesRow
		if err := rows.Scan(&i.CharacterID, &i.Roll, &i.DmQueueItemID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePendingInitiative = `-- name: DeletePendingInitiative :exec
DELETE FROM pending_initiatives
WHERE campaign_id = $1 AND character_id = $2
`

type DeletePendingInitiativeParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeletePendingInitiative(ctx context.Context, arg DeletePendingInitiativeParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingInitiative, arg.CampaignID, arg.CharacterID)
	return err
}

const getPendingInitiative = `-- name: GetPendingInitiative :one
SELECT id, campaign_id, character_id, roll, created_at, updated_at, dm_queue_item_id FROM pending_initiatives
WHERE campaign_id = $1 AND character_id = $2
`

type GetPendingInitiativeParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) GetPendingInitiative(ctx context.Context, arg GetPendingInitiativeParams) (PendingInitiative, error) {
	row := q.db.QueryRowContext(ctx, getPendingInitiative, arg.CampaignID, arg.CharacterID)
	var i PendingInitiative
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.Roll,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DmQueueItemID,
	)
	return i, err
}

const upsertPendingInitiative = `-- name: UpsertPendingInitiative :one
INSERT INTO pending_initiatives (campaign_id, character_id, roll, dm_queue_item_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, character_id)
DO UPDATE SET roll = EXCLUDED.roll, dm_queue_item_id = EXCLUDED.dm_queue_item_id, updated_at = now()
RETURNING id, campaign_id, character_id, roll, created_at, updated_at, dm_queue_item_id
`

type UpsertPendingInitiativeParams struct {
	CampaignID    uuid.UUID      `json:"campaign_id"`
	CharacterID   uuid.UUID      `json:"character_id"`
	Roll          int32          `json:"roll"`
	DmQueueItemID sql.NullString `json:"dm_queue_item_id"`
}

// APP-5: stage (or edit) one player's own initiative before combat starts.
// Re-submitting the same (campaign, character) overwrites the prior roll.
// dm_queue_item_id carries the id of the #dm-queue / DM-Console item this stage
// posted, so a re-roll / clear / StartCombat can cancel it (nullable: NULL when
// no notifier is wired).
func (q *Queries) UpsertPendingInitiative(ctx context.Context, arg UpsertPendingInitiativeParams) (PendingInitiative, error) {
	row := q.db.QueryRowContext(ctx, upsertPendingInitiative,
		arg.CampaignID,
		arg.CharacterID,
		arg.Roll,
		arg.DmQueueItemID,
	)
	var i PendingInitiative
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.Roll,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DmQueueItemID,
	)
	return i, err
}
