// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_actions.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
)

const cancelAllPendingActionsByCombatant = `-- name: CancelAllPendingActionsByCombatant :exec
UPDATE pending_actions
SET status = 'cancelled', updated_at = now()
WHERE combatant_id = $1 AND encounter_id = $2 AND status = 'pending'
`

type CancelAllPendingActionsByCombatantParams struct {
	CombatantID uuid.UUID `json:"combatant_id"`
	EncounterID uuid.UUID `json:"encounter_id"`
}

func (q *Queries) CancelAllPendingActionsByCombatant(ctx context.Context, arg CancelAllPendingActionsByCombatantParams) error {
	_, err := q.db.ExecContext(ctx, cancelAllPendingActionsByCombatant, arg.CombatantID, arg.EncounterID)
	return err
}

const createPendingAction = `-- name: CreatePendingAction :one
INSERT INTO pending_actions (encounter_id, combatant_id, action_text, dm_queue_message_id, dm_queue_channel_id, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, encounter_id, combatant_id, action_text, dm_queue_message_id, dm_queue_channel_id, status, created_at, updated_at
`

type CreatePendingActionParams struct {
	EncounterID      uuid.UUID `json:"encounter_id"`
	CombatantID      uuid.UUID `json:"combatant_id"`
	ActionText       string    `json:"action_text"`
	DmQueueMessageID string    `json:"dm_queue_message_id"`
	DmQueueChannelID string    `json:"dm_queue_channel_id"`
}

func (q *Queries) CreatePendingAction(ctx context.Context, arg CreatePendingActionParams) (PendingAction, error) {
	row := q.db.QueryRowContext(ctx, createPendingAction,
		arg.EncounterID,
		arg.CombatantID,
		arg.ActionText,
		arg.DmQueueMessageID,
		arg.DmQueueChannelID,
	)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.ActionText,
		&i.DmQueueMessageID,
		&i.DmQueueChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingAction = `-- name: GetPendingAction :one
SELECT id, encounter_id, combatant_id, action_text, dm_queue_message_id, dm_queue_channel_id, status, created_at, updated_at FROM pending_actions WHERE id = $1
`

func (q *Queries) GetPendingAction(ctx context.Context, id uuid.UUID) (PendingAction, error) {
	row := q.db.QueryRowContext(ctx, getPendingAction, id)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.ActionText,
		&i.DmQueueMessageID,
		&i.DmQueueChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingActionByCombatant = `-- name: GetPendingActionByCombatant :one
SELECT id, encounter_id, combatant_id, action_text, dm_queue_message_id, dm_queue_channel_id, status, created_at, updated_at FROM pending_actions
WHERE combatant_id = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingActionByCombatant(ctx context.Context, combatantID uuid.UUID) (PendingAction, error) {
	row := q.db.QueryRowContext(ctx, getPendingActionByCombatant, combatantID)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.ActionText,
		&i.DmQueueMessageID,
		&i.DmQueueChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingActionDMQueueMessage = `-- name: UpdatePendingActionDMQueueMessage :one
UPDATE pending_actions
SET dm_queue_message_id = $2, dm_queue_channel_id = $3, updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, combatant_id, action_text, dm_queue_message_id, dm_queue_channel_id, status, created_at, updated_at
`

type UpdatePendingActionDMQueueMessageParams struct {
	ID               uuid.UUID `json:"id"`
	DmQueueMessageID string    `json:"dm_queue_message_id"`
	DmQueueChannelID string    `json:"dm_queue_channel_id"`
}

func (q *Queries) UpdatePendingActionDMQueueMessage(ctx context.Context, arg UpdatePendingActionDMQueueMessageParams) (PendingAction, error) {
	row := q.db.QueryRowContext(ctx, updatePendingActionDMQueueMessage, arg.ID, arg.DmQueueMessageID, arg.DmQueueChannelID)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.ActionText,
		&i.DmQueueMessageID,
		&i.DmQueueChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingActionStatus = `-- name: UpdatePendingActionStatus :one
UPDATE pending_actions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, combatant_id, action_text, dm_queue_message_id, dm_queue_channel_id, status, created_at, updated_at
`

type UpdatePendingActionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePendingActionStatus(ctx context.Context, arg UpdatePendingActionStatusParams) (PendingAction, error) {
	row := q.db.QueryRowContext(ctx, updatePendingActionStatus, arg.ID, arg.Status)
	var i PendingAction
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.ActionText,
		&i.DmQueueMessageID,
		&i.DmQueueChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
