// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_asi.sql

package refdata

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deletePendingASI = `-- name: DeletePendingASI :exec
DELETE FROM pending_asi WHERE character_id = $1
`

func (q *Queries) DeletePendingASI(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePendingASI, characterID)
	return err
}

const getPendingASI = `-- name: GetPendingASI :one
SELECT character_id, snapshot_json, created_at, updated_at
FROM pending_asi
WHERE character_id = $1
`

func (q *Queries) GetPendingASI(ctx context.Context, characterID uuid.UUID) (PendingAsi, error) {
	row := q.db.QueryRowContext(ctx, getPendingASI, characterID)
	var i PendingAsi
	err := row.Scan(
		&i.CharacterID,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingASI = `-- name: ListPendingASI :many
SELECT character_id, snapshot_json, created_at, updated_at
FROM pending_asi
ORDER BY created_at ASC
`

func (q *Queries) ListPendingASI(ctx context.Context) ([]PendingAsi, error) {
	rows, err := q.db.QueryContext(ctx, listPendingASI)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingAsi{}
	for rows.Next() {
		var i PendingAsi
		if err := rows.Scan(
			&i.CharacterID,
			&i.SnapshotJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingASIByCampaign = `-- name: ListPendingASIByCampaign :many
SELECT pa.character_id, c.name AS character_name, pa.created_at
FROM pending_asi pa
JOIN player_characters pc ON pc.character_id = pa.character_id
JOIN characters c ON c.id = pa.character_id
WHERE pc.campaign_id = $1
ORDER BY pa.created_at ASC
`

type ListPendingASIByCampaignRow struct {
	CharacterID   uuid.UUID `json:"character_id"`
	CharacterName string    `json:"character_name"`
	CreatedAt     time.Time `json:"created_at"`
}

// Pending level-up / ASI prompts for one campaign, joined to the character's
// name for display. pending_asi only carries character_id, so the campaign is
// scoped via the player_characters membership row. Feeds the DM Console's
// unified pending list (internal/situation).
func (q *Queries) ListPendingASIByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListPendingASIByCampaignRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingASIByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingASIByCampaignRow{}
	for rows.Next() {
		var i ListPendingASIByCampaignRow
		if err := rows.Scan(&i.CharacterID, &i.CharacterName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPendingASI = `-- name: UpsertPendingASI :exec
INSERT INTO pending_asi (character_id, snapshot_json)
VALUES ($1, $2)
ON CONFLICT (character_id) DO UPDATE
    SET snapshot_json = EXCLUDED.snapshot_json,
        updated_at    = now()
`

type UpsertPendingASIParams struct {
	CharacterID  uuid.UUID       `json:"character_id"`
	SnapshotJson json.RawMessage `json:"snapshot_json"`
}

func (q *Queries) UpsertPendingASI(ctx context.Context, arg UpsertPendingASIParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingASI, arg.CharacterID, arg.SnapshotJson)
	return err
}
