// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_saves.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelAllPendingSavesByCombatant = `-- name: CancelAllPendingSavesByCombatant :exec
UPDATE pending_saves
SET status = 'forfeited', updated_at = now()
WHERE combatant_id = $1 AND encounter_id = $2 AND status = 'pending'
`

type CancelAllPendingSavesByCombatantParams struct {
	CombatantID uuid.UUID `json:"combatant_id"`
	EncounterID uuid.UUID `json:"encounter_id"`
}

func (q *Queries) CancelAllPendingSavesByCombatant(ctx context.Context, arg CancelAllPendingSavesByCombatantParams) error {
	_, err := q.db.ExecContext(ctx, cancelAllPendingSavesByCombatant, arg.CombatantID, arg.EncounterID)
	return err
}

const createPendingSave = `-- name: CreatePendingSave :one
INSERT INTO pending_saves (encounter_id, combatant_id, ability, dc, source, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, encounter_id, combatant_id, ability, dc, source, status, roll_result, success, created_at, updated_at
`

type CreatePendingSaveParams struct {
	EncounterID uuid.UUID `json:"encounter_id"`
	CombatantID uuid.UUID `json:"combatant_id"`
	Ability     string    `json:"ability"`
	Dc          int32     `json:"dc"`
	Source      string    `json:"source"`
}

func (q *Queries) CreatePendingSave(ctx context.Context, arg CreatePendingSaveParams) (PendingSafe, error) {
	row := q.db.QueryRowContext(ctx, createPendingSave,
		arg.EncounterID,
		arg.CombatantID,
		arg.Ability,
		arg.Dc,
		arg.Source,
	)
	var i PendingSafe
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Ability,
		&i.Dc,
		&i.Source,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const forfeitPendingSave = `-- name: ForfeitPendingSave :one
UPDATE pending_saves
SET status = 'forfeited', updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, combatant_id, ability, dc, source, status, roll_result, success, created_at, updated_at
`

func (q *Queries) ForfeitPendingSave(ctx context.Context, id uuid.UUID) (PendingSafe, error) {
	row := q.db.QueryRowContext(ctx, forfeitPendingSave, id)
	var i PendingSafe
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Ability,
		&i.Dc,
		&i.Source,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSave = `-- name: GetPendingSave :one
SELECT id, encounter_id, combatant_id, ability, dc, source, status, roll_result, success, created_at, updated_at FROM pending_saves WHERE id = $1
`

func (q *Queries) GetPendingSave(ctx context.Context, id uuid.UUID) (PendingSafe, error) {
	row := q.db.QueryRowContext(ctx, getPendingSave, id)
	var i PendingSafe
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Ability,
		&i.Dc,
		&i.Source,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingSavesByCombatant = `-- name: ListPendingSavesByCombatant :many
SELECT id, encounter_id, combatant_id, ability, dc, source, status, roll_result, success, created_at, updated_at FROM pending_saves
WHERE combatant_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingSavesByCombatant(ctx context.Context, combatantID uuid.UUID) ([]PendingSafe, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSavesByCombatant, combatantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingSafe{}
	for rows.Next() {
		var i PendingSafe
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Ability,
			&i.Dc,
			&i.Source,
			&i.Status,
			&i.RollResult,
			&i.Success,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSavesByEncounter = `-- name: ListPendingSavesByEncounter :many
SELECT id, encounter_id, combatant_id, ability, dc, source, status, roll_result, success, created_at, updated_at FROM pending_saves
WHERE encounter_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingSavesByEncounter(ctx context.Context, encounterID uuid.UUID) ([]PendingSafe, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSavesByEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingSafe{}
	for rows.Next() {
		var i PendingSafe
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Ability,
			&i.Dc,
			&i.Source,
			&i.Status,
			&i.RollResult,
			&i.Success,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePendingSaveResult = `-- name: UpdatePendingSaveResult :one
UPDATE pending_saves
SET roll_result = $2, success = $3, status = 'rolled', updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, combatant_id, ability, dc, source, status, roll_result, success, created_at, updated_at
`

type UpdatePendingSaveResultParams struct {
	ID         uuid.UUID     `json:"id"`
	RollResult sql.NullInt32 `json:"roll_result"`
	Success    sql.NullBool  `json:"success"`
}

func (q *Queries) UpdatePendingSaveResult(ctx context.Context, arg UpdatePendingSaveResultParams) (PendingSafe, error) {
	row := q.db.QueryRowContext(ctx, updatePendingSaveResult, arg.ID, arg.RollResult, arg.Success)
	var i PendingSafe
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Ability,
		&i.Dc,
		&i.Source,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
