// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_checks.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const forfeitPendingCheck = `-- name: ForfeitPendingCheck :one
UPDATE pending_checks
SET status = 'forfeited', updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, combatant_id, skill, dc, reason, status, roll_result, success, created_at, updated_at
`

func (q *Queries) ForfeitPendingCheck(ctx context.Context, id uuid.UUID) (PendingCheck, error) {
	row := q.db.QueryRowContext(ctx, forfeitPendingCheck, id)
	var i PendingCheck
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Skill,
		&i.Dc,
		&i.Reason,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingCheck = `-- name: GetPendingCheck :one
SELECT id, encounter_id, combatant_id, skill, dc, reason, status, roll_result, success, created_at, updated_at FROM pending_checks WHERE id = $1
`

func (q *Queries) GetPendingCheck(ctx context.Context, id uuid.UUID) (PendingCheck, error) {
	row := q.db.QueryRowContext(ctx, getPendingCheck, id)
	var i PendingCheck
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Skill,
		&i.Dc,
		&i.Reason,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingChecksByCombatant = `-- name: ListPendingChecksByCombatant :many
SELECT id, encounter_id, combatant_id, skill, dc, reason, status, roll_result, success, created_at, updated_at FROM pending_checks
WHERE combatant_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingChecksByCombatant(ctx context.Context, combatantID uuid.UUID) ([]PendingCheck, error) {
	rows, err := q.db.QueryContext(ctx, listPendingChecksByCombatant, combatantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingCheck{}
	for rows.Next() {
		var i PendingCheck
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Skill,
			&i.Dc,
			&i.Reason,
			&i.Status,
			&i.RollResult,
			&i.Success,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingChecksByEncounter = `-- name: ListPendingChecksByEncounter :many
SELECT id, encounter_id, combatant_id, skill, dc, reason, status, roll_result, success, created_at, updated_at FROM pending_checks
WHERE encounter_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingChecksByEncounter(ctx context.Context, encounterID uuid.UUID) ([]PendingCheck, error) {
	rows, err := q.db.QueryContext(ctx, listPendingChecksByEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingCheck{}
	for rows.Next() {
		var i PendingCheck
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Skill,
			&i.Dc,
			&i.Reason,
			&i.Status,
			&i.RollResult,
			&i.Success,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePendingCheckResult = `-- name: UpdatePendingCheckResult :one
UPDATE pending_checks
SET roll_result = $2, success = $3, status = 'rolled', updated_at = now()
WHERE id = $1
RETURNING id, encounter_id, combatant_id, skill, dc, reason, status, roll_result, success, created_at, updated_at
`

type UpdatePendingCheckResultParams struct {
	ID         uuid.UUID     `json:"id"`
	RollResult sql.NullInt32 `json:"roll_result"`
	Success    sql.NullBool  `json:"success"`
}

func (q *Queries) UpdatePendingCheckResult(ctx context.Context, arg UpdatePendingCheckResultParams) (PendingCheck, error) {
	row := q.db.QueryRowContext(ctx, updatePendingCheckResult, arg.ID, arg.RollResult, arg.Success)
	var i PendingCheck
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Skill,
		&i.Dc,
		&i.Reason,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPendingCheck = `-- name: UpsertPendingCheck :one
INSERT INTO pending_checks (encounter_id, combatant_id, skill, dc, reason, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, encounter_id, combatant_id, skill, dc, reason, status, roll_result, success, created_at, updated_at
`

type UpsertPendingCheckParams struct {
	EncounterID uuid.UUID      `json:"encounter_id"`
	CombatantID uuid.UUID      `json:"combatant_id"`
	Skill       string         `json:"skill"`
	Dc          int32          `json:"dc"`
	Reason      sql.NullString `json:"reason"`
}

func (q *Queries) UpsertPendingCheck(ctx context.Context, arg UpsertPendingCheckParams) (PendingCheck, error) {
	row := q.db.QueryRowContext(ctx, upsertPendingCheck,
		arg.EncounterID,
		arg.CombatantID,
		arg.Skill,
		arg.Dc,
		arg.Reason,
	)
	var i PendingCheck
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Skill,
		&i.Dc,
		&i.Reason,
		&i.Status,
		&i.RollResult,
		&i.Success,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
