// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_ddb_imports.sql

package refdata

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deletePendingDDBImport = `-- name: DeletePendingDDBImport :exec
DELETE FROM pending_ddb_imports WHERE id = $1
`

func (q *Queries) DeletePendingDDBImport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePendingDDBImport, id)
	return err
}

const getPendingDDBImport = `-- name: GetPendingDDBImport :one
SELECT id, character_id, params_json, created_at, updated_at
FROM pending_ddb_imports
WHERE id = $1
`

func (q *Queries) GetPendingDDBImport(ctx context.Context, id uuid.UUID) (PendingDdbImport, error) {
	row := q.db.QueryRowContext(ctx, getPendingDDBImport, id)
	var i PendingDdbImport
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.ParamsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPendingDDBImport = `-- name: UpsertPendingDDBImport :exec
INSERT INTO pending_ddb_imports (id, character_id, params_json, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET character_id = EXCLUDED.character_id,
        params_json  = EXCLUDED.params_json,
        created_at   = EXCLUDED.created_at,
        updated_at   = now()
`

type UpsertPendingDDBImportParams struct {
	ID          uuid.UUID       `json:"id"`
	CharacterID uuid.UUID       `json:"character_id"`
	ParamsJson  json.RawMessage `json:"params_json"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) UpsertPendingDDBImport(ctx context.Context, arg UpsertPendingDDBImportParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingDDBImport,
		arg.ID,
		arg.CharacterID,
		arg.ParamsJson,
		arg.CreatedAt,
	)
	return err
}
