// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_characters.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPlayerCharacter = `-- name: CreatePlayerCharacter :one
INSERT INTO player_characters (
    campaign_id, character_id, discord_user_id, status, dm_feedback, created_via
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, campaign_id, character_id, discord_user_id, status, dm_feedback, created_via, created_at, updated_at
`

type CreatePlayerCharacterParams struct {
	CampaignID    uuid.UUID      `json:"campaign_id"`
	CharacterID   uuid.UUID      `json:"character_id"`
	DiscordUserID string         `json:"discord_user_id"`
	Status        string         `json:"status"`
	DmFeedback    sql.NullString `json:"dm_feedback"`
	CreatedVia    string         `json:"created_via"`
}

func (q *Queries) CreatePlayerCharacter(ctx context.Context, arg CreatePlayerCharacterParams) (PlayerCharacter, error) {
	row := q.db.QueryRowContext(ctx, createPlayerCharacter,
		arg.CampaignID,
		arg.CharacterID,
		arg.DiscordUserID,
		arg.Status,
		arg.DmFeedback,
		arg.CreatedVia,
	)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.DiscordUserID,
		&i.Status,
		&i.DmFeedback,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCharacterByNameCaseInsensitive = `-- name: FindCharacterByNameCaseInsensitive :one
SELECT id, campaign_id, name, race, classes, level, ability_scores, hp_max, hp_current, temp_hp, ac, ac_formula, speed_ft, proficiency_bonus, equipped_main_hand, equipped_off_hand, equipped_armor, spell_slots, pact_magic_slots, hit_dice_remaining, feature_uses, features, proficiencies, gold, attunement_slots, languages, inventory, character_data, ddb_url, homebrew, created_at, updated_at, card_message_id FROM characters
WHERE campaign_id = $1 AND LOWER(name) = LOWER($2)
`

type FindCharacterByNameCaseInsensitiveParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Lower      string    `json:"lower"`
}

func (q *Queries) FindCharacterByNameCaseInsensitive(ctx context.Context, arg FindCharacterByNameCaseInsensitiveParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, findCharacterByNameCaseInsensitive, arg.CampaignID, arg.Lower)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Race,
		&i.Classes,
		&i.Level,
		&i.AbilityScores,
		&i.HpMax,
		&i.HpCurrent,
		&i.TempHp,
		&i.Ac,
		&i.AcFormula,
		&i.SpeedFt,
		&i.ProficiencyBonus,
		&i.EquippedMainHand,
		&i.EquippedOffHand,
		&i.EquippedArmor,
		&i.SpellSlots,
		&i.PactMagicSlots,
		&i.HitDiceRemaining,
		&i.FeatureUses,
		&i.Features,
		&i.Proficiencies,
		&i.Gold,
		&i.AttunementSlots,
		pq.Array(&i.Languages),
		&i.Inventory,
		&i.CharacterData,
		&i.DdbUrl,
		&i.Homebrew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardMessageID,
	)
	return i, err
}

const getPlayerCharacter = `-- name: GetPlayerCharacter :one
SELECT id, campaign_id, character_id, discord_user_id, status, dm_feedback, created_via, created_at, updated_at FROM player_characters WHERE id = $1
`

func (q *Queries) GetPlayerCharacter(ctx context.Context, id uuid.UUID) (PlayerCharacter, error) {
	row := q.db.QueryRowContext(ctx, getPlayerCharacter, id)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.DiscordUserID,
		&i.Status,
		&i.DmFeedback,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerCharacterByCharacter = `-- name: GetPlayerCharacterByCharacter :one
SELECT id, campaign_id, character_id, discord_user_id, status, dm_feedback, created_via, created_at, updated_at FROM player_characters
WHERE campaign_id = $1 AND character_id = $2
`

type GetPlayerCharacterByCharacterParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) GetPlayerCharacterByCharacter(ctx context.Context, arg GetPlayerCharacterByCharacterParams) (PlayerCharacter, error) {
	row := q.db.QueryRowContext(ctx, getPlayerCharacterByCharacter, arg.CampaignID, arg.CharacterID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.DiscordUserID,
		&i.Status,
		&i.DmFeedback,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerCharacterByDiscordUser = `-- name: GetPlayerCharacterByDiscordUser :one
SELECT id, campaign_id, character_id, discord_user_id, status, dm_feedback, created_via, created_at, updated_at FROM player_characters
WHERE campaign_id = $1 AND discord_user_id = $2
`

type GetPlayerCharacterByDiscordUserParams struct {
	CampaignID    uuid.UUID `json:"campaign_id"`
	DiscordUserID string    `json:"discord_user_id"`
}

func (q *Queries) GetPlayerCharacterByDiscordUser(ctx context.Context, arg GetPlayerCharacterByDiscordUserParams) (PlayerCharacter, error) {
	row := q.db.QueryRowContext(ctx, getPlayerCharacterByDiscordUser, arg.CampaignID, arg.DiscordUserID)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.DiscordUserID,
		&i.Status,
		&i.DmFeedback,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerCharacterWithCharacter = `-- name: GetPlayerCharacterWithCharacter :one
SELECT pc.id, pc.campaign_id, pc.character_id, pc.discord_user_id, pc.status,
       pc.dm_feedback, pc.created_via, pc.created_at, pc.updated_at,
       c.name AS character_name, c.race, c.level, c.classes, c.hp_max,
       c.hp_current, c.ac, c.speed_ft, c.ability_scores, c.languages, c.ddb_url
FROM player_characters pc
JOIN characters c ON c.id = pc.character_id
WHERE pc.id = $1
`

type GetPlayerCharacterWithCharacterRow struct {
	ID            uuid.UUID       `json:"id"`
	CampaignID    uuid.UUID       `json:"campaign_id"`
	CharacterID   uuid.UUID       `json:"character_id"`
	DiscordUserID string          `json:"discord_user_id"`
	Status        string          `json:"status"`
	DmFeedback    sql.NullString  `json:"dm_feedback"`
	CreatedVia    string          `json:"created_via"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	CharacterName string          `json:"character_name"`
	Race          string          `json:"race"`
	Level         int32           `json:"level"`
	Classes       json.RawMessage `json:"classes"`
	HpMax         int32           `json:"hp_max"`
	HpCurrent     int32           `json:"hp_current"`
	Ac            int32           `json:"ac"`
	SpeedFt       int32           `json:"speed_ft"`
	AbilityScores json.RawMessage `json:"ability_scores"`
	Languages     []string        `json:"languages"`
	DdbUrl        sql.NullString  `json:"ddb_url"`
}

func (q *Queries) GetPlayerCharacterWithCharacter(ctx context.Context, id uuid.UUID) (GetPlayerCharacterWithCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerCharacterWithCharacter, id)
	var i GetPlayerCharacterWithCharacterRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.DiscordUserID,
		&i.Status,
		&i.DmFeedback,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CharacterName,
		&i.Race,
		&i.Level,
		&i.Classes,
		&i.HpMax,
		&i.HpCurrent,
		&i.Ac,
		&i.SpeedFt,
		&i.AbilityScores,
		pq.Array(&i.Languages),
		&i.DdbUrl,
	)
	return i, err
}

const listCharacterNamesByCampaign = `-- name: ListCharacterNamesByCampaign :many
SELECT id, name FROM characters
WHERE campaign_id = $1
ORDER BY name
`

type ListCharacterNamesByCampaignRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListCharacterNamesByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListCharacterNamesByCampaignRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterNamesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCharacterNamesByCampaignRow{}
	for rows.Next() {
		var i ListCharacterNamesByCampaignRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerCharactersByCampaign = `-- name: ListPlayerCharactersByCampaign :many
SELECT id, campaign_id, character_id, discord_user_id, status, dm_feedback, created_via, created_at, updated_at FROM player_characters
WHERE campaign_id = $1
ORDER BY created_at
`

func (q *Queries) ListPlayerCharactersByCampaign(ctx context.Context, campaignID uuid.UUID) ([]PlayerCharacter, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerCharactersByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerCharacter{}
	for rows.Next() {
		var i PlayerCharacter
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CharacterID,
			&i.DiscordUserID,
			&i.Status,
			&i.DmFeedback,
			&i.CreatedVia,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerCharactersByStatus = `-- name: ListPlayerCharactersByStatus :many
SELECT pc.id, pc.campaign_id, pc.character_id, pc.discord_user_id, pc.status,
       pc.dm_feedback, pc.created_via, pc.created_at, pc.updated_at,
       c.name AS character_name, c.race, c.level, c.classes, c.hp_max,
       c.hp_current, c.ac, c.speed_ft, c.ability_scores, c.languages, c.ddb_url
FROM player_characters pc
JOIN characters c ON c.id = pc.character_id
WHERE pc.campaign_id = $1 AND pc.status = $2
ORDER BY pc.created_at
`

type ListPlayerCharactersByStatusParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Status     string    `json:"status"`
}

type ListPlayerCharactersByStatusRow struct {
	ID            uuid.UUID       `json:"id"`
	CampaignID    uuid.UUID       `json:"campaign_id"`
	CharacterID   uuid.UUID       `json:"character_id"`
	DiscordUserID string          `json:"discord_user_id"`
	Status        string          `json:"status"`
	DmFeedback    sql.NullString  `json:"dm_feedback"`
	CreatedVia    string          `json:"created_via"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	CharacterName string          `json:"character_name"`
	Race          string          `json:"race"`
	Level         int32           `json:"level"`
	Classes       json.RawMessage `json:"classes"`
	HpMax         int32           `json:"hp_max"`
	HpCurrent     int32           `json:"hp_current"`
	Ac            int32           `json:"ac"`
	SpeedFt       int32           `json:"speed_ft"`
	AbilityScores json.RawMessage `json:"ability_scores"`
	Languages     []string        `json:"languages"`
	DdbUrl        sql.NullString  `json:"ddb_url"`
}

func (q *Queries) ListPlayerCharactersByStatus(ctx context.Context, arg ListPlayerCharactersByStatusParams) ([]ListPlayerCharactersByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerCharactersByStatus, arg.CampaignID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerCharactersByStatusRow{}
	for rows.Next() {
		var i ListPlayerCharactersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CharacterID,
			&i.DiscordUserID,
			&i.Status,
			&i.DmFeedback,
			&i.CreatedVia,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CharacterName,
			&i.Race,
			&i.Level,
			&i.Classes,
			&i.HpMax,
			&i.HpCurrent,
			&i.Ac,
			&i.SpeedFt,
			&i.AbilityScores,
			pq.Array(&i.Languages),
			&i.DdbUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerCharacterStatus = `-- name: UpdatePlayerCharacterStatus :one
UPDATE player_characters
SET status = $2, dm_feedback = $3, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, character_id, discord_user_id, status, dm_feedback, created_via, created_at, updated_at
`

type UpdatePlayerCharacterStatusParams struct {
	ID         uuid.UUID      `json:"id"`
	Status     string         `json:"status"`
	DmFeedback sql.NullString `json:"dm_feedback"`
}

func (q *Queries) UpdatePlayerCharacterStatus(ctx context.Context, arg UpdatePlayerCharacterStatusParams) (PlayerCharacter, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerCharacterStatus, arg.ID, arg.Status, arg.DmFeedback)
	var i PlayerCharacter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.DiscordUserID,
		&i.Status,
		&i.DmFeedback,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
