// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: races.sql

package refdata

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countRaces = `-- name: CountRaces :one
SELECT count(*) FROM races
`

func (q *Queries) CountRaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHomebrewRace = `-- name: DeleteHomebrewRace :execrows
DELETE FROM races WHERE id = $1 AND homebrew = true AND campaign_id = $2
`

type DeleteHomebrewRaceParams struct {
	ID         string        `json:"id"`
	CampaignID uuid.NullUUID `json:"campaign_id"`
}

func (q *Queries) DeleteHomebrewRace(ctx context.Context, arg DeleteHomebrewRaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHomebrewRace, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRace = `-- name: GetRace :one
SELECT id, name, speed_ft, size, ability_bonuses, darkvision_ft, traits, languages, subraces, created_at, updated_at, campaign_id, homebrew, source FROM races WHERE id = $1
`

func (q *Queries) GetRace(ctx context.Context, id string) (Race, error) {
	row := q.db.QueryRowContext(ctx, getRace, id)
	var i Race
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpeedFt,
		&i.Size,
		&i.AbilityBonuses,
		&i.DarkvisionFt,
		&i.Traits,
		pq.Array(&i.Languages),
		&i.Subraces,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
		&i.Homebrew,
		&i.Source,
	)
	return i, err
}

const listRaces = `-- name: ListRaces :many
SELECT id, name, speed_ft, size, ability_bonuses, darkvision_ft, traits, languages, subraces, created_at, updated_at, campaign_id, homebrew, source FROM races ORDER BY name
`

func (q *Queries) ListRaces(ctx context.Context) ([]Race, error) {
	rows, err := q.db.QueryContext(ctx, listRaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Race{}
	for rows.Next() {
		var i Race
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpeedFt,
			&i.Size,
			&i.AbilityBonuses,
			&i.DarkvisionFt,
			&i.Traits,
			pq.Array(&i.Languages),
			&i.Subraces,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignID,
			&i.Homebrew,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRace = `-- name: UpsertRace :exec
INSERT INTO races (id, name, speed_ft, size, ability_bonuses, darkvision_ft, traits, languages, subraces, campaign_id, homebrew, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    speed_ft = EXCLUDED.speed_ft,
    size = EXCLUDED.size,
    ability_bonuses = EXCLUDED.ability_bonuses,
    darkvision_ft = EXCLUDED.darkvision_ft,
    traits = EXCLUDED.traits,
    languages = EXCLUDED.languages,
    subraces = EXCLUDED.subraces,
    campaign_id = EXCLUDED.campaign_id,
    homebrew = EXCLUDED.homebrew,
    source = EXCLUDED.source,
    updated_at = now()
`

type UpsertRaceParams struct {
	ID             string                `json:"id"`
	Name           string                `json:"name"`
	SpeedFt        int32                 `json:"speed_ft"`
	Size           string                `json:"size"`
	AbilityBonuses json.RawMessage       `json:"ability_bonuses"`
	DarkvisionFt   int32                 `json:"darkvision_ft"`
	Traits         json.RawMessage       `json:"traits"`
	Languages      []string              `json:"languages"`
	Subraces       pqtype.NullRawMessage `json:"subraces"`
	CampaignID     uuid.NullUUID         `json:"campaign_id"`
	Homebrew       sql.NullBool          `json:"homebrew"`
	Source         sql.NullString        `json:"source"`
}

func (q *Queries) UpsertRace(ctx context.Context, arg UpsertRaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertRace,
		arg.ID,
		arg.Name,
		arg.SpeedFt,
		arg.Size,
		arg.AbilityBonuses,
		arg.DarkvisionFt,
		arg.Traits,
		pq.Array(arg.Languages),
		arg.Subraces,
		arg.CampaignID,
		arg.Homebrew,
		arg.Source,
	)
	return err
}
