// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reaction_declarations.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelAllReactionDeclarationsByCombatant = `-- name: CancelAllReactionDeclarationsByCombatant :exec
UPDATE reaction_declarations
SET status = 'cancelled'
WHERE combatant_id = $1 AND encounter_id = $2 AND status = 'active'
`

type CancelAllReactionDeclarationsByCombatantParams struct {
	CombatantID uuid.UUID `json:"combatant_id"`
	EncounterID uuid.UUID `json:"encounter_id"`
}

func (q *Queries) CancelAllReactionDeclarationsByCombatant(ctx context.Context, arg CancelAllReactionDeclarationsByCombatantParams) error {
	_, err := q.db.ExecContext(ctx, cancelAllReactionDeclarationsByCombatant, arg.CombatantID, arg.EncounterID)
	return err
}

const cancelReactionDeclaration = `-- name: CancelReactionDeclaration :one
UPDATE reaction_declarations
SET status = 'cancelled'
WHERE id = $1 AND status = 'active'
RETURNING id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id
`

func (q *Queries) CancelReactionDeclaration(ctx context.Context, id uuid.UUID) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, cancelReactionDeclaration, id)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}

const createReactionDeclaration = `-- name: CreateReactionDeclaration :one
INSERT INTO reaction_declarations (encounter_id, combatant_id, description)
VALUES ($1, $2, $3)
RETURNING id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id
`

type CreateReactionDeclarationParams struct {
	EncounterID uuid.UUID `json:"encounter_id"`
	CombatantID uuid.UUID `json:"combatant_id"`
	Description string    `json:"description"`
}

func (q *Queries) CreateReactionDeclaration(ctx context.Context, arg CreateReactionDeclarationParams) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, createReactionDeclaration, arg.EncounterID, arg.CombatantID, arg.Description)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}

const createReadiedActionDeclaration = `-- name: CreateReadiedActionDeclaration :one
INSERT INTO reaction_declarations (encounter_id, combatant_id, description, is_readied_action, spell_name, spell_slot_level)
VALUES ($1, $2, $3, true, $4, $5)
RETURNING id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id
`

type CreateReadiedActionDeclarationParams struct {
	EncounterID    uuid.UUID      `json:"encounter_id"`
	CombatantID    uuid.UUID      `json:"combatant_id"`
	Description    string         `json:"description"`
	SpellName      sql.NullString `json:"spell_name"`
	SpellSlotLevel sql.NullInt32  `json:"spell_slot_level"`
}

func (q *Queries) CreateReadiedActionDeclaration(ctx context.Context, arg CreateReadiedActionDeclarationParams) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, createReadiedActionDeclaration,
		arg.EncounterID,
		arg.CombatantID,
		arg.Description,
		arg.SpellName,
		arg.SpellSlotLevel,
	)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}

const deleteReactionDeclarationsByEncounter = `-- name: DeleteReactionDeclarationsByEncounter :exec
DELETE FROM reaction_declarations WHERE encounter_id = $1
`

func (q *Queries) DeleteReactionDeclarationsByEncounter(ctx context.Context, encounterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReactionDeclarationsByEncounter, encounterID)
	return err
}

const getReactionDeclaration = `-- name: GetReactionDeclaration :one
SELECT id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id FROM reaction_declarations WHERE id = $1
`

func (q *Queries) GetReactionDeclaration(ctx context.Context, id uuid.UUID) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, getReactionDeclaration, id)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}

const listActiveReactionDeclarationsByCombatant = `-- name: ListActiveReactionDeclarationsByCombatant :many
SELECT id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id FROM reaction_declarations WHERE combatant_id = $1 AND encounter_id = $2 AND status = 'active' ORDER BY created_at ASC
`

type ListActiveReactionDeclarationsByCombatantParams struct {
	CombatantID uuid.UUID `json:"combatant_id"`
	EncounterID uuid.UUID `json:"encounter_id"`
}

func (q *Queries) ListActiveReactionDeclarationsByCombatant(ctx context.Context, arg ListActiveReactionDeclarationsByCombatantParams) ([]ReactionDeclaration, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReactionDeclarationsByCombatant, arg.CombatantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionDeclaration{}
	for rows.Next() {
		var i ReactionDeclaration
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedOnRound,
			&i.IsReadiedAction,
			&i.SpellName,
			&i.SpellSlotLevel,
			&i.CounterspellEnemySpell,
			&i.CounterspellEnemyLevel,
			&i.CounterspellSlotUsed,
			&i.CounterspellStatus,
			&i.CounterspellDc,
			&i.CounterspellEnemyCasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveReactionDeclarationsByEncounter = `-- name: ListActiveReactionDeclarationsByEncounter :many
SELECT id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id FROM reaction_declarations WHERE encounter_id = $1 AND status = 'active' ORDER BY created_at ASC
`

func (q *Queries) ListActiveReactionDeclarationsByEncounter(ctx context.Context, encounterID uuid.UUID) ([]ReactionDeclaration, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReactionDeclarationsByEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionDeclaration{}
	for rows.Next() {
		var i ReactionDeclaration
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedOnRound,
			&i.IsReadiedAction,
			&i.SpellName,
			&i.SpellSlotLevel,
			&i.CounterspellEnemySpell,
			&i.CounterspellEnemyLevel,
			&i.CounterspellSlotUsed,
			&i.CounterspellStatus,
			&i.CounterspellDc,
			&i.CounterspellEnemyCasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionDeclarationsByCombatant = `-- name: ListReactionDeclarationsByCombatant :many
SELECT id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id FROM reaction_declarations WHERE combatant_id = $1 AND encounter_id = $2 ORDER BY created_at ASC
`

type ListReactionDeclarationsByCombatantParams struct {
	CombatantID uuid.UUID `json:"combatant_id"`
	EncounterID uuid.UUID `json:"encounter_id"`
}

func (q *Queries) ListReactionDeclarationsByCombatant(ctx context.Context, arg ListReactionDeclarationsByCombatantParams) ([]ReactionDeclaration, error) {
	rows, err := q.db.QueryContext(ctx, listReactionDeclarationsByCombatant, arg.CombatantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionDeclaration{}
	for rows.Next() {
		var i ReactionDeclaration
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedOnRound,
			&i.IsReadiedAction,
			&i.SpellName,
			&i.SpellSlotLevel,
			&i.CounterspellEnemySpell,
			&i.CounterspellEnemyLevel,
			&i.CounterspellSlotUsed,
			&i.CounterspellStatus,
			&i.CounterspellDc,
			&i.CounterspellEnemyCasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionDeclarationsByEncounter = `-- name: ListReactionDeclarationsByEncounter :many
SELECT id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id FROM reaction_declarations WHERE encounter_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListReactionDeclarationsByEncounter(ctx context.Context, encounterID uuid.UUID) ([]ReactionDeclaration, error) {
	rows, err := q.db.QueryContext(ctx, listReactionDeclarationsByEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionDeclaration{}
	for rows.Next() {
		var i ReactionDeclaration
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedOnRound,
			&i.IsReadiedAction,
			&i.SpellName,
			&i.SpellSlotLevel,
			&i.CounterspellEnemySpell,
			&i.CounterspellEnemyLevel,
			&i.CounterspellSlotUsed,
			&i.CounterspellStatus,
			&i.CounterspellDc,
			&i.CounterspellEnemyCasterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReactionDeclarationCounterspellPrompt = `-- name: UpdateReactionDeclarationCounterspellPrompt :one
UPDATE reaction_declarations
SET counterspell_enemy_spell = $2, counterspell_enemy_level = $3, counterspell_enemy_caster_id = $4, counterspell_status = 'prompted'
WHERE id = $1
RETURNING id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id
`

type UpdateReactionDeclarationCounterspellPromptParams struct {
	ID                        uuid.UUID      `json:"id"`
	CounterspellEnemySpell    sql.NullString `json:"counterspell_enemy_spell"`
	CounterspellEnemyLevel    sql.NullInt32  `json:"counterspell_enemy_level"`
	CounterspellEnemyCasterID uuid.NullUUID  `json:"counterspell_enemy_caster_id"`
}

func (q *Queries) UpdateReactionDeclarationCounterspellPrompt(ctx context.Context, arg UpdateReactionDeclarationCounterspellPromptParams) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, updateReactionDeclarationCounterspellPrompt,
		arg.ID,
		arg.CounterspellEnemySpell,
		arg.CounterspellEnemyLevel,
		arg.CounterspellEnemyCasterID,
	)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}

const updateReactionDeclarationCounterspellResolved = `-- name: UpdateReactionDeclarationCounterspellResolved :one
UPDATE reaction_declarations
SET counterspell_slot_used = $2, counterspell_status = $3, counterspell_dc = $4
WHERE id = $1
RETURNING id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id
`

type UpdateReactionDeclarationCounterspellResolvedParams struct {
	ID                   uuid.UUID      `json:"id"`
	CounterspellSlotUsed sql.NullInt32  `json:"counterspell_slot_used"`
	CounterspellStatus   sql.NullString `json:"counterspell_status"`
	CounterspellDc       sql.NullInt32  `json:"counterspell_dc"`
}

func (q *Queries) UpdateReactionDeclarationCounterspellResolved(ctx context.Context, arg UpdateReactionDeclarationCounterspellResolvedParams) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, updateReactionDeclarationCounterspellResolved,
		arg.ID,
		arg.CounterspellSlotUsed,
		arg.CounterspellStatus,
		arg.CounterspellDc,
	)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}

const updateReactionDeclarationStatusUsed = `-- name: UpdateReactionDeclarationStatusUsed :one
UPDATE reaction_declarations
SET status = 'used', used_at = now(), used_on_round = $2
WHERE id = $1
RETURNING id, encounter_id, combatant_id, description, status, created_at, used_at, used_on_round, is_readied_action, spell_name, spell_slot_level, counterspell_enemy_spell, counterspell_enemy_level, counterspell_slot_used, counterspell_status, counterspell_dc, counterspell_enemy_caster_id
`

type UpdateReactionDeclarationStatusUsedParams struct {
	ID          uuid.UUID     `json:"id"`
	UsedOnRound sql.NullInt32 `json:"used_on_round"`
}

func (q *Queries) UpdateReactionDeclarationStatusUsed(ctx context.Context, arg UpdateReactionDeclarationStatusUsedParams) (ReactionDeclaration, error) {
	row := q.db.QueryRowContext(ctx, updateReactionDeclarationStatusUsed, arg.ID, arg.UsedOnRound)
	var i ReactionDeclaration
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedOnRound,
		&i.IsReadiedAction,
		&i.SpellName,
		&i.SpellSlotLevel,
		&i.CounterspellEnemySpell,
		&i.CounterspellEnemyLevel,
		&i.CounterspellSlotUsed,
		&i.CounterspellStatus,
		&i.CounterspellDc,
		&i.CounterspellEnemyCasterID,
	)
	return i, err
}
