package refdata

// srdCreaturesCR6to7 returns SRD creatures with CR 6-7.
func srdCreaturesCR6to7() []cr {
	return []cr{
		// ——— CR 6 ———
		{
			ID: "chimera", Name: "Chimera", Size: "Large", Type: "monstrosity", Alignment: optStr("chaotic evil"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "12d10+48", HpAverage: 114,
			Speed:         mustJSON(map[string]int{"walk": 30, "fly": 60}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 11, "con": 19, "int": 3, "wis": 14, "cha": 10}),
			Skills:        optJSON(map[string]int{"perception": 8}),
			Senses:        optJSON(map[string]any{"darkvision": 60, "passive_perception": 18}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"understands draconic but can't speak"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Bite", "to_hit": 7, "damage": "2d6+4", "damage_type": "piercing", "reach_ft": 5},
				{"name": "Horns", "to_hit": 7, "damage": "1d12+4", "damage_type": "bludgeoning", "reach_ft": 5},
				{"name": "Claws", "to_hit": 7, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Fire Breath (Recharge 5-6)", "description": "The dragon head exhales fire in a 15-foot cone. Each creature in that area must make a DC 15 Dexterity saving throw, taking 31 (7d8) fire damage on a failed save, or half as much damage on a successful one."},
			}),
		},
		{
			ID: "cyclops", Name: "Cyclops", Size: "Huge", Type: "giant", Alignment: optStr("chaotic neutral"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "12d12+60", HpAverage: 138,
			Speed:         mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 22, "dex": 11, "con": 20, "int": 8, "wis": 6, "cha": 10}),
			Senses:        optJSON(map[string]any{"passive_perception": 8}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"giant"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Greatclub", "to_hit": 9, "damage": "3d8+6", "damage_type": "bludgeoning", "reach_ft": 10},
				{"name": "Rock", "to_hit": 9, "damage": "4d10+6", "damage_type": "bludgeoning", "reach_ft": 120},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Poor Depth Perception", "description": "The cyclops has disadvantage on any attack roll against a target more than 30 feet away."},
			}),
		},
		{
			ID: "drider", Name: "Drider", Size: "Large", Type: "monstrosity", Alignment: optStr("chaotic evil"),
			Ac: 19, AcType: optStr("natural armor"), HpFormula: "13d10+52", HpAverage: 123,
			Speed:         mustJSON(map[string]int{"walk": 30, "climb": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 16, "con": 18, "int": 13, "wis": 14, "cha": 12}),
			Skills:        optJSON(map[string]int{"perception": 5, "stealth": 9}),
			Senses:        optJSON(map[string]any{"darkvision": 120, "passive_perception": 15}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"elvish", "undercommon"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Longsword", "to_hit": 6, "damage": "1d8+3", "damage_type": "slashing", "reach_ft": 5},
				{"name": "Longbow", "to_hit": 6, "damage": "1d8+3", "damage_type": "piercing", "reach_ft": 150},
				{"name": "Bite", "to_hit": 6, "damage": "1d4+3", "damage_type": "piercing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Fey Ancestry", "description": "The drider has advantage on saving throws against being charmed, and magic can't put the drider to sleep."},
				{"name": "Spider Climb", "description": "The drider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."},
				{"name": "Sunlight Sensitivity", "description": "While in sunlight, the drider has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."},
				{"name": "Web Walker", "description": "The drider ignores movement restrictions caused by webbing."},
				{"name": "Innate Spellcasting", "description": "The drider's innate spellcasting ability is Wisdom (spell save DC 13). The drider can innately cast the following spells, requiring no material components: At will: dancing lights; 1/day each: darkness, faerie fire."},
			}),
		},
		{
			ID: "galeb-duhr", Name: "Galeb Duhr", Size: "Medium", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 16, AcType: optStr("natural armor"), HpFormula: "9d8+45", HpAverage: 85,
			Speed:         mustJSON(map[string]int{"walk": 15}),
			AbilityScores: mustJSON(map[string]int{"str": 20, "dex": 14, "con": 20, "int": 11, "wis": 12, "cha": 11}),
			DamageResistances: []string{"bludgeoning", "piercing", "slashing from nonmagical attacks"},
			DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{},
			ConditionImmunities: []string{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"},
			Senses:    optJSON(map[string]any{"darkvision": 60, "tremorsense": 60, "passive_perception": 11}),
			Languages: []string{"terran"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Slam", "to_hit": 8, "damage": "2d6+5", "damage_type": "bludgeoning", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "False Appearance", "description": "While the galeb duhr remains motionless, it is indistinguishable from a normal boulder."},
				{"name": "Rolling Charge", "description": "If the galeb duhr rolls at least 20 feet straight toward a target and then hits it with a slam attack on the same turn, the target takes an extra 7 (2d6) bludgeoning damage. If the target is a creature, it must succeed on a DC 16 Strength saving throw or be knocked prone."},
				{"name": "Animate Boulders (1/Day)", "description": "The galeb duhr magically animates up to two boulders it can see within 60 feet of it. A boulder has statistics like those of a galeb duhr, except it has Intelligence 1 and Charisma 1, it can't be charmed or frightened, and it lacks this action option. A boulder remains animated for 1 minute, until the galeb duhr dies, or until the galeb duhr dismisses it as a bonus action."},
			}),
		},
		{
			ID: "invisible-stalker", Name: "Invisible Stalker", Size: "Medium", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 14, HpFormula: "16d8+32", HpAverage: 104,
			Speed:         mustJSON(map[string]int{"walk": 50, "fly": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 19, "con": 14, "int": 10, "wis": 15, "cha": 11}),
			Skills:        optJSON(map[string]int{"perception": 8, "stealth": 10}),
			DamageResistances: []string{"bludgeoning", "piercing", "slashing from nonmagical attacks"},
			DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{},
			ConditionImmunities: []string{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"},
			Senses:    optJSON(map[string]any{"darkvision": 60, "passive_perception": 18}),
			Languages: []string{"auran", "understands common but doesn't speak it"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Slam", "to_hit": 6, "damage": "2d6+3", "damage_type": "bludgeoning", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Invisibility", "description": "The stalker is invisible."},
				{"name": "Faultless Tracker", "description": "The stalker is given a quarry by its summoner. The stalker knows the direction and distance to its quarry as long as the two of them are on the same plane of existence."},
			}),
		},
		{
			ID: "mammoth", Name: "Mammoth", Size: "Huge", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "11d12+55", HpAverage: 126,
			Speed:         mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 24, "dex": 9, "con": 21, "int": 3, "wis": 11, "cha": 6}),
			Senses:        optJSON(map[string]any{"passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Gore", "to_hit": 10, "damage": "4d8+7", "damage_type": "piercing", "reach_ft": 10},
				{"name": "Stomp", "to_hit": 10, "damage": "4d10+7", "damage_type": "bludgeoning", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Trampling Charge", "description": "If the mammoth moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 18 Strength saving throw or be knocked prone. If the target is prone, the mammoth can make one stomp attack against it as a bonus action."},
			}),
		},
		{
			ID: "medusa", Name: "Medusa", Size: "Medium", Type: "monstrosity", Alignment: optStr("lawful evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "17d8+51", HpAverage: 127,
			Speed:         mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 10, "dex": 15, "con": 16, "int": 12, "wis": 13, "cha": 15}),
			Skills:        optJSON(map[string]int{"deception": 5, "insight": 4, "perception": 4, "stealth": 5}),
			Senses:        optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"common"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Shortsword", "to_hit": 5, "damage": "1d6+2", "damage_type": "piercing", "reach_ft": 5},
				{"name": "Longbow", "to_hit": 5, "damage": "1d8+2", "damage_type": "piercing", "reach_ft": 150},
				{"name": "Snake Hair", "to_hit": 5, "damage": "1d4+2", "damage_type": "piercing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Petrifying Gaze", "description": "When a creature that can see the medusa's eyes starts its turn within 30 feet of the medusa, the medusa can force it to make a DC 14 Constitution saving throw if the medusa isn't incapacitated and can see the creature. On a failed save, the creature is restrained and must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified."},
			}),
		},
		{
			ID: "vrock", Name: "Vrock", Size: "Large", Type: "fiend", Alignment: optStr("chaotic evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "11d10+44", HpAverage: 104,
			Speed:         mustJSON(map[string]int{"walk": 40, "fly": 60}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 15, "con": 18, "int": 8, "wis": 13, "cha": 8}),
			SavingThrows:  optJSON(map[string]int{"dex": 5, "wis": 4, "cha": 2}),
			DamageResistances: []string{"cold", "fire", "lightning", "bludgeoning", "piercing", "slashing from nonmagical attacks"},
			DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{},
			ConditionImmunities: []string{"poisoned"},
			Senses:    optJSON(map[string]any{"darkvision": 120, "passive_perception": 11}),
			Languages: []string{"abyssal", "telepathy 120 ft."},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Beak", "to_hit": 6, "damage": "2d6+3", "damage_type": "piercing", "reach_ft": 5},
				{"name": "Talons", "to_hit": 6, "damage": "2d10+3", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Magic Resistance", "description": "The vrock has advantage on saving throws against spells and other magical effects."},
				{"name": "Spores (Recharge 6)", "description": "A 15-foot-radius cloud of toxic spores extends out from the vrock. The spores spread around corners. Each creature in that area must succeed on a DC 14 Constitution saving throw or become poisoned. While poisoned in this way, a target takes 5 (1d10) poison damage at the start of each of its turns. A target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success."},
				{"name": "Stunning Screech (1/Day)", "description": "The vrock emits a horrific screech. Each creature within 20 feet of it that can hear it and that isn't a demon must succeed on a DC 14 Constitution saving throw or be stunned until the end of the vrock's next turn."},
			}),
		},
		{
			ID: "wyvern", Name: "Wyvern", Size: "Large", Type: "dragon", Alignment: optStr("unaligned"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "13d10+39", HpAverage: 110,
			Speed:         mustJSON(map[string]int{"walk": 20, "fly": 80}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 10, "con": 16, "int": 5, "wis": 12, "cha": 6}),
			Skills:        optJSON(map[string]int{"perception": 4}),
			Senses:        optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Bite", "to_hit": 7, "damage": "2d6+4", "damage_type": "piercing", "reach_ft": 10},
				{"name": "Claws", "to_hit": 7, "damage": "2d8+4", "damage_type": "slashing", "reach_ft": 5},
				{"name": "Stinger", "to_hit": 7, "damage": "2d6+4", "damage_type": "piercing", "reach_ft": 10},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Stinger Poison", "description": "The target must make a DC 15 Constitution saving throw, taking 24 (7d6) poison damage on a failed save, or half as much damage on a successful one."},
			}),
		},
		{
			ID: "young-brass-dragon", Name: "Young Brass Dragon", Size: "Large", Type: "dragon", Alignment: optStr("chaotic good"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "13d10+39", HpAverage: 110,
			Speed:         mustJSON(map[string]int{"walk": 40, "burrow": 20, "fly": 80}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 10, "con": 17, "int": 12, "wis": 11, "cha": 15}),
			SavingThrows:  optJSON(map[string]int{"dex": 3, "con": 6, "wis": 3, "cha": 5}),
			Skills:        optJSON(map[string]int{"perception": 6, "persuasion": 5, "stealth": 3}),
			DamageResistances: []string{}, DamageImmunities: []string{"fire"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Senses:    optJSON(map[string]any{"blindsight": 30, "darkvision": 120, "passive_perception": 16}),
			Languages: []string{"common", "draconic"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Bite", "to_hit": 7, "damage": "2d10+4", "damage_type": "piercing", "reach_ft": 10},
				{"name": "Claw", "to_hit": 7, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Breath Weapons (Recharge 5-6)", "description": "The dragon uses one of the following breath weapons. Fire Breath: The dragon exhales fire in a 40-foot line that is 5 feet wide. Each creature in that line must make a DC 14 Dexterity saving throw, taking 42 (12d6) fire damage on a failed save, or half as much damage on a successful one. Sleep Breath: The dragon exhales sleep gas in a 30-foot cone. Each creature in that area must succeed on a DC 14 Constitution saving throw or fall unconscious for 5 minutes. This effect ends for a creature if the creature takes damage or someone uses an action to wake it."},
			}),
		},
		{
			ID: "young-white-dragon", Name: "Young White Dragon", Size: "Large", Type: "dragon", Alignment: optStr("chaotic evil"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "14d10+56", HpAverage: 133,
			Speed:         mustJSON(map[string]int{"walk": 40, "burrow": 20, "fly": 80, "swim": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 10, "con": 18, "int": 6, "wis": 11, "cha": 12}),
			SavingThrows:  optJSON(map[string]int{"dex": 3, "con": 7, "wis": 3, "cha": 4}),
			Skills:        optJSON(map[string]int{"perception": 6, "stealth": 3}),
			DamageResistances: []string{}, DamageImmunities: []string{"cold"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Senses:    optJSON(map[string]any{"blindsight": 30, "darkvision": 120, "passive_perception": 16}),
			Languages: []string{"common", "draconic"},
			Cr:        "6",
			Attacks: mustJSON([]map[string]any{
				{"name": "Bite", "to_hit": 7, "damage": "2d10+4", "damage_type": "piercing", "reach_ft": 10},
				{"name": "Claw", "to_hit": 7, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Ice Walk", "description": "The dragon can move across and climb icy surfaces without needing to make an ability check. Additionally, difficult terrain composed of ice or snow doesn't cost it extra movement."},
				{"name": "Cold Breath (Recharge 5-6)", "description": "The dragon exhales an icy blast in a 30-foot cone. Each creature in that area must make a DC 15 Constitution saving throw, taking 45 (10d8) cold damage on a failed save, or half as much damage on a successful one."},
			}),
		},

		// ——— CR 7 ———
		{
			ID: "giant-ape", Name: "Giant Ape", Size: "Huge", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 12, HpFormula: "15d12+60", HpAverage: 157,
			Speed:         mustJSON(map[string]int{"walk": 40, "climb": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 23, "dex": 14, "con": 18, "int": 7, "wis": 12, "cha": 7}),
			Skills:        optJSON(map[string]int{"athletics": 9, "perception": 4}),
			Senses:        optJSON(map[string]any{"passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr:        "7",
			Attacks: mustJSON([]map[string]any{
				{"name": "Fist", "to_hit": 9, "damage": "3d10+6", "damage_type": "bludgeoning", "reach_ft": 10},
				{"name": "Rock", "to_hit": 9, "damage": "7d6+6", "damage_type": "bludgeoning", "reach_ft": 50},
			}),
		},
		{
			ID: "oni", Name: "Oni", Size: "Large", Type: "giant", Alignment: optStr("lawful evil"),
			Ac: 16, AcType: optStr("chain mail"), HpFormula: "13d10+39", HpAverage: 110,
			Speed:         mustJSON(map[string]int{"walk": 30, "fly": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 11, "con": 16, "int": 14, "wis": 12, "cha": 15}),
			SavingThrows:  optJSON(map[string]int{"dex": 3, "con": 6, "wis": 4, "cha": 5}),
			Skills:        optJSON(map[string]int{"arcana": 5, "deception": 8, "perception": 4}),
			Senses:        optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"common", "giant"},
			Cr:        "7",
			Attacks: mustJSON([]map[string]any{
				{"name": "Glaive", "to_hit": 7, "damage": "2d10+4", "damage_type": "slashing", "reach_ft": 10},
				{"name": "Claw (Oni Form Only)", "to_hit": 7, "damage": "1d8+4", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Magic Weapons", "description": "The oni's weapon attacks are magical."},
				{"name": "Regeneration", "description": "The oni regains 10 hit points at the start of its turn if it has at least 1 hit point."},
				{"name": "Innate Spellcasting", "description": "The oni's innate spellcasting ability is Charisma (spell save DC 13). The oni can innately cast the following spells, requiring no material components: At will: darkness, invisibility; 1/day each: charm person, cone of cold, gaseous form, sleep."},
				{"name": "Change Shape", "description": "The oni magically polymorphs into a Small or Medium humanoid, into a Large giant, or back into its true form. Other than its size, its statistics are the same in each form. The only equipment that is transformed is its glaive, which shrinks so that it can be wielded in humanoid form. If the oni dies, it reverts to its true form, and its glaive reverts to its normal size."},
			}),
		},
		{
			ID: "shield-guardian", Name: "Shield Guardian", Size: "Large", Type: "construct", Alignment: optStr("unaligned"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "15d10+60", HpAverage: 142,
			Speed:         mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 8, "con": 18, "int": 7, "wis": 10, "cha": 3}),
			Senses:        optJSON(map[string]any{"blindsight": 10, "darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{},
			ConditionImmunities: []string{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"},
			Languages: []string{"understands commands given in any language but can't speak"},
			Cr:        "7",
			Attacks: mustJSON([]map[string]any{
				{"name": "Fist", "to_hit": 7, "damage": "2d6+4", "damage_type": "bludgeoning", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Bound", "description": "The shield guardian is magically bound to an amulet. As long as the guardian and its amulet are on the same plane of existence, the amulet's wearer can telepathically call the guardian to travel to it, and the guardian knows the distance and direction to the amulet."},
				{"name": "Regeneration", "description": "The shield guardian regains 10 hit points at the start of its turn if it has at least 1 hit point."},
				{"name": "Shield", "description": "When a creature makes an attack against the wearer of the guardian's amulet, the guardian grants a +2 bonus to the wearer's AC if the guardian is within 5 feet of the wearer."},
				{"name": "Spell Storing", "description": "A spellcaster who wears the shield guardian's amulet can cause the guardian to store one spell of 4th level or lower. The spell has no effect when stored. When commanded to do so by the wearer or when a situation arises that was predefined by the spellcaster, the guardian casts the stored spell with any parameters set by the original caster, requiring no components."},
			}),
		},
		{
			ID: "stone-giant", Name: "Stone Giant", Size: "Huge", Type: "giant", Alignment: optStr("neutral"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "11d12+55", HpAverage: 126,
			Speed:         mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 23, "dex": 15, "con": 20, "int": 10, "wis": 12, "cha": 9}),
			SavingThrows:  optJSON(map[string]int{"dex": 5, "con": 8, "wis": 4}),
			Skills:        optJSON(map[string]int{"athletics": 12, "perception": 4}),
			Senses:        optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"giant"},
			Cr:        "7",
			Attacks: mustJSON([]map[string]any{
				{"name": "Greatclub", "to_hit": 9, "damage": "3d8+6", "damage_type": "bludgeoning", "reach_ft": 15},
				{"name": "Rock", "to_hit": 9, "damage": "4d10+6", "damage_type": "bludgeoning", "reach_ft": 60},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Stone Camouflage", "description": "The giant has advantage on Dexterity (Stealth) checks made to hide in rocky terrain."},
				{"name": "Rock Catching", "description": "If a rock or similar object is hurled at the giant, the giant can, with a successful DC 10 Dexterity saving throw, catch the missile and take no bludgeoning damage from it."},
			}),
		},
		{
			ID: "young-black-dragon", Name: "Young Black Dragon", Size: "Large", Type: "dragon", Alignment: optStr("chaotic evil"),
			Ac: 18, AcType: optStr("natural armor"), HpFormula: "15d10+45", HpAverage: 127,
			Speed:         mustJSON(map[string]int{"walk": 40, "fly": 80, "swim": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 14, "con": 17, "int": 12, "wis": 11, "cha": 15}),
			SavingThrows:  optJSON(map[string]int{"dex": 5, "con": 6, "wis": 3, "cha": 5}),
			Skills:        optJSON(map[string]int{"perception": 6, "stealth": 5}),
			DamageResistances: []string{}, DamageImmunities: []string{"acid"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Senses:    optJSON(map[string]any{"blindsight": 30, "darkvision": 120, "passive_perception": 16}),
			Languages: []string{"common", "draconic"},
			Cr:        "7",
			Attacks: mustJSON([]map[string]any{
				{"name": "Bite", "to_hit": 7, "damage": "2d10+4", "damage_type": "piercing", "reach_ft": 10},
				{"name": "Claw", "to_hit": 7, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Amphibious", "description": "The dragon can breathe air and water."},
				{"name": "Acid Breath (Recharge 5-6)", "description": "The dragon exhales acid in a 30-foot line that is 5 feet wide. Each creature in that line must make a DC 14 Dexterity saving throw, taking 49 (11d8) acid damage on a failed save, or half as much damage on a successful one."},
			}),
		},
		{
			ID: "young-copper-dragon", Name: "Young Copper Dragon", Size: "Large", Type: "dragon", Alignment: optStr("chaotic good"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "14d10+42", HpAverage: 119,
			Speed:         mustJSON(map[string]int{"walk": 40, "climb": 40, "fly": 80}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 12, "con": 17, "int": 16, "wis": 13, "cha": 15}),
			SavingThrows:  optJSON(map[string]int{"dex": 4, "con": 6, "wis": 4, "cha": 5}),
			Skills:        optJSON(map[string]int{"deception": 5, "perception": 7, "stealth": 4}),
			DamageResistances: []string{}, DamageImmunities: []string{"acid"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Senses:    optJSON(map[string]any{"blindsight": 30, "darkvision": 120, "passive_perception": 17}),
			Languages: []string{"common", "draconic"},
			Cr:        "7",
			Attacks: mustJSON([]map[string]any{
				{"name": "Bite", "to_hit": 7, "damage": "2d10+4", "damage_type": "piercing", "reach_ft": 10},
				{"name": "Claw", "to_hit": 7, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5},
			}),
			Abilities: optJSON([]map[string]any{
				{"name": "Breath Weapons (Recharge 5-6)", "description": "The dragon uses one of the following breath weapons. Acid Breath: The dragon exhales acid in a 40-foot line that is 5 feet wide. Each creature in that line must make a DC 14 Dexterity saving throw, taking 40 (9d8) acid damage on a failed save, or half as much damage on a successful one. Slowing Breath: The dragon exhales gas in a 30-foot cone. Each creature in that area must succeed on a DC 14 Constitution saving throw. On a failed save, the creature can't use reactions, its speed is halved, and it can't make more than one attack on its turn. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself with a successful save."},
			}),
		},
	}
}
