package refdata

// srdCreaturesCR3to5 returns SRD creatures with CR 3-5.
func srdCreaturesCR3to5() []cr {
	return []cr{
		// ── CR 3 ──
		{
			ID: "basilisk", Name: "Basilisk", Size: "Medium", Type: "monstrosity", Alignment: optStr("unaligned"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "8d8+16", HpAverage: 52,
			Speed: mustJSON(map[string]int{"walk": 20}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 8, "con": 15, "int": 2, "wis": 8, "cha": 7}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 9}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 5, "damage": "2d6+3", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Petrifying Gaze", "description": "If a creature starts its turn within 30 feet of the basilisk and the two of them can see each other, the basilisk can force the creature to make a DC 12 Constitution saving throw if the basilisk isn't incapacitated. On a failed save, the creature magically begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic."}}),
		},
		{
			ID: "bearded-devil", Name: "Bearded Devil", Size: "Medium", Type: "fiend", Alignment: optStr("lawful evil"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "8d8+16", HpAverage: 52,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 15, "con": 15, "int": 9, "wis": 11, "cha": 11}),
			SavingThrows: optJSON(map[string]int{"str": 5, "con": 4, "wis": 2}),
			Senses: optJSON(map[string]any{"darkvision": 120, "passive_perception": 10}),
			DamageResistances: []string{"cold", "bludgeoning, piercing, and slashing from nonmagical attacks that aren't silvered"}, DamageImmunities: []string{"fire", "poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"poisoned"},
			Languages: []string{"Infernal", "telepathy 120 ft."},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Beard", "to_hit": 5, "damage": "1d8+2", "damage_type": "piercing", "reach_ft": 5}, {"name": "Glaive", "to_hit": 5, "damage": "1d10+3", "damage_type": "slashing", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Devil's Sight", "description": "Magical darkness doesn't impede the devil's darkvision."}, {"name": "Magic Resistance", "description": "The devil has advantage on saving throws against spells and other magical effects."}, {"name": "Steadfast", "description": "The devil can't be frightened while it can see an allied creature within 30 feet of it."}}),
		},
		{
			ID: "blue-dragon-wyrmling", Name: "Blue Dragon Wyrmling", Size: "Medium", Type: "dragon", Alignment: optStr("lawful evil"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "8d8+16", HpAverage: 52,
			Speed: mustJSON(map[string]int{"walk": 30, "burrow": 15, "fly": 60}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 10, "con": 15, "int": 12, "wis": 11, "cha": 15}),
			SavingThrows: optJSON(map[string]int{"dex": 2, "con": 4, "wis": 2, "cha": 4}),
			Skills: optJSON(map[string]int{"perception": 4, "stealth": 2}),
			Senses: optJSON(map[string]any{"blindsight": 10, "darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{"lightning"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Draconic"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 5, "damage": "1d10+3", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Lightning Breath (Recharge 5-6)", "description": "The dragon exhales lightning in a 30-foot line that is 5 feet wide. Each creature in that line must make a DC 12 Dexterity saving throw, taking 22 (4d10) lightning damage on a failed save, or half as much damage on a successful one."}}),
		},
		{
			ID: "displacer-beast", Name: "Displacer Beast", Size: "Large", Type: "monstrosity", Alignment: optStr("lawful evil"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "10d10+30", HpAverage: 85,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 15, "con": 16, "int": 6, "wis": 12, "cha": 8}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 11}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Tentacle", "to_hit": 6, "damage": "1d6+4", "damage_type": "bludgeoning", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Avoidance", "description": "If the displacer beast is subjected to an effect that allows it to make a saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throw, and only half damage if it fails."}, {"name": "Displacement", "description": "The displacer beast projects a magical illusion that makes it appear to be standing near its actual location, causing attack rolls against it to have disadvantage. If it is hit by an attack, this trait is disrupted until the end of its next turn. This trait is also disrupted while the displacer beast is incapacitated or has a speed of 0."}}),
		},
		{
			ID: "doppelganger", Name: "Doppelganger", Size: "Medium", Type: "monstrosity", Alignment: optStr("neutral"),
			Ac: 14, HpFormula: "8d8+16", HpAverage: 52,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 11, "dex": 18, "con": 14, "int": 11, "wis": 12, "cha": 14}),
			Skills: optJSON(map[string]int{"deception": 6, "insight": 3}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 11}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed"},
			Languages: []string{"Common"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Slam", "to_hit": 6, "damage": "1d6+4", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Shapechanger", "description": "The doppelganger can use its action to polymorph into a Small or Medium humanoid it has seen, or back into its true form. Its statistics, other than its size, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies."}, {"name": "Ambusher", "description": "The doppelganger has advantage on attack rolls against any creature it has surprised."}, {"name": "Surprise Attack", "description": "If the doppelganger surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 10 (3d6) damage from the attack."}, {"name": "Read Thoughts", "description": "The doppelganger magically reads the surface thoughts of one creature within 60 feet of it. The effect can penetrate barriers, but 3 feet of wood or dirt, 2 feet of stone, 2 inches of metal, or a thin sheet of lead blocks it. While the target is in range, the doppelganger can continue reading its thoughts, as long as the doppelganger's concentration isn't broken (as if concentrating on a spell)."}}),
		},
		{
			ID: "giant-scorpion", Name: "Giant Scorpion", Size: "Large", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "7d10+14", HpAverage: 52,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 15, "dex": 13, "con": 15, "int": 1, "wis": 9, "cha": 3}),
			Senses: optJSON(map[string]any{"blindsight": 60, "passive_perception": 9}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Claw", "to_hit": 4, "damage": "1d8+2", "damage_type": "bludgeoning", "reach_ft": 5}, {"name": "Sting", "to_hit": 4, "damage": "1d10+2", "damage_type": "piercing", "reach_ft": 5}}),
		},
		{
			ID: "green-hag", Name: "Green Hag", Size: "Medium", Type: "fey", Alignment: optStr("neutral evil"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "11d8+33", HpAverage: 82,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 12, "con": 16, "int": 13, "wis": 14, "cha": 14}),
			Skills: optJSON(map[string]int{"arcana": 3, "deception": 4, "perception": 4, "stealth": 3}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common", "Draconic", "Sylvan"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Claws", "to_hit": 6, "damage": "2d8+4", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Amphibious", "description": "The hag can breathe air and water."}, {"name": "Innate Spellcasting", "description": "The hag's innate spellcasting ability is Charisma (spell save DC 12). She can innately cast the following spells, requiring no material components: At will: dancing lights, minor illusion, vicious mockery."}, {"name": "Mimicry", "description": "The hag can mimic animal sounds and humanoid voices. A creature that hears the sounds can tell they are imitations with a successful DC 14 Wisdom (Insight) check."}, {"name": "Invisible Passage", "description": "The hag magically turns invisible until she attacks or casts a spell, or until her concentration ends (as if concentrating on a spell). While invisible, she leaves no physical evidence of her passage, so she can be tracked only by magic. Any equipment she wears or carries is invisible with her."}}),
		},
		{
			ID: "hell-hound", Name: "Hell Hound", Size: "Medium", Type: "fiend", Alignment: optStr("lawful evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "7d8+14", HpAverage: 45,
			Speed: mustJSON(map[string]int{"walk": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 12, "con": 14, "int": 6, "wis": 13, "cha": 6}),
			Skills: optJSON(map[string]int{"perception": 5}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 15}),
			DamageResistances: []string{}, DamageImmunities: []string{"fire"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"understands Infernal but can't speak it"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 5, "damage": "1d8+3", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Keen Hearing and Smell", "description": "The hound has advantage on Wisdom (Perception) checks that rely on hearing or smell."}, {"name": "Pack Tactics", "description": "The hound has advantage on an attack roll against a creature if at least one of the hound's allies is within 5 feet of the creature and the ally isn't incapacitated."}, {"name": "Fire Breath (Recharge 5-6)", "description": "The hound exhales fire in a 15-foot cone. Each creature in that area must make a DC 12 Dexterity saving throw, taking 21 (6d6) fire damage on a failed save, or half as much damage on a successful one."}}),
		},
		{
			ID: "hook-horror", Name: "Hook Horror", Size: "Large", Type: "monstrosity", Alignment: optStr("neutral"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "10d10+20", HpAverage: 75,
			Speed: mustJSON(map[string]int{"walk": 30, "climb": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 10, "con": 15, "int": 6, "wis": 12, "cha": 7}),
			Skills: optJSON(map[string]int{"perception": 3}),
			Senses: optJSON(map[string]any{"blindsight": 60, "darkvision": 120, "passive_perception": 13}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Hook Horror"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Hook", "to_hit": 6, "damage": "2d6+4", "damage_type": "piercing", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Echolocation", "description": "The hook horror can't use its blindsight while deafened."}, {"name": "Keen Hearing", "description": "The hook horror has advantage on Wisdom (Perception) checks that rely on hearing."}}),
		},
		{
			ID: "killer-whale", Name: "Killer Whale", Size: "Huge", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 12, AcType: optStr("natural armor"), HpFormula: "12d12+12", HpAverage: 90,
			Speed: mustJSON(map[string]int{"swim": 60}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 10, "con": 13, "int": 3, "wis": 12, "cha": 7}),
			Skills: optJSON(map[string]int{"perception": 3}),
			Senses: optJSON(map[string]any{"blindsight": 120, "passive_perception": 13}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 6, "damage": "5d6+4", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Echolocation", "description": "The whale can't use its blindsight while deafened."}, {"name": "Hold Breath", "description": "The whale can hold its breath for 30 minutes."}, {"name": "Keen Hearing", "description": "The whale has advantage on Wisdom (Perception) checks that rely on hearing."}}),
		},
		{
			ID: "knight", Name: "Knight", Size: "Medium", Type: "humanoid", Alignment: optStr("any alignment"),
			Ac: 18, AcType: optStr("plate"), HpFormula: "8d8+16", HpAverage: 52,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 11, "con": 14, "int": 11, "wis": 11, "cha": 15}),
			SavingThrows: optJSON(map[string]int{"con": 4, "wis": 2}),
			Senses: optJSON(map[string]any{"passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"any one language"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Greatsword", "to_hit": 5, "damage": "2d6+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Heavy Crossbow", "to_hit": 2, "damage": "1d10", "damage_type": "piercing", "reach_ft": 100}}),
			Abilities: optJSON([]map[string]any{{"name": "Brave", "description": "The knight has advantage on saving throws against being frightened."}, {"name": "Leadership (Recharges after a Short or Long Rest)", "description": "For 1 minute, the knight can utter a special command or warning whenever a nonhostile creature that it can see within 30 feet of it makes an attack roll or a saving throw. The creature can add a d4 to its roll provided it can hear and understand the knight. A creature can benefit from only one Leadership die at a time. This effect ends if the knight is incapacitated."}}),
		},
		{
			ID: "manticore", Name: "Manticore", Size: "Large", Type: "monstrosity", Alignment: optStr("lawful evil"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "8d10+24", HpAverage: 68,
			Speed: mustJSON(map[string]int{"walk": 30, "fly": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 16, "con": 17, "int": 7, "wis": 12, "cha": 8}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 11}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 5, "damage": "1d8+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claw", "to_hit": 5, "damage": "1d6+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Tail Spike", "to_hit": 5, "damage": "1d8+3", "damage_type": "piercing", "reach_ft": 100}}),
			Abilities: optJSON([]map[string]any{{"name": "Tail Spike Regrowth", "description": "The manticore has twenty-four tail spikes. Used spikes regrow when the manticore finishes a long rest."}}),
		},
		{
			ID: "minotaur", Name: "Minotaur", Size: "Large", Type: "monstrosity", Alignment: optStr("chaotic evil"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "9d10+27", HpAverage: 76,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 11, "con": 16, "int": 6, "wis": 16, "cha": 9}),
			Skills: optJSON(map[string]int{"perception": 7}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 17}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Abyssal"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Greataxe", "to_hit": 6, "damage": "2d12+4", "damage_type": "slashing", "reach_ft": 5}, {"name": "Gore", "to_hit": 6, "damage": "2d8+4", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Charge", "description": "If the minotaur moves at least 10 feet straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be pushed up to 10 feet away and knocked prone."}, {"name": "Labyrinthine Recall", "description": "The minotaur can perfectly recall any path it has traveled."}, {"name": "Reckless", "description": "At the start of its turn, the minotaur can gain advantage on all melee weapon attack rolls it makes during that turn, but attack rolls against it have advantage until the start of its next turn."}}),
		},
		{
			ID: "mummy", Name: "Mummy", Size: "Medium", Type: "undead", Alignment: optStr("lawful evil"),
			Ac: 11, AcType: optStr("natural armor"), HpFormula: "9d8+18", HpAverage: 58,
			Speed: mustJSON(map[string]int{"walk": 20}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 8, "con": 15, "int": 6, "wis": 10, "cha": 12}),
			SavingThrows: optJSON(map[string]int{"wis": 2}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{"bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"necrotic", "poison"}, DamageVulnerabilities: []string{"fire"}, ConditionImmunities: []string{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"},
			Languages: []string{"the languages it knew in life"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Rotting Fist", "to_hit": 5, "damage": "2d6+3", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Dreadful Glare", "description": "The mummy targets one creature it can see within 60 feet of it. If the target can see the mummy, it must succeed on a DC 11 Wisdom saving throw against this magic or become frightened until the end of the mummy's next turn. If the target fails the saving throw by 5 or more, it is also paralyzed for the same duration. A target that succeeds on the saving throw is immune to the Dreadful Glare of all mummies (but not mummy lords) for the next 24 hours."}}),
		},
		{
			ID: "nightmare", Name: "Nightmare", Size: "Large", Type: "fiend", Alignment: optStr("neutral evil"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "8d10+24", HpAverage: 68,
			Speed: mustJSON(map[string]int{"walk": 60, "fly": 90}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 15, "con": 16, "int": 10, "wis": 13, "cha": 15}),
			Senses: optJSON(map[string]any{"passive_perception": 11}),
			DamageResistances: []string{}, DamageImmunities: []string{"fire"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"understands Abyssal, Common, and Infernal but can't speak"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Hooves", "to_hit": 6, "damage": "2d8+4", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Confer Fire Resistance", "description": "The nightmare can grant resistance to fire damage to anyone riding it."}, {"name": "Illumination", "description": "The nightmare sheds bright light in a 10-foot radius and dim light for an additional 10 feet."}, {"name": "Ethereal Stride", "description": "The nightmare and up to three willing creatures within 5 feet of it magically enter the Ethereal Plane from the Material Plane, or vice versa."}}),
		},
		{
			ID: "owlbear", Name: "Owlbear", Size: "Large", Type: "monstrosity", Alignment: optStr("unaligned"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "7d10+21", HpAverage: 59,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 20, "dex": 12, "con": 17, "int": 3, "wis": 12, "cha": 7}),
			Skills: optJSON(map[string]int{"perception": 3}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 13}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Beak", "to_hit": 7, "damage": "1d10+5", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claws", "to_hit": 7, "damage": "2d8+5", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Keen Sight and Smell", "description": "The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell."}}),
		},
		{
			ID: "phase-spider", Name: "Phase Spider", Size: "Large", Type: "monstrosity", Alignment: optStr("unaligned"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "5d10+5", HpAverage: 32,
			Speed: mustJSON(map[string]int{"walk": 30, "climb": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 15, "dex": 15, "con": 12, "int": 6, "wis": 10, "cha": 6}),
			Skills: optJSON(map[string]int{"stealth": 6}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 4, "damage": "1d10+2", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Ethereal Jaunt", "description": "As a bonus action, the spider can magically shift from the Material Plane to the Ethereal Plane, or vice versa."}, {"name": "Spider Climb", "description": "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."}, {"name": "Web Walker", "description": "The spider ignores movement restrictions caused by webbing."}}),
		},
		{
			ID: "spectator", Name: "Spectator", Size: "Medium", Type: "aberration", Alignment: optStr("lawful neutral"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "6d8+12", HpAverage: 39,
			Speed: mustJSON(map[string]int{"fly": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 8, "dex": 14, "con": 14, "int": 13, "wis": 14, "cha": 11}),
			Skills: optJSON(map[string]int{"perception": 6}),
			Senses: optJSON(map[string]any{"darkvision": 120, "passive_perception": 16}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"prone"},
			Languages: []string{"Deep Speech", "Undercommon", "telepathy 120 ft."},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 1, "damage": "2d6-1", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Eye Rays", "description": "The spectator shoots up to two of its eye rays at one or two creatures it can see within 90 feet of it, choosing from Confusion Ray, Paralyzing Ray, Fear Ray, and Wounding Ray."}}),
		},
		{
			ID: "veteran", Name: "Veteran", Size: "Medium", Type: "humanoid", Alignment: optStr("any alignment"),
			Ac: 17, AcType: optStr("splint"), HpFormula: "9d8+18", HpAverage: 58,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 13, "con": 14, "int": 10, "wis": 11, "cha": 10}),
			Skills: optJSON(map[string]int{"athletics": 5, "perception": 2}),
			Senses: optJSON(map[string]any{"passive_perception": 12}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"any one language"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Longsword", "to_hit": 5, "damage": "1d8+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Shortsword", "to_hit": 5, "damage": "1d6+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Heavy Crossbow", "to_hit": 3, "damage": "1d10+1", "damage_type": "piercing", "reach_ft": 100}}),
		},
		{
			ID: "werewolf", Name: "Werewolf", Size: "Medium", Type: "humanoid", Alignment: optStr("chaotic evil"),
			Ac: 12, AcType: optStr("natural armor in hybrid/wolf form, 11 in humanoid form"), HpFormula: "9d8+18", HpAverage: 58,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 15, "dex": 13, "con": 14, "int": 10, "wis": 11, "cha": 10}),
			Skills: optJSON(map[string]int{"perception": 4, "stealth": 3}),
			Senses: optJSON(map[string]any{"passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{"bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite (Wolf or Hybrid Form Only)", "to_hit": 4, "damage": "1d8+2", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claws (Hybrid Form Only)", "to_hit": 4, "damage": "2d4+2", "damage_type": "slashing", "reach_ft": 5}, {"name": "Spear (Humanoid Form Only)", "to_hit": 4, "damage": "1d6+2", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Shapechanger", "description": "The werewolf can use its action to polymorph into a wolf-humanoid hybrid or into a wolf, or back into its true form, which is humanoid. Its statistics, other than its AC, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies."}, {"name": "Keen Hearing and Smell", "description": "The werewolf has advantage on Wisdom (Perception) checks that rely on hearing or smell."}}),
		},
		{
			ID: "winter-wolf", Name: "Winter Wolf", Size: "Large", Type: "monstrosity", Alignment: optStr("neutral evil"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "10d10+20", HpAverage: 75,
			Speed: mustJSON(map[string]int{"walk": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 13, "con": 14, "int": 7, "wis": 12, "cha": 8}),
			Skills: optJSON(map[string]int{"perception": 5, "stealth": 3}),
			Senses: optJSON(map[string]any{"passive_perception": 15}),
			DamageResistances: []string{}, DamageImmunities: []string{"cold"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common", "Giant", "Winter Wolf"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 6, "damage": "2d6+4", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Keen Hearing and Smell", "description": "The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell."}, {"name": "Pack Tactics", "description": "The wolf has advantage on an attack roll against a creature if at least one of the wolf's allies is within 5 feet of the creature and the ally isn't incapacitated."}, {"name": "Snow Camouflage", "description": "The wolf has advantage on Dexterity (Stealth) checks made to hide in snowy terrain."}, {"name": "Cold Breath (Recharge 5-6)", "description": "The wolf exhales a blast of freezing wind in a 15-foot cone. Each creature in that area must make a DC 12 Dexterity saving throw, taking 18 (4d8) cold damage on a failed save, or half as much damage on a successful one."}}),
		},
		{
			ID: "yeti", Name: "Yeti", Size: "Large", Type: "monstrosity", Alignment: optStr("chaotic evil"),
			Ac: 12, AcType: optStr("natural armor"), HpFormula: "6d10+18", HpAverage: 51,
			Speed: mustJSON(map[string]int{"walk": 40, "climb": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 13, "con": 16, "int": 8, "wis": 12, "cha": 7}),
			Skills: optJSON(map[string]int{"perception": 3, "stealth": 3}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 13}),
			DamageResistances: []string{}, DamageImmunities: []string{"cold"}, DamageVulnerabilities: []string{"fire"}, ConditionImmunities: []string{},
			Languages: []string{"Yeti"},
			Cr: "3",
			Attacks: mustJSON([]map[string]any{{"name": "Claw", "to_hit": 6, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Fear of Fire", "description": "If the yeti takes fire damage, it has disadvantage on attack rolls and ability checks until the end of its next turn."}, {"name": "Keen Smell", "description": "The yeti has advantage on Wisdom (Perception) checks that rely on smell."}, {"name": "Snow Camouflage", "description": "The yeti has advantage on Dexterity (Stealth) checks made to hide in snowy terrain."}, {"name": "Chilling Gaze", "description": "The yeti targets one creature it can see within 30 feet of it. If the target can see the yeti, the target must succeed on a DC 13 Constitution saving throw against this magic or take 10 (3d6) cold damage and then be paralyzed for 1 minute, unless it is immune to cold damage. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success."}}),
		},
		// ── CR 4 ──
		{
			ID: "banshee", Name: "Banshee", Size: "Medium", Type: "undead", Alignment: optStr("chaotic evil"),
			Ac: 12, HpFormula: "13d8", HpAverage: 58,
			Speed: mustJSON(map[string]int{"fly": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 1, "dex": 14, "con": 10, "int": 12, "wis": 11, "cha": 17}),
			SavingThrows: optJSON(map[string]int{"wis": 2, "cha": 5}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{"acid", "fire", "lightning", "thunder", "bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"cold", "necrotic", "poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"},
			Languages: []string{"Common", "Elvish"},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Corrupting Touch", "to_hit": 4, "damage": "3d6+2", "damage_type": "necrotic", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Detect Life", "description": "The banshee can magically sense the presence of living creatures up to 5 miles away that aren't undead or constructs. She knows the general direction they're in but not their exact locations."}, {"name": "Incorporeal Movement", "description": "The banshee can move through other creatures and objects as if they were difficult terrain. She takes 5 (1d10) force damage if she ends her turn inside an object."}, {"name": "Wail (1/Day)", "description": "The banshee releases a mournful wail, provided that she isn't in sunlight. This wail has no effect on constructs and undead. All other creatures within 30 feet of her that can hear her must make a DC 13 Constitution saving throw. On a failure, a creature drops to 0 hit points. On a success, a creature takes 10 (3d6) psychic damage."}}),
		},
		{
			ID: "black-pudding", Name: "Black Pudding", Size: "Large", Type: "ooze", Alignment: optStr("unaligned"),
			Ac: 7, HpFormula: "10d10+30", HpAverage: 85,
			Speed: mustJSON(map[string]int{"walk": 20, "climb": 20}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 5, "con": 16, "int": 1, "wis": 6, "cha": 1}),
			Senses: optJSON(map[string]any{"blindsight": 60, "passive_perception": 8}),
			DamageResistances: []string{}, DamageImmunities: []string{"acid", "cold", "lightning", "slashing"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"},
			Languages: []string{},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Pseudopod", "to_hit": 5, "damage": "1d6+3", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Amorphous", "description": "The pudding can move through a space as narrow as 1 inch wide without squeezing."}, {"name": "Corrosive Form", "description": "A creature that touches the pudding or hits it with a melee attack while within 5 feet of it takes 4 (1d8) acid damage. Any nonmagical weapon made of metal or wood that hits the pudding corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls. If its penalty drops to -5, the weapon is destroyed. Nonmagical ammunition made of metal or wood that hits the pudding is destroyed after dealing damage."}, {"name": "Spider Climb", "description": "The pudding can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."}}),
		},
		{
			ID: "couatl", Name: "Couatl", Size: "Medium", Type: "celestial", Alignment: optStr("lawful good"),
			Ac: 19, AcType: optStr("natural armor"), HpFormula: "13d8+39", HpAverage: 97,
			Speed: mustJSON(map[string]int{"walk": 30, "fly": 90}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 20, "con": 17, "int": 18, "wis": 20, "cha": 18}),
			SavingThrows: optJSON(map[string]int{"con": 5, "wis": 7, "cha": 6}),
			Senses: optJSON(map[string]any{"truesight": 120, "passive_perception": 15}),
			DamageResistances: []string{"radiant"}, DamageImmunities: []string{"psychic", "bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"all", "telepathy 120 ft."},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 8, "damage": "1d6+5", "damage_type": "piercing", "reach_ft": 5}, {"name": "Constrict", "to_hit": 6, "damage": "2d6+3", "damage_type": "bludgeoning", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Magic Resistance", "description": "The couatl has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "The couatl's weapon attacks are magical."}, {"name": "Shielded Mind", "description": "The couatl is immune to scrying and to any effect that would sense its emotions, read its thoughts, or detect its location."}}),
		},
		{
			ID: "elephant", Name: "Elephant", Size: "Huge", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 12, AcType: optStr("natural armor"), HpFormula: "8d12+24", HpAverage: 76,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 22, "dex": 9, "con": 17, "int": 3, "wis": 11, "cha": 6}),
			Senses: optJSON(map[string]any{"passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Gore", "to_hit": 8, "damage": "3d8+6", "damage_type": "piercing", "reach_ft": 5}, {"name": "Stomp", "to_hit": 8, "damage": "3d10+6", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Trampling Charge", "description": "If the elephant moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the elephant can make one stomp attack against it as a bonus action."}}),
		},
		{
			ID: "ettin", Name: "Ettin", Size: "Large", Type: "giant", Alignment: optStr("chaotic evil"),
			Ac: 12, AcType: optStr("natural armor"), HpFormula: "10d10+30", HpAverage: 85,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 21, "dex": 8, "con": 17, "int": 6, "wis": 10, "cha": 8}),
			Skills: optJSON(map[string]int{"perception": 4}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Giant", "Orc"},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Battleaxe", "to_hit": 7, "damage": "2d8+5", "damage_type": "slashing", "reach_ft": 5}, {"name": "Morningstar", "to_hit": 7, "damage": "2d8+5", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Two Heads", "description": "The ettin has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious."}, {"name": "Wakeful", "description": "When one of the ettin's heads is asleep, its other head is awake."}}),
		},
		{
			ID: "ghost", Name: "Ghost", Size: "Medium", Type: "undead", Alignment: optStr("any alignment"),
			Ac: 11, HpFormula: "10d8", HpAverage: 45,
			Speed: mustJSON(map[string]int{"fly": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 7, "dex": 13, "con": 10, "int": 10, "wis": 12, "cha": 17}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 11}),
			DamageResistances: []string{"acid", "fire", "lightning", "thunder", "bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"cold", "necrotic", "poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"},
			Languages: []string{"any languages it knew in life"},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Withering Touch", "to_hit": 5, "damage": "4d6+3", "damage_type": "necrotic", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Ethereal Sight", "description": "The ghost can see 60 feet into the Ethereal Plane when it is on the Material Plane, and vice versa."}, {"name": "Incorporeal Movement", "description": "The ghost can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object."}, {"name": "Horrifying Visage", "description": "Each non-undead creature within 60 feet of the ghost that can see it must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute. If the save fails by 5 or more, the target also ages 1d4 x 10 years. A frightened target can repeat the saving throw at the end of each of its turns, ending the frightened condition on itself on a success."}, {"name": "Possession (Recharge 6)", "description": "One humanoid that the ghost can see within 5 feet of it must succeed on a DC 13 Charisma saving throw or be possessed by the ghost; the ghost then disappears, and the target is incapacitated and loses control of its body. The ghost now controls the body but doesn't deprive the target of awareness."}}),
		},
		{
			ID: "lamia", Name: "Lamia", Size: "Large", Type: "monstrosity", Alignment: optStr("chaotic evil"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "13d10+26", HpAverage: 97,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 13, "con": 15, "int": 14, "wis": 15, "cha": 16}),
			Skills: optJSON(map[string]int{"deception": 7, "insight": 4, "stealth": 3}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 12}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Abyssal", "Common"},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Claws", "to_hit": 5, "damage": "2d10+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Dagger", "to_hit": 5, "damage": "1d4+3", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Innate Spellcasting", "description": "The lamia's innate spellcasting ability is Charisma (spell save DC 13). It can innately cast the following spells, requiring no material components. At will: disguise self (any humanoid form), major image. 3/day each: charm person, mirror image, scrying, suggestion. 1/day: geas."}, {"name": "Intoxicating Touch", "description": "The lamia magically touches one creature. The target must succeed on a DC 13 Wisdom saving throw or be magically cursed for 1 hour. Until the curse ends, the target has disadvantage on Wisdom saving throws and all ability checks."}}),
		},
		{
			ID: "succubus-incubus", Name: "Succubus/Incubus", Size: "Medium", Type: "fiend", Alignment: optStr("neutral evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "12d8+12", HpAverage: 66,
			Speed: mustJSON(map[string]int{"walk": 30, "fly": 60}),
			AbilityScores: mustJSON(map[string]int{"str": 8, "dex": 17, "con": 13, "int": 15, "wis": 12, "cha": 20}),
			Skills: optJSON(map[string]int{"deception": 9, "insight": 5, "perception": 5, "persuasion": 9, "stealth": 7}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 15}),
			DamageResistances: []string{"cold", "fire", "lightning", "poison", "bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Abyssal", "Common", "Infernal", "telepathy 60 ft."},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Claw (Fiend Form Only)", "to_hit": 5, "damage": "1d6+3", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Telepathic Bond", "description": "The fiend ignores the range restriction on its telepathy when communicating with a creature it has charmed. The two don't even need to be on the same plane of existence."}, {"name": "Shapechanger", "description": "The fiend can use its action to polymorph into a Small or Medium humanoid, or back into its true form. Without wings, the fiend loses its flying speed. Other than its size and speed, its statistics are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies."}, {"name": "Draining Kiss", "description": "The fiend kisses a creature charmed by it or a willing creature. The target must make a DC 15 Constitution saving throw against this magic, taking 32 (5d10+5) psychic damage on a failed save, or half as much damage on a successful one. The target's hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0."}, {"name": "Charm", "description": "One humanoid the fiend can see within 30 feet of it must succeed on a DC 15 Wisdom saving throw or be magically charmed for 1 day. The charmed target obeys the fiend's verbal or telepathic commands."}}),
		},
		{
			ID: "wereboar", Name: "Wereboar", Size: "Medium", Type: "humanoid", Alignment: optStr("neutral evil"),
			Ac: 11, AcType: optStr("natural armor in boar/hybrid form, 10 in humanoid form"), HpFormula: "9d10+27", HpAverage: 78,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 10, "con": 15, "int": 10, "wis": 11, "cha": 8}),
			Skills: optJSON(map[string]int{"perception": 2}),
			Senses: optJSON(map[string]any{"passive_perception": 12}),
			DamageResistances: []string{}, DamageImmunities: []string{"bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common"},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Tusks (Boar or Hybrid Form Only)", "to_hit": 5, "damage": "2d6+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Maul (Humanoid or Hybrid Form Only)", "to_hit": 5, "damage": "2d6+3", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Shapechanger", "description": "The wereboar can use its action to polymorph into a boar-humanoid hybrid or into a boar, or back into its true form, which is humanoid. Its statistics, other than its AC, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies."}, {"name": "Charge (Boar or Hybrid Form Only)", "description": "If the wereboar moves at least 15 feet straight toward a target and then hits it with its tusks on the same turn, the target takes an extra 7 (2d6) slashing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone."}, {"name": "Relentless (Recharges after a Short or Long Rest)", "description": "If the wereboar takes 14 damage or less that would reduce it to 0 hit points, it is reduced to 1 hit point instead."}}),
		},
		{
			ID: "weretiger", Name: "Weretiger", Size: "Medium", Type: "humanoid", Alignment: optStr("neutral"),
			Ac: 12, HpFormula: "16d8+48", HpAverage: 120,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 15, "con": 16, "int": 10, "wis": 13, "cha": 11}),
			Skills: optJSON(map[string]int{"perception": 5, "stealth": 4}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 15}),
			DamageResistances: []string{}, DamageImmunities: []string{"bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common"},
			Cr: "4",
			Attacks: mustJSON([]map[string]any{{"name": "Bite (Tiger or Hybrid Form Only)", "to_hit": 5, "damage": "1d10+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claw (Tiger or Hybrid Form Only)", "to_hit": 5, "damage": "1d8+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Scimitar (Humanoid or Hybrid Form Only)", "to_hit": 5, "damage": "1d6+3", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Shapechanger", "description": "The weretiger can use its action to polymorph into a tiger-humanoid hybrid or into a tiger, or back into its true form, which is humanoid. Its statistics, other than its size, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies."}, {"name": "Keen Hearing and Smell", "description": "The weretiger has advantage on Wisdom (Perception) checks that rely on hearing or smell."}, {"name": "Pounce (Tiger or Hybrid Form Only)", "description": "If the weretiger moves at least 15 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the weretiger can make one bite attack against it as a bonus action."}}),
		},
		// ── CR 5 ──
		{
			ID: "air-elemental", Name: "Air Elemental", Size: "Large", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 15, HpFormula: "12d10+24", HpAverage: 90,
			Speed: mustJSON(map[string]int{"fly": 90}),
			AbilityScores: mustJSON(map[string]int{"str": 14, "dex": 20, "con": 14, "int": 6, "wis": 10, "cha": 6}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{"lightning", "thunder", "bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"},
			Languages: []string{"Auran"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Slam", "to_hit": 8, "damage": "2d8+5", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Air Form", "description": "The elemental can enter a hostile creature's space and stop there. It can move through a space as narrow as 1 inch wide without squeezing."}, {"name": "Whirlwind (Recharge 4-6)", "description": "Each creature in the elemental's space must make a DC 13 Strength saving throw. On a failure, a target takes 15 (3d8+2) bludgeoning damage and is flung up 20 feet away from the elemental in a random direction and knocked prone."}}),
		},
		{
			ID: "barbed-devil", Name: "Barbed Devil", Size: "Medium", Type: "fiend", Alignment: optStr("lawful evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "13d8+52", HpAverage: 110,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 17, "con": 18, "int": 12, "wis": 14, "cha": 14}),
			SavingThrows: optJSON(map[string]int{"str": 6, "con": 7, "wis": 5, "cha": 5}),
			Skills: optJSON(map[string]int{"deception": 5, "insight": 5, "perception": 8}),
			Senses: optJSON(map[string]any{"darkvision": 120, "passive_perception": 18}),
			DamageResistances: []string{"cold", "bludgeoning, piercing, and slashing from nonmagical attacks that aren't silvered"}, DamageImmunities: []string{"fire", "poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"poisoned"},
			Languages: []string{"Infernal", "telepathy 120 ft."},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Claw", "to_hit": 6, "damage": "1d6+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Tail", "to_hit": 6, "damage": "2d6+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Hurl Flame", "to_hit": 5, "damage": "3d6", "damage_type": "fire", "reach_ft": 150}}),
			Abilities: optJSON([]map[string]any{{"name": "Barbed Hide", "description": "At the start of each of its turns, the barbed devil deals 5 (1d10) piercing damage to any creature grappling it."}, {"name": "Devil's Sight", "description": "Magical darkness doesn't impede the devil's darkvision."}, {"name": "Magic Resistance", "description": "The devil has advantage on saving throws against spells and other magical effects."}}),
		},
		{
			ID: "beholder-zombie", Name: "Beholder Zombie", Size: "Large", Type: "undead", Alignment: optStr("neutral evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "11d10+33", HpAverage: 93,
			Speed: mustJSON(map[string]int{"fly": 20}),
			AbilityScores: mustJSON(map[string]int{"str": 10, "dex": 8, "con": 16, "int": 3, "wis": 8, "cha": 5}),
			SavingThrows: optJSON(map[string]int{"wis": 2}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 9}),
			DamageResistances: []string{}, DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"poisoned", "prone"},
			Languages: []string{"understands Deep Speech and Undercommon but can't speak"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 3, "damage": "4d6", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Undead Fortitude", "description": "If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead."}, {"name": "Eye Rays", "description": "The zombie uses a random eye ray, choosing from Paralyzing Ray, Fear Ray, Enervation Ray, and Disintegration Ray."}}),
		},
		{
			ID: "bulette", Name: "Bulette", Size: "Large", Type: "monstrosity", Alignment: optStr("unaligned"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "9d10+45", HpAverage: 94,
			Speed: mustJSON(map[string]int{"walk": 40, "burrow": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 11, "con": 21, "int": 2, "wis": 10, "cha": 5}),
			Skills: optJSON(map[string]int{"perception": 6}),
			Senses: optJSON(map[string]any{"darkvision": 60, "tremorsense": 60, "passive_perception": 16}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 7, "damage": "4d12+4", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Standing Leap", "description": "The bulette's long jump is up to 30 feet and its high jump is up to 15 feet, with or without a running start."}, {"name": "Deadly Leap", "description": "If the bulette jumps at least 15 feet as part of its movement, it can then use this action to land on its feet in a space that contains one or more other creatures. Each of those creatures must succeed on a DC 16 Strength or Dexterity saving throw (target's choice) or be knocked prone and take 14 (3d6+4) bludgeoning damage plus 14 (3d6+4) slashing damage. On a successful save, the creature takes only half the damage, isn't knocked prone, and is pushed 5 feet out of the bulette's space."}}),
		},
		{
			ID: "earth-elemental", Name: "Earth Elemental", Size: "Large", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "12d10+60", HpAverage: 126,
			Speed: mustJSON(map[string]int{"walk": 30, "burrow": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 20, "dex": 8, "con": 20, "int": 5, "wis": 10, "cha": 5}),
			Senses: optJSON(map[string]any{"darkvision": 60, "tremorsense": 60, "passive_perception": 10}),
			DamageResistances: []string{"bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{"thunder"}, ConditionImmunities: []string{"exhaustion", "paralyzed", "petrified", "poisoned", "unconscious"},
			Languages: []string{"Terran"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Slam", "to_hit": 8, "damage": "2d8+5", "damage_type": "bludgeoning", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Earth Glide", "description": "The elemental can burrow through nonmagical, unworked earth and stone. While doing so, the elemental doesn't disturb the material it moves through."}, {"name": "Siege Monster", "description": "The elemental deals double damage to objects and structures."}}),
		},
		{
			ID: "fire-elemental", Name: "Fire Elemental", Size: "Large", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 13, HpFormula: "12d10+36", HpAverage: 102,
			Speed: mustJSON(map[string]int{"walk": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 10, "dex": 17, "con": 16, "int": 6, "wis": 10, "cha": 7}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{"bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"fire", "poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"},
			Languages: []string{"Ignan"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Touch", "to_hit": 6, "damage": "2d6+3", "damage_type": "fire", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Fire Form", "description": "The elemental can move through a space as narrow as 1 inch wide without squeezing. A creature that touches the elemental or hits it with a melee attack while within 5 feet of it takes 5 (1d10) fire damage. In addition, the elemental can enter a hostile creature's space and stop there. The first time it enters a creature's space on a turn, that creature takes 5 (1d10) fire damage and catches fire; until someone takes an action to douse the fire, the creature takes 5 (1d10) fire damage at the start of each of its turns."}, {"name": "Illumination", "description": "The elemental sheds bright light in a 30-foot radius and dim light in an additional 30 feet."}, {"name": "Water Susceptibility", "description": "For every 5 feet the elemental moves in water, or for every gallon of water splashed on it, it takes 1 cold damage."}}),
		},
		{
			ID: "flesh-golem", Name: "Flesh Golem", Size: "Medium", Type: "construct", Alignment: optStr("neutral"),
			Ac: 9, HpFormula: "11d8+44", HpAverage: 93,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 9, "con": 18, "int": 6, "wis": 10, "cha": 5}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{"lightning", "poison", "bludgeoning, piercing, and slashing from nonmagical attacks that aren't adamantine"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"},
			Languages: []string{"understands the languages of its creator but can't speak"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Slam", "to_hit": 7, "damage": "2d8+4", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Berserk", "description": "Whenever the golem starts its turn with 40 hit points or fewer, roll a d6. On a 6, the golem goes berserk. On each of its turns while berserk, the golem attacks the nearest creature it can see. If no creature is near enough to move to and attack, the golem attacks an object, with preference for an object smaller than itself. Once the golem goes berserk, it continues to do so until it is destroyed or regains all its hit points."}, {"name": "Aversion of Fire", "description": "If the golem takes fire damage, it has disadvantage on attack rolls and ability checks until the end of its next turn."}, {"name": "Immutable Form", "description": "The golem is immune to any spell or effect that would alter its form."}, {"name": "Lightning Absorption", "description": "Whenever the golem is subjected to lightning damage, it takes no damage and instead regains a number of hit points equal to the lightning damage dealt."}, {"name": "Magic Resistance", "description": "The golem has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "The golem's weapon attacks are magical."}}),
		},
		{
			ID: "giant-crocodile", Name: "Giant Crocodile", Size: "Huge", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "9d12+27", HpAverage: 85,
			Speed: mustJSON(map[string]int{"walk": 30, "swim": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 21, "dex": 9, "con": 17, "int": 2, "wis": 10, "cha": 7}),
			Skills: optJSON(map[string]int{"stealth": 5}),
			Senses: optJSON(map[string]any{"passive_perception": 10}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 8, "damage": "3d10+5", "damage_type": "piercing", "reach_ft": 5}, {"name": "Tail", "to_hit": 8, "damage": "2d8+5", "damage_type": "bludgeoning", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Hold Breath", "description": "The crocodile can hold its breath for 30 minutes."}}),
		},
		{
			ID: "giant-shark", Name: "Giant Shark", Size: "Huge", Type: "beast", Alignment: optStr("unaligned"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "11d12+55", HpAverage: 126,
			Speed: mustJSON(map[string]int{"swim": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 23, "dex": 11, "con": 21, "int": 1, "wis": 10, "cha": 5}),
			Skills: optJSON(map[string]int{"perception": 3}),
			Senses: optJSON(map[string]any{"blindsight": 60, "passive_perception": 13}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 9, "damage": "3d10+6", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Blood Frenzy", "description": "The shark has advantage on melee attack rolls against any creature that doesn't have all its hit points."}, {"name": "Water Breathing", "description": "The shark can breathe only underwater."}}),
		},
		{
			ID: "gorgon", Name: "Gorgon", Size: "Large", Type: "monstrosity", Alignment: optStr("unaligned"),
			Ac: 19, AcType: optStr("natural armor"), HpFormula: "12d10+48", HpAverage: 114,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 20, "dex": 11, "con": 18, "int": 2, "wis": 12, "cha": 7}),
			Skills: optJSON(map[string]int{"perception": 4}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 14}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"petrified"},
			Languages: []string{},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Gore", "to_hit": 8, "damage": "2d12+5", "damage_type": "piercing", "reach_ft": 5}, {"name": "Hooves", "to_hit": 8, "damage": "2d10+5", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Trampling Charge", "description": "If the gorgon moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 16 Strength saving throw or be knocked prone. If the target is prone, the gorgon can make one hooves attack against it as a bonus action."}, {"name": "Petrifying Breath (Recharge 5-6)", "description": "The gorgon exhales petrifying gas in a 30-foot cone. Each creature in that area must succeed on a DC 13 Constitution saving throw. On a failed save, a target begins to turn to stone and is restrained. The restrained target must repeat the saving throw at the end of its next turn. On a success, the effect ends on the target. On a failure, the target is petrified until freed by the greater restoration spell or other magic."}}),
		},
		{
			ID: "half-red-dragon-veteran", Name: "Half-Red Dragon Veteran", Size: "Medium", Type: "humanoid", Alignment: optStr("any alignment"),
			Ac: 18, AcType: optStr("plate"), HpFormula: "10d8+20", HpAverage: 65,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 13, "con": 14, "int": 10, "wis": 11, "cha": 10}),
			Skills: optJSON(map[string]int{"athletics": 5, "perception": 2}),
			Senses: optJSON(map[string]any{"blindsight": 10, "darkvision": 60, "passive_perception": 12}),
			DamageResistances: []string{"fire"}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common", "Draconic"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Longsword", "to_hit": 5, "damage": "1d8+3", "damage_type": "slashing", "reach_ft": 5}, {"name": "Shortsword", "to_hit": 5, "damage": "1d6+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Heavy Crossbow", "to_hit": 3, "damage": "1d10+1", "damage_type": "piercing", "reach_ft": 100}}),
			Abilities: optJSON([]map[string]any{{"name": "Fire Breath (Recharge 5-6)", "description": "The veteran exhales fire in a 15-foot cone. Each creature in that area must make a DC 15 Dexterity saving throw, taking 24 (7d6) fire damage on a failed save, or half as much damage on a successful one."}}),
		},
		{
			ID: "hill-giant", Name: "Hill Giant", Size: "Huge", Type: "giant", Alignment: optStr("chaotic evil"),
			Ac: 13, AcType: optStr("natural armor"), HpFormula: "10d12+40", HpAverage: 105,
			Speed: mustJSON(map[string]int{"walk": 40}),
			AbilityScores: mustJSON(map[string]int{"str": 21, "dex": 8, "con": 19, "int": 5, "wis": 9, "cha": 6}),
			Skills: optJSON(map[string]int{"perception": 2}),
			Senses: optJSON(map[string]any{"passive_perception": 12}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Giant"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Greatclub", "to_hit": 8, "damage": "3d8+5", "damage_type": "bludgeoning", "reach_ft": 10}, {"name": "Rock", "to_hit": 8, "damage": "3d10+5", "damage_type": "bludgeoning", "reach_ft": 60}}),
		},
		{
			ID: "night-hag", Name: "Night Hag", Size: "Medium", Type: "fiend", Alignment: optStr("neutral evil"),
			Ac: 17, AcType: optStr("natural armor"), HpFormula: "16d8+40", HpAverage: 112,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 15, "con": 16, "int": 16, "wis": 14, "cha": 16}),
			Skills: optJSON(map[string]int{"deception": 7, "insight": 6, "perception": 6, "stealth": 6}),
			Senses: optJSON(map[string]any{"darkvision": 120, "passive_perception": 16}),
			DamageResistances: []string{"cold", "fire", "bludgeoning, piercing, and slashing from nonmagical attacks that aren't silvered"}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed"},
			Languages: []string{"Abyssal", "Common", "Infernal", "Primordial"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Claws (Hag Form Only)", "to_hit": 7, "damage": "2d8+4", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Innate Spellcasting", "description": "The hag's innate spellcasting ability is Charisma (spell save DC 14, +6 to hit with spell attacks). She can innately cast the following spells, requiring no material components: At will: detect magic, magic missile. 2/day each: plane shift (self only), ray of enfeeblement, sleep."}, {"name": "Magic Resistance", "description": "The hag has advantage on saving throws against spells and other magical effects."}, {"name": "Night Hag Items", "description": "A night hag carries two very rare magic items that she must craft for herself. If either object is lost, the night hag will go to great lengths to retrieve it, as creating a new tool takes time and effort. Heartstone: This lustrous black gem allows a night hag to become ethereal while it is in her possession. Soul Bag: When an evil humanoid dies as a result of a night hag's Nightmare Haunting, the hag catches the soul in this black sack made of stitched flesh."}, {"name": "Change Shape", "description": "The hag magically polymorphs into a Small or Medium female humanoid, or back into her true form. Her statistics are the same in each form. Any equipment she is wearing or carrying isn't transformed. She reverts to her true form if she dies."}}),
		},
		{
			ID: "otyugh", Name: "Otyugh", Size: "Large", Type: "aberration", Alignment: optStr("neutral"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "12d10+48", HpAverage: 114,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 16, "dex": 11, "con": 19, "int": 6, "wis": 13, "cha": 6}),
			SavingThrows: optJSON(map[string]int{"con": 7}),
			Senses: optJSON(map[string]any{"darkvision": 120, "passive_perception": 11}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Otyugh"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 6, "damage": "2d8+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Tentacle", "to_hit": 6, "damage": "1d8+3", "damage_type": "bludgeoning", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Limited Telepathy", "description": "The otyugh can magically transmit simple messages and images to any creature within 120 feet of it that can understand a language. This form of telepathy doesn't allow the receiving creature to telepathically respond."}}),
		},
		{
			ID: "roper", Name: "Roper", Size: "Large", Type: "monstrosity", Alignment: optStr("neutral evil"),
			Ac: 20, AcType: optStr("natural armor"), HpFormula: "11d10+33", HpAverage: 93,
			Speed: mustJSON(map[string]int{"walk": 10, "climb": 10}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 8, "con": 17, "int": 7, "wis": 16, "cha": 6}),
			Skills: optJSON(map[string]int{"perception": 6, "stealth": 5}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 16}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 7, "damage": "4d8+4", "damage_type": "piercing", "reach_ft": 5}, {"name": "Tendril", "to_hit": 7, "damage": "0", "damage_type": "none", "reach_ft": 50}}),
			Abilities: optJSON([]map[string]any{{"name": "False Appearance", "description": "While the roper remains motionless, it is indistinguishable from a normal cave formation, such as a stalagmite."}, {"name": "Grasping Tendrils", "description": "The roper can have up to six tendrils at a time. Each tendril can be attacked (AC 20; 10 hit points; immunity to poison and psychic damage). Destroying a tendril deals no damage to the roper, which can extrude a replacement tendril on its next turn. A tendril can also be broken if a creature takes an action and succeeds on a DC 15 Strength check against it."}, {"name": "Spider Climb", "description": "The roper can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."}}),
		},
		{
			ID: "salamander", Name: "Salamander", Size: "Large", Type: "elemental", Alignment: optStr("neutral evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "12d10+24", HpAverage: 90,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 14, "con": 15, "int": 11, "wis": 10, "cha": 12}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{"bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"fire"}, DamageVulnerabilities: []string{"cold"}, ConditionImmunities: []string{},
			Languages: []string{"Ignan"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Spear", "to_hit": 7, "damage": "2d6+4", "damage_type": "piercing", "reach_ft": 5}, {"name": "Tail", "to_hit": 7, "damage": "2d6+4", "damage_type": "bludgeoning", "reach_ft": 10}}),
			Abilities: optJSON([]map[string]any{{"name": "Heated Body", "description": "A creature that touches the salamander or hits it with a melee attack while within 5 feet of it takes 7 (2d6) fire damage."}, {"name": "Heated Weapons", "description": "Any metal melee weapon the salamander wields deals an extra 3 (1d6) fire damage on a hit (included in the attack)."}}),
		},
		{
			ID: "shambling-mound", Name: "Shambling Mound", Size: "Large", Type: "plant", Alignment: optStr("unaligned"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "16d10+48", HpAverage: 136,
			Speed: mustJSON(map[string]int{"walk": 20, "swim": 20}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 8, "con": 16, "int": 5, "wis": 10, "cha": 5}),
			Skills: optJSON(map[string]int{"stealth": 2}),
			Senses: optJSON(map[string]any{"blindsight": 60, "passive_perception": 10}),
			DamageResistances: []string{"cold", "fire"}, DamageImmunities: []string{"lightning"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"blinded", "deafened", "exhaustion"},
			Languages: []string{},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Slam", "to_hit": 7, "damage": "2d8+4", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Lightning Absorption", "description": "Whenever the shambling mound is subjected to lightning damage, it takes no damage and regains a number of hit points equal to the lightning damage dealt."}, {"name": "Engulf", "description": "The shambling mound engulfs a Medium or smaller creature grappled by it. The engulfed target is blinded, restrained, and unable to breathe, and it must succeed on a DC 14 Constitution saving throw at the start of each of the mound's turns or take 13 (2d8+4) bludgeoning damage. If the mound moves, the engulfed target moves with it. The mound can have only one creature engulfed at a time."}}),
		},
		{
			ID: "troll", Name: "Troll", Size: "Large", Type: "giant", Alignment: optStr("chaotic evil"),
			Ac: 15, AcType: optStr("natural armor"), HpFormula: "8d10+40", HpAverage: 84,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 13, "con": 20, "int": 7, "wis": 9, "cha": 7}),
			Skills: optJSON(map[string]int{"perception": 2}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 12}),
			DamageResistances: []string{}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Giant"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 7, "damage": "1d6+4", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claw", "to_hit": 7, "damage": "2d6+4", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Keen Smell", "description": "The troll has advantage on Wisdom (Perception) checks that rely on smell."}, {"name": "Regeneration", "description": "The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn't function at the start of the troll's next turn. The troll dies only if it starts its turn with 0 hit points and doesn't regenerate."}}),
		},
		{
			ID: "unicorn", Name: "Unicorn", Size: "Large", Type: "celestial", Alignment: optStr("lawful good"),
			Ac: 12, HpFormula: "9d10+18", HpAverage: 67,
			Speed: mustJSON(map[string]int{"walk": 50}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 14, "con": 15, "int": 11, "wis": 17, "cha": 16}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 13}),
			DamageResistances: []string{}, DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed", "paralyzed", "poisoned"},
			Languages: []string{"Celestial", "Elvish", "Sylvan", "telepathy 60 ft."},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Hooves", "to_hit": 7, "damage": "2d6+4", "damage_type": "bludgeoning", "reach_ft": 5}, {"name": "Horn", "to_hit": 7, "damage": "1d8+4", "damage_type": "piercing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Charge", "description": "If the unicorn moves at least 20 feet straight toward a target and then hits it with a horn attack on the same turn, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 15 Strength saving throw or be knocked prone."}, {"name": "Innate Spellcasting", "description": "The unicorn's innate spellcasting ability is Charisma (spell save DC 14). The unicorn can innately cast the following spells, requiring no components: At will: detect evil and good, druidcraft, pass without trace. 1/day each: calm emotions, dispel evil and good, entangle."}, {"name": "Magic Resistance", "description": "The unicorn has advantage on saving throws against spells and other magical effects."}, {"name": "Magic Weapons", "description": "The unicorn's weapon attacks are magical."}, {"name": "Healing Touch (3/Day)", "description": "The unicorn touches another creature with its horn. The target magically regains 11 (2d8+2) hit points. In addition, the touch removes all diseases and neutralizes all poisons afflicting the target."}, {"name": "Teleport (1/Day)", "description": "The unicorn magically teleports itself and up to three willing creatures it can see within 5 feet of it, along with any equipment they are wearing or carrying, to a location the unicorn is familiar with, up to 1 mile away."}}),
		},
		{
			ID: "water-elemental", Name: "Water Elemental", Size: "Large", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 14, AcType: optStr("natural armor"), HpFormula: "12d10+48", HpAverage: 114,
			Speed: mustJSON(map[string]int{"walk": 30, "swim": 90}),
			AbilityScores: mustJSON(map[string]int{"str": 18, "dex": 14, "con": 18, "int": 5, "wis": 10, "cha": 8}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 10}),
			DamageResistances: []string{"acid", "bludgeoning, piercing, and slashing from nonmagical attacks"}, DamageImmunities: []string{"poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"},
			Languages: []string{"Aquan"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Slam", "to_hit": 7, "damage": "2d8+4", "damage_type": "bludgeoning", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Water Form", "description": "The elemental can enter a hostile creature's space and stop there. It can move through a space as narrow as 1 inch wide without squeezing."}, {"name": "Freeze", "description": "If the elemental takes cold damage, it partially freezes; its speed is reduced by 20 feet until the end of its next turn."}, {"name": "Whelm (Recharge 4-6)", "description": "Each creature in the elemental's space must make a DC 15 Strength saving throw. On a failure, a target takes 13 (2d8+4) bludgeoning damage. If it is Large or smaller, it is also grappled (escape DC 14). Until this grapple ends, the target is restrained and unable to breathe unless it can breathe water. If the saving throw is successful, the target is pushed out of the elemental's space."}}),
		},
		{
			ID: "werebear", Name: "Werebear", Size: "Medium", Type: "humanoid", Alignment: optStr("neutral good"),
			Ac: 11, AcType: optStr("natural armor in bear/hybrid form, 10 in humanoid form"), HpFormula: "18d8+54", HpAverage: 135,
			Speed: mustJSON(map[string]int{"walk": 30}),
			AbilityScores: mustJSON(map[string]int{"str": 19, "dex": 10, "con": 17, "int": 11, "wis": 12, "cha": 12}),
			Skills: optJSON(map[string]int{"perception": 7}),
			Senses: optJSON(map[string]any{"passive_perception": 17}),
			DamageResistances: []string{}, DamageImmunities: []string{"bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Common"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite (Bear or Hybrid Form Only)", "to_hit": 7, "damage": "2d10+4", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claw (Bear or Hybrid Form Only)", "to_hit": 7, "damage": "2d8+4", "damage_type": "slashing", "reach_ft": 5}, {"name": "Greataxe (Humanoid or Hybrid Form Only)", "to_hit": 7, "damage": "1d12+4", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Shapechanger", "description": "The werebear can use its action to polymorph into a Large bear-humanoid hybrid or into a Large bear, or back into its true form, which is humanoid. Its statistics, other than its size and AC, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies."}, {"name": "Keen Smell", "description": "The werebear has advantage on Wisdom (Perception) checks that rely on smell."}}),
		},
		{
			ID: "wraith", Name: "Wraith", Size: "Medium", Type: "undead", Alignment: optStr("neutral evil"),
			Ac: 13, HpFormula: "9d8+27", HpAverage: 67,
			Speed: mustJSON(map[string]int{"fly": 60}),
			AbilityScores: mustJSON(map[string]int{"str": 6, "dex": 16, "con": 16, "int": 12, "wis": 14, "cha": 15}),
			Senses: optJSON(map[string]any{"darkvision": 60, "passive_perception": 12}),
			DamageResistances: []string{"acid", "cold", "fire", "lightning", "thunder", "bludgeoning, piercing, and slashing from nonmagical attacks that aren't silvered"}, DamageImmunities: []string{"necrotic", "poison"}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{"charmed", "exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"},
			Languages: []string{"the languages it knew in life"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Life Drain", "to_hit": 6, "damage": "4d8+3", "damage_type": "necrotic", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Incorporeal Movement", "description": "The wraith can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object."}, {"name": "Sunlight Sensitivity", "description": "While in sunlight, the wraith has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."}, {"name": "Create Specter", "description": "The wraith targets a humanoid within 10 feet of it that has been dead for no longer than 1 minute and died violently. The target's spirit rises as a specter in the space of its corpse or in the nearest unoccupied space. The specter is under the wraith's control. The wraith can have no more than seven specters under its control at one time."}}),
		},
		{
			ID: "xorn", Name: "Xorn", Size: "Medium", Type: "elemental", Alignment: optStr("neutral"),
			Ac: 19, AcType: optStr("natural armor"), HpFormula: "7d8+42", HpAverage: 73,
			Speed: mustJSON(map[string]int{"walk": 20, "burrow": 20}),
			AbilityScores: mustJSON(map[string]int{"str": 17, "dex": 10, "con": 22, "int": 11, "wis": 10, "cha": 11}),
			Skills: optJSON(map[string]int{"perception": 6, "stealth": 3}),
			Senses: optJSON(map[string]any{"darkvision": 60, "tremorsense": 60, "passive_perception": 16}),
			DamageResistances: []string{"piercing and slashing from nonmagical attacks that aren't adamantine"}, DamageImmunities: []string{}, DamageVulnerabilities: []string{}, ConditionImmunities: []string{},
			Languages: []string{"Terran"},
			Cr: "5",
			Attacks: mustJSON([]map[string]any{{"name": "Bite", "to_hit": 6, "damage": "3d6+3", "damage_type": "piercing", "reach_ft": 5}, {"name": "Claw", "to_hit": 6, "damage": "1d6+3", "damage_type": "slashing", "reach_ft": 5}}),
			Abilities: optJSON([]map[string]any{{"name": "Earth Glide", "description": "The xorn can burrow through nonmagical, unworked earth and stone. While doing so, the xorn doesn't disturb the material it moves through."}, {"name": "Stone Camouflage", "description": "The xorn has advantage on Dexterity (Stealth) checks made to hide in rocky terrain."}, {"name": "Treasure Sense", "description": "The xorn can pinpoint, by scent, the location of precious metals and stones, such as coins and gems, within 60 feet of it."}}),
		},
	}
}
