package refdata

func srdCantrips() []sp {
	return []sp{
		{ID: "acid-splash", Name: "Acid Splash", Level: 0, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "1d6", "type": "acid", "cantrip_scaling": true}), SaveAbility: optStr("dex"), SaveEffect: optStr("no_effect")},
		{ID: "blade-ward", Name: "Blade Ward", Level: 0, School: "abjuration", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S"}, Duration: "1 round", Description: "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.", ResolutionMode: "auto", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "chill-touch", Name: "Chill Touch", Level: 0, School: "necromancy", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(120), Components: []string{"V", "S"}, Duration: "1 round", Description: "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can't regain hit points until the start of your next turn.", ResolutionMode: "auto", Classes: []string{"sorcerer", "warlock", "wizard"}, Damage: optJSON(map[string]any{"dice": "1d8", "type": "necrotic", "cantrip_scaling": true}), AttackType: optStr("ranged")},
		{ID: "dancing-lights", Name: "Dancing Lights", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(120), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a bit of phosphorus or wychwood, or a glowworm"), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "wizard"}},
		{ID: "druidcraft", Name: "Druidcraft", Level: 0, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "Whispering to the spirits of nature, you create one of several minor effects: weather prediction, flower bloom, sensory effect, or light/snuff a flame.", ResolutionMode: "dm_required", Classes: []string{"druid"}},
		{ID: "eldritch-blast", Name: "Eldritch Blast", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(120), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.", ResolutionMode: "auto", Classes: []string{"warlock"}, Damage: optJSON(map[string]any{"dice": "1d10", "type": "force", "cantrip_scaling": true}), AttackType: optStr("ranged")},
		{ID: "fire-bolt", Name: "Fire Bolt", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(120), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "1d10", "type": "fire", "cantrip_scaling": true}), AttackType: optStr("ranged")},
		{ID: "friends", Name: "Friends", Level: 0, School: "enchantment", CastingTime: "1 action", RangeType: "self", Components: []string{"S", "M"}, MaterialDescription: optStr("a small amount of makeup applied to the face"), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn't hostile toward you.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "guidance", Name: "Guidance", Level: 0, School: "divination", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S"}, Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.", ResolutionMode: "auto", Classes: []string{"cleric", "druid"}},
		{ID: "light", Name: "Light", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "M"}, MaterialDescription: optStr("a firefly or phosphorescent moss"), Duration: "1 hour", Description: "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.", ResolutionMode: "auto", Classes: []string{"bard", "cleric", "sorcerer", "wizard"}},
		{ID: "mage-hand", Name: "Mage Hand", Level: 0, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V", "S"}, Duration: "1 minute", Description: "A spectral, floating hand appears at a point you choose within range. The hand can manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "mending", Name: "Mending", Level: 0, School: "transmutation", CastingTime: "1 minute", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("two lodestones"), Duration: "Instantaneous", Description: "This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin.", ResolutionMode: "dm_required", Classes: []string{"bard", "cleric", "druid", "sorcerer", "wizard"}},
		{ID: "message", Name: "Message", Level: 0, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(120), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a short piece of copper wire"), Duration: "1 round", Description: "You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "wizard"}},
		{ID: "minor-illusion", Name: "Minor Illusion", Level: 0, School: "illusion", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"S", "M"}, MaterialDescription: optStr("a bit of fleece"), Duration: "1 minute", Description: "You create a sound or an image of an object within range that lasts for the duration.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "poison-spray", Name: "Poison Spray", Level: 0, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(10), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.", ResolutionMode: "auto", Classes: []string{"druid", "sorcerer", "warlock", "wizard"}, Damage: optJSON(map[string]any{"dice": "1d12", "type": "poison", "cantrip_scaling": true}), SaveAbility: optStr("con"), SaveEffect: optStr("no_effect")},
		{ID: "prestidigitation", Name: "Prestidigitation", Level: 0, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(10), Components: []string{"V", "S"}, Duration: "Up to 1 hour", Description: "This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor magical effects.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "produce-flame", Name: "Produce Flame", Level: 0, School: "conjuration", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S"}, Duration: "10 minutes", Description: "A flickering flame appears in your hand. It sheds bright light in a 10-foot radius and dim light for an additional 10 feet. You can also hurl the flame at a creature within 30 feet, making a ranged spell attack dealing 1d8 fire damage.", ResolutionMode: "auto", Classes: []string{"druid"}, Damage: optJSON(map[string]any{"dice": "1d8", "type": "fire", "cantrip_scaling": true}), AttackType: optStr("ranged")},
		{ID: "ray-of-frost", Name: "Ray of Frost", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "1d8", "type": "cold", "cantrip_scaling": true}), AttackType: optStr("ranged")},
		{ID: "resistance", Name: "Resistance", Level: 0, School: "abjuration", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a miniature cloak"), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice.", ResolutionMode: "auto", Classes: []string{"cleric", "druid"}},
		{ID: "sacred-flame", Name: "Sacred Flame", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage.", ResolutionMode: "auto", Classes: []string{"cleric"}, Damage: optJSON(map[string]any{"dice": "1d8", "type": "radiant", "cantrip_scaling": true}), SaveAbility: optStr("dex"), SaveEffect: optStr("no_effect")},
		{ID: "shillelagh", Name: "Shillelagh", Level: 0, School: "transmutation", CastingTime: "1 bonus action", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("mistletoe, a shamrock leaf, and a club or quarterstaff"), Duration: "1 minute", Description: "The wood of a club or quarterstaff you are holding is imbued with nature's power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon's damage die becomes a d8.", ResolutionMode: "auto", Classes: []string{"druid"}},
		{ID: "shocking-grasp", Name: "Shocking Grasp", Level: 0, School: "evocation", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. On a hit, the target takes 1d8 lightning damage, and it can't take reactions until the start of its next turn.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "1d8", "type": "lightning", "cantrip_scaling": true}), AttackType: optStr("melee")},
		{ID: "spare-the-dying", Name: "Spare the Dying", Level: 0, School: "necromancy", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "You touch a living creature that has 0 hit points. The creature becomes stable.", ResolutionMode: "auto", Classes: []string{"cleric"}},
		{ID: "thaumaturgy", Name: "Thaumaturgy", Level: 0, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V"}, Duration: "Up to 1 minute", Description: "You manifest a minor wonder, a sign of supernatural power: your voice booms, flames flicker, the ground trembles, or other effects.", ResolutionMode: "dm_required", Classes: []string{"cleric"}},
		{ID: "thorn-whip", Name: "Thorn Whip", Level: 0, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("the stem of a plant with thorns"), Duration: "Instantaneous", Description: "You create a long, vine-like whip covered in thorns that lashes out at your command toward a creature in range. Make a melee spell attack against the target. On a hit, the creature takes 1d6 piercing damage, and if the creature is Large or smaller, you pull the creature up to 10 feet closer to you.", ResolutionMode: "auto", Classes: []string{"druid"}, Damage: optJSON(map[string]any{"dice": "1d6", "type": "piercing", "cantrip_scaling": true}), AttackType: optStr("melee")},
		{ID: "true-strike", Name: "True Strike", Level: 0, School: "divination", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"S"}, Duration: "Concentration, up to 1 round", Concentration: optBool(true), Description: "You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target's defenses. On your next turn, you gain advantage on your first attack roll against the target.", ResolutionMode: "auto", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "vicious-mockery", Name: "Vicious Mockery", Level: 0, School: "enchantment", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V"}, Duration: "Instantaneous", Description: "You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you, it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.", ResolutionMode: "auto", Classes: []string{"bard"}, Damage: optJSON(map[string]any{"dice": "1d4", "type": "psychic", "cantrip_scaling": true}), SaveAbility: optStr("wis"), SaveEffect: optStr("no_effect")},
	}
}
