package refdata

import "context"

// mi is a shorthand builder for UpsertMagicItemParams to reduce verbosity.
type mi = UpsertMagicItemParams

func seedMagicItems(ctx context.Context, q *Queries) error {
	return seedEntities(ctx, srdMagicItems(), q.UpsertMagicItem, "magic_item")
}

func srdMagicItems() []mi {
	return []mi{
		// ── Weapons (+1/+2/+3) ──────────────────────────────────────
		// These are generic enhancement TEMPLATES. The spec mentions
		// "+1 Longsword" / "+1 Greatsword" etc. as named items, but in
		// practice every named +N weapon is the base weapon ID joined
		// with one of these enhancement templates at the inventory
		// layer, keeping the SRD seed compact.
		{ID: "weapon-plus-1", Name: "Weapon +1", BaseItemType: optStr("weapon"), Rarity: "uncommon", MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 1}, {"type": "modify_damage", "modifier": 1}}),
			Description:    "You have a +1 bonus to attack and damage rolls made with this magic weapon."},
		{ID: "weapon-plus-2", Name: "Weapon +2", BaseItemType: optStr("weapon"), Rarity: "rare", MagicBonus: optInt(2),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 2}, {"type": "modify_damage", "modifier": 2}}),
			Description:    "You have a +2 bonus to attack and damage rolls made with this magic weapon."},
		{ID: "weapon-plus-3", Name: "Weapon +3", BaseItemType: optStr("weapon"), Rarity: "very_rare", MagicBonus: optInt(3),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 3}, {"type": "modify_damage", "modifier": 3}}),
			Description:    "You have a +3 bonus to attack and damage rolls made with this magic weapon."},

		// ── Named Weapons ───────────────────────────────────────────
		{ID: "berserker-axe", Name: "Berserker Axe", BaseItemType: optStr("weapon"), BaseItemID: optStr("greataxe"), Rarity: "rare",
			RequiresAttunement: optBool(true), MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 1}, {"type": "modify_damage", "modifier": 1}, {"type": "bonus_hp", "modifier": 1, "per_level": true}}),
			Description:        "You gain a +1 bonus to attack and damage rolls made with this magic axe. You gain 1 bonus hit point for each level you have attained. While attuned, you must make a DC 15 Wisdom saving throw when you take damage in combat or go berserk."},
		{ID: "dancing-sword", Name: "Dancing Sword", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "very_rare",
			RequiresAttunement: optBool(true),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Dance", "action_type": "bonus_action", "description": "Toss the sword into the air and it hovers, flies up to 30 feet and attacks the same target you do."}}),
			Description:        "You can use a bonus action to toss this sword into the air and speak the command word. The sword begins to hover, flies up to 30 feet, and attacks one creature of your choice within 5 feet of it."},
		{ID: "defender", Name: "Defender", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "legendary",
			RequiresAttunement: optBool(true), MagicBonus: optInt(3),
			Description:        "You gain a +3 bonus to attack and damage rolls made with this magic weapon. The first time you attack with the sword on each of your turns, you can transfer some or all of the sword's bonus to your AC instead."},
		{ID: "dragon-slayer", Name: "Dragon Slayer", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "rare",
			MagicBonus:     optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 1}, {"type": "modify_damage", "modifier": 1}, {"type": "bonus_damage_vs", "creature_type": "dragon", "dice": "3d6"}}),
			Description:    "You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a dragon with this weapon, the dragon takes an extra 3d6 damage of the weapon's type."},
		{ID: "flame-tongue", Name: "Flame Tongue", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Ignite", "action_type": "bonus_action", "description": "Speak command word to cause flames to erupt, shedding bright light in a 40-foot radius and dealing an extra 2d6 fire damage."}}),
			Description:        "You can use a bonus action to speak this magic sword's command word, causing flames to erupt from the blade. The flames shed bright light in a 40-foot radius and dim light for an additional 40 feet. While ablaze, the sword deals an extra 2d6 fire damage to any target it hits."},
		{ID: "frost-brand", Name: "Frost Brand", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "very_rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "bonus_damage", "damage_type": "cold", "dice": "1d6"}, {"type": "resistance", "damage_type": "fire"}}),
			Description:        "When you hit with an attack using this magic sword, the target takes an extra 1d6 cold damage. You have resistance to fire damage while you hold the sword."},
		{ID: "giant-slayer", Name: "Giant Slayer", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "rare",
			MagicBonus:     optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 1}, {"type": "modify_damage", "modifier": 1}, {"type": "bonus_damage_vs", "creature_type": "giant", "dice": "2d6"}}),
			Description:    "You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a giant with it, the giant takes an extra 2d6 damage of the weapon's type and must succeed on a DC 15 Strength saving throw or fall prone."},
		{ID: "holy-avenger", Name: "Holy Avenger", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "legendary",
			RequiresAttunement: optBool(true), AttunementRestriction: optStr("by a paladin"), MagicBonus: optInt(3),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 3}, {"type": "modify_damage", "modifier": 3}, {"type": "bonus_damage_vs", "creature_type": "fiend_or_undead", "dice": "2d10", "damage_type": "radiant"}}),
			Description:    "You gain a +3 bonus to attack and damage rolls made with this magic weapon. When you hit a fiend or an undead with it, that creature takes an extra 2d10 radiant damage. While you hold the drawn sword, it creates a 10-foot-radius aura that grants you and friendly creatures advantage on saving throws against spells and other magical effects."},
		{ID: "luck-blade", Name: "Luck Blade", BaseItemType: optStr("weapon"), BaseItemID: optStr("shortsword"), Rarity: "legendary",
			RequiresAttunement: optBool(true), MagicBonus: optInt(1),
			PassiveEffects:     optJSON([]map[string]any{{"type": "modify_attack", "modifier": 1}, {"type": "modify_damage", "modifier": 1}, {"type": "modify_saving_throw", "modifier": 1}}),
			Charges:            optJSON(map[string]any{"max": 3, "recharge": "never"}),
			Description:        "You gain a +1 bonus to attack and damage rolls made with this magic weapon. While the sword is on your person, you gain a +1 bonus to saving throws. You can use the sword's luck to reroll one attack roll, ability check, or saving throw. You can also spend 1 charge to cast wish."},
		{ID: "mace-of-disruption", Name: "Mace of Disruption", BaseItemType: optStr("weapon"), BaseItemID: optStr("mace"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "bonus_damage_vs", "creature_type": "fiend_or_undead", "dice": "2d6", "damage_type": "radiant"}}),
			Description:        "When you hit a fiend or an undead with this magic weapon, that creature takes an extra 2d6 radiant damage. If the target has 25 hit points or fewer after taking this damage, it must succeed on a DC 15 Wisdom saving throw or be destroyed."},
		{ID: "mace-of-smiting", Name: "Mace of Smiting", BaseItemType: optStr("weapon"), BaseItemID: optStr("mace"), Rarity: "rare",
			MagicBonus:     optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 1}, {"type": "modify_damage", "modifier": 1}, {"type": "bonus_damage_vs", "creature_type": "construct", "dice": "2d6"}}),
			Description:    "You gain a +1 bonus to attack and damage rolls made with this magic weapon. The bonus increases to +3 when you use the mace to attack a construct. When you roll a 20 on an attack roll, the target takes an extra 2d6 bludgeoning damage, or 4d6 if it's a construct."},
		{ID: "nine-lives-stealer", Name: "Nine Lives Stealer", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "very_rare",
			RequiresAttunement: optBool(true), MagicBonus: optInt(2),
			Charges:            optJSON(map[string]any{"max": 9, "recharge": "never"}),
			Description:        "You gain a +2 bonus to attack and damage rolls made with this magic weapon. The sword has 9 charges. If you score a critical hit against a creature that has fewer than 100 hit points, it must succeed on a DC 15 Constitution saving throw or be slain instantly. The sword loses 1 charge if the creature is slain."},
		{ID: "oathbow", Name: "Oathbow", BaseItemType: optStr("weapon"), BaseItemID: optStr("longbow"), Rarity: "very_rare",
			RequiresAttunement: optBool(true),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Sworn Enemy", "action_type": "special", "description": "Speak command phrase when you nock an arrow to designate your sworn enemy. You have advantage on attack rolls against the target and deal an extra 3d6 piercing damage."}}),
			Description:        "When you nock an arrow on this bow, it whispers in Elvish 'Swift defeat to my enemies.' When you use this weapon to make a ranged attack, you can speak its command phrase to designate a creature as your sworn enemy for seven days or until it drops to 0 hit points."},
		{ID: "scimitar-of-speed", Name: "Scimitar of Speed", BaseItemType: optStr("weapon"), BaseItemID: optStr("scimitar"), Rarity: "very_rare",
			RequiresAttunement: optBool(true), MagicBonus: optInt(2),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Quick Strike", "action_type": "bonus_action", "description": "Make one attack with this weapon as a bonus action on each of your turns."}}),
			Description:        "You gain a +2 bonus to attack and damage rolls made with this magic weapon. In addition, you can make one attack with it as a bonus action on each of your turns."},
		{ID: "sun-blade", Name: "Sun Blade", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "rare",
			RequiresAttunement: optBool(true), MagicBonus: optInt(2),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_attack", "modifier": 2}, {"type": "modify_damage", "modifier": 2}, {"type": "bonus_damage_vs", "creature_type": "undead", "dice": "1d8", "damage_type": "radiant"}}),
			Description:    "This item appears to be a longsword hilt. While grasping the hilt, you can use a bonus action to cause a blade of pure radiance to spring into existence. You gain a +2 bonus to attack and damage rolls with this weapon, which deals radiant damage instead of slashing. Undead take an extra 1d8 radiant damage."},
		{ID: "sword-of-life-stealing", Name: "Sword of Life Stealing", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			Description:        "When you attack a creature with this magic weapon and roll a 20 on the attack roll, that target takes an extra 3d6 necrotic damage, provided that the target isn't a construct or an undead. You gain temporary hit points equal to the extra damage dealt."},
		{ID: "sword-of-sharpness", Name: "Sword of Sharpness", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "very_rare",
			RequiresAttunement: optBool(true),
			Description:        "When you attack an object with this magic sword and hit, maximize your weapon damage dice against the target. When you attack a creature and roll a 20, that target takes an extra 4d6 slashing damage. Then roll another d20. If you roll a 20, you lop off one of the target's limbs."},
		{ID: "sword-of-wounding", Name: "Sword of Wounding", BaseItemType: optStr("weapon"), BaseItemID: optStr("longsword"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			Description:        "Hit points lost to this weapon's damage can be regained only through a short or long rest, rather than by regeneration, magic, or any other means. Once per turn, when you hit a creature with this weapon, you can wound the target. The wounded target takes 1d4 necrotic damage at the start of each of its turns."},
		{ID: "trident-of-fish-command", Name: "Trident of Fish Command", BaseItemType: optStr("weapon"), BaseItemID: optStr("trident"), Rarity: "uncommon",
			RequiresAttunement: optBool(true),
			Charges:            optJSON(map[string]any{"max": 3, "recharge": "dawn", "recharge_dice": "1d3"}),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Dominate Beast (fish)", "charges_cost": 1, "action_type": "action", "description": "Use 1 charge to cast dominate beast (save DC 15) on a beast that has an innate swimming speed."}}),
			Description:        "This trident is a magic weapon. It has 3 charges. While you carry it, you can use an action and expend 1 charge to cast dominate beast (save DC 15) from it on a beast that has an innate swimming speed. The trident regains 1d3 expended charges daily at dawn."},
		{ID: "vicious-weapon", Name: "Vicious Weapon", BaseItemType: optStr("weapon"), Rarity: "rare",
			Description: "When you roll a 20 on your attack roll with this magic weapon, the target takes an extra 2d6 damage of the weapon's type."},
		{ID: "vorpal-sword", Name: "Vorpal Sword", BaseItemType: optStr("weapon"), BaseItemID: optStr("greatsword"), Rarity: "legendary",
			RequiresAttunement: optBool(true), MagicBonus: optInt(3),
			Description:        "You gain a +3 bonus to attack and damage rolls made with this magic weapon. In addition, the weapon ignores resistance to slashing damage. When you attack a creature that has at least one head and roll a 20, you cut off one of the creature's heads."},
		{ID: "javelin-of-lightning", Name: "Javelin of Lightning", BaseItemType: optStr("weapon"), BaseItemID: optStr("javelin"), Rarity: "uncommon",
			ActiveAbilities: optJSON([]map[string]any{{"name": "Lightning Bolt", "action_type": "action", "description": "Speak the command word and throw the javelin. It transforms into a bolt of lightning, forming a 5-foot-wide line. Each creature in the line must make a DC 13 Dexterity saving throw, taking 4d6 lightning damage on a failed save."}}),
			Description:     "This javelin is a magic weapon. When you hurl it and speak its command word, it transforms into a bolt of lightning, forming a line 5 feet wide that extends out from you to a target within 120 feet. Each creature in the line excluding you and the target must make a DC 13 Dexterity saving throw, taking 4d6 lightning damage on a failed save, or half as much on a successful one. The javelin then reverts to its normal form. This property can't be used again until the next dawn."},

		// ── Armor (+1/+2/+3) ────────────────────────────────────────
		{ID: "armor-plus-1", Name: "Armor +1", BaseItemType: optStr("armor"), Rarity: "rare", MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}}),
			Description:    "You have a +1 bonus to AC while wearing this armor."},
		{ID: "armor-plus-2", Name: "Armor +2", BaseItemType: optStr("armor"), Rarity: "very_rare", MagicBonus: optInt(2),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 2}}),
			Description:    "You have a +2 bonus to AC while wearing this armor."},
		{ID: "armor-plus-3", Name: "Armor +3", BaseItemType: optStr("armor"), Rarity: "legendary", MagicBonus: optInt(3),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 3}}),
			Description:    "You have a +3 bonus to AC while wearing this armor."},
		{ID: "shield-plus-1", Name: "Shield +1", BaseItemType: optStr("armor"), BaseItemID: optStr("shield"), Rarity: "uncommon", MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}}),
			Description:    "While holding this shield, you have a +1 bonus to AC in addition to the shield's normal bonus to AC."},
		{ID: "shield-plus-2", Name: "Shield +2", BaseItemType: optStr("armor"), BaseItemID: optStr("shield"), Rarity: "rare", MagicBonus: optInt(2),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 2}}),
			Description:    "While holding this shield, you have a +2 bonus to AC in addition to the shield's normal bonus to AC."},
		{ID: "shield-plus-3", Name: "Shield +3", BaseItemType: optStr("armor"), BaseItemID: optStr("shield"), Rarity: "very_rare", MagicBonus: optInt(3),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 3}}),
			Description:    "While holding this shield, you have a +3 bonus to AC in addition to the shield's normal bonus to AC."},

		// ── Named Armor ─────────────────────────────────────────────
		{ID: "adamantine-armor", Name: "Adamantine Armor", BaseItemType: optStr("armor"), Rarity: "uncommon",
			PassiveEffects: optJSON([]map[string]any{{"type": "critical_hit_immunity"}}),
			Description:    "This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you're wearing it, any critical hit against you becomes a normal hit."},
		{ID: "animated-shield", Name: "Animated Shield", BaseItemType: optStr("armor"), BaseItemID: optStr("shield"), Rarity: "very_rare",
			RequiresAttunement: optBool(true),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Animate", "action_type": "bonus_action", "description": "Speak the command word to animate the shield. It leaps into the air and hovers in your space, granting its AC bonus while leaving your hands free."}}),
			Description:        "While holding this shield, you can speak its command word as a bonus action to cause it to animate. The shield leaps into the air and hovers in your space to protect you as if you were wielding it, leaving both your hands free."},
		{ID: "armor-of-invulnerability", Name: "Armor of Invulnerability", BaseItemType: optStr("armor"), BaseItemID: optStr("plate"), Rarity: "legendary",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "resistance", "damage_type": "nonmagical"}}),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Invulnerability", "action_type": "action", "description": "You can use an action to make yourself immune to nonmagical damage for 10 minutes or until you are no longer wearing the armor."}}),
			Description:        "You have resistance to nonmagical damage while you wear this armor. Additionally, you can use an action to make yourself immune to nonmagical damage for 10 minutes or until you are no longer wearing the armor. Once this special action is used, it can't be used again until the next dawn."},
		{ID: "armor-of-resistance", Name: "Armor of Resistance", BaseItemType: optStr("armor"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "resistance", "damage_type": "varies"}}),
			Description:        "You have resistance to one type of damage while you wear this armor. The DM chooses the type or determines it randomly."},
		{ID: "arrow-catching-shield", Name: "Arrow-Catching Shield", BaseItemType: optStr("armor"), BaseItemID: optStr("shield"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "modify_ac_vs", "attack_type": "ranged", "modifier": 2}}),
			Description:        "You gain a +2 bonus to AC against ranged attacks while you wield this shield. This bonus is in addition to the shield's normal bonus to AC. Whenever an attacker makes a ranged attack against a target within 5 feet of you, you can use your reaction to become the target of the attack instead."},
		{ID: "demon-armor", Name: "Demon Armor", BaseItemType: optStr("armor"), BaseItemID: optStr("plate"), Rarity: "very_rare",
			RequiresAttunement: optBool(true), MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}}),
			Description:    "While wearing this armor, you gain a +1 bonus to AC, and you can understand and speak Abyssal. In addition, the armor's clawed gauntlets turn unarmed strikes into magic weapons that deal 1d8 slashing damage."},
		{ID: "dragon-scale-mail", Name: "Dragon Scale Mail", BaseItemType: optStr("armor"), BaseItemID: optStr("scale-mail"), Rarity: "very_rare",
			RequiresAttunement: optBool(true), MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}, {"type": "resistance", "damage_type": "varies"}, {"type": "advantage", "on": "saving_throws_vs_breath_weapons"}}),
			Description:    "Dragon scale mail is made of the scales of one kind of dragon. You have a +1 bonus to AC, advantage on saving throws against the Frightful Presence and breath weapons of dragons, and resistance to one damage type determined by the kind of dragon that provided the scales."},
		{ID: "dwarven-plate", Name: "Dwarven Plate", BaseItemType: optStr("armor"), BaseItemID: optStr("plate"), Rarity: "very_rare",
			MagicBonus:     optInt(2),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 2}, {"type": "reduce_forced_movement", "amount": 10}}),
			Description:    "While wearing this armor, you gain a +2 bonus to AC. In addition, if an effect moves you against your will along the ground, you can use your reaction to reduce the distance you are moved by up to 10 feet."},
		{ID: "efreeti-chain", Name: "Efreeti Chain", BaseItemType: optStr("armor"), BaseItemID: optStr("chain-mail"), Rarity: "legendary",
			RequiresAttunement: optBool(true), MagicBonus: optInt(3),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 3}, {"type": "immunity", "damage_type": "fire"}}),
			Description:    "While wearing this armor, you gain a +3 bonus to AC, you are immune to fire damage, and you can understand and speak Primordial. In addition, you can stand on and walk across molten rock as if it were solid ground."},
		{ID: "glamoured-studded-leather", Name: "Glamoured Studded Leather", BaseItemType: optStr("armor"), BaseItemID: optStr("studded-leather"), Rarity: "rare",
			MagicBonus:     optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}}),
			ActiveAbilities: optJSON([]map[string]any{{"name": "Glamour", "action_type": "bonus_action", "description": "Speak the command word to change the armor's appearance to a normal set of clothing or other type of armor."}}),
			Description:     "While wearing this armor, you gain a +1 bonus to AC. You can also use a bonus action to speak the armor's command word and cause the armor to assume the appearance of a normal set of clothing or some other kind of armor."},
		{ID: "spellguard-shield", Name: "Spellguard Shield", BaseItemType: optStr("armor"), BaseItemID: optStr("shield"), Rarity: "very_rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "advantage", "on": "saving_throws_vs_spells"}, {"type": "disadvantage_on_attacks", "applies_to": "spell_attacks_against_you"}}),
			Description:        "While holding this shield, you have advantage on saving throws against spells and other magical effects, and spell attacks have disadvantage against you."},

		// ── Wondrous Items ──────────────────────────────────────────
		{ID: "amulet-of-health", Name: "Amulet of Health", BaseItemType: optStr("wondrous"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "set_ability_score", "ability": "constitution", "value": 19}}),
			Description:        "Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is already 19 or higher."},
		{ID: "bag-of-holding", Name: "Bag of Holding", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			Description: "This bag has an interior space considerably larger than its outside dimensions, roughly 2 feet in diameter at the mouth and 4 feet deep. The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet. The bag weighs 15 pounds, regardless of its contents."},
		{ID: "belt-of-giant-strength-hill", Name: "Belt of Giant Strength (Hill)", BaseItemType: optStr("wondrous"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "set_ability_score", "ability": "strength", "value": 21}}),
			Description:        "While wearing this belt, your Strength score changes to 21. The item has no effect on you if your Strength without the belt is equal to or greater than the belt's score."},
		{ID: "boots-of-elvenkind", Name: "Boots of Elvenkind", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			PassiveEffects: optJSON([]map[string]any{{"type": "advantage", "on": "stealth_checks"}}),
			Description:    "While you wear these boots, your steps make no sound, regardless of the surface you are moving across. You also have advantage on Dexterity (Stealth) checks that rely on moving silently."},
		{ID: "boots-of-speed", Name: "Boots of Speed", BaseItemType: optStr("wondrous"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Speed", "action_type": "bonus_action", "description": "Click heels together to double your walking speed for 10 minutes and impose disadvantage on opportunity attacks against you."}}),
			Description:        "While you wear these boots, you can use a bonus action and click the boots' heels together. The boots double your walking speed, and any creature that makes an opportunity attack against you has disadvantage on the attack roll. The effect lasts for 10 minutes. The boots can't be used again until after a long rest."},
		{ID: "bracers-of-defense", Name: "Bracers of Defense", BaseItemType: optStr("wondrous"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "modify_ac", "modifier": 2, "condition": "no_armor_no_shield"}}),
			Description:        "While wearing these bracers, you gain a +2 bonus to AC if you are wearing no armor and using no shield."},
		{ID: "cloak-of-displacement", Name: "Cloak of Displacement", BaseItemType: optStr("wondrous"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "disadvantage_on_attacks", "applies_to": "attacks_against_you"}}),
			Description:        "While you wear this cloak, it projects an illusion that makes you appear to be standing in a place near your actual location, causing any creature to have disadvantage on attack rolls against you. If you take damage, the property ceases to function until the start of your next turn."},
		{ID: "cloak-of-protection", Name: "Cloak of Protection", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}, {"type": "modify_saving_throw", "modifier": 1}}),
			Description:        "You gain a +1 bonus to AC and saving throws while you wear this cloak."},
		{ID: "gauntlets-of-ogre-power", Name: "Gauntlets of Ogre Power", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "set_ability_score", "ability": "strength", "value": 19}}),
			Description:        "Your Strength score is 19 while you wear these gauntlets. They have no effect on you if your Strength is already 19 or higher."},
		{ID: "goggles-of-night", Name: "Goggles of Night", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			PassiveEffects: optJSON([]map[string]any{{"type": "grant_darkvision", "range": 60}}),
			Description:    "While wearing these dark lenses, you have darkvision out to a range of 60 feet. If you already have darkvision, wearing the goggles increases its range by 60 feet."},
		{ID: "headband-of-intellect", Name: "Headband of Intellect", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "set_ability_score", "ability": "intelligence", "value": 19}}),
			Description:        "Your Intelligence score is 19 while you wear this headband. It has no effect on you if your Intelligence is already 19 or higher."},
		{ID: "mantle-of-spell-resistance", Name: "Mantle of Spell Resistance", BaseItemType: optStr("wondrous"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "advantage", "on": "saving_throws_vs_spells"}}),
			Description:        "You have advantage on saving throws against spells while you wear this cloak."},
		{ID: "necklace-of-fireballs", Name: "Necklace of Fireballs", BaseItemType: optStr("wondrous"), Rarity: "rare",
			ActiveAbilities: optJSON([]map[string]any{{"name": "Fireball", "action_type": "action", "spell_id": "fireball", "description": "Detach a bead and hurl it up to 60 feet away. It detonates as a 3rd-level fireball spell (save DC 15)."}}),
			Description:     "This necklace has 1d6+3 beads hanging from it. You can use an action to detach a bead and throw it up to 60 feet away. When it reaches the end of its trajectory, it detonates as a 3rd-level fireball spell (save DC 15)."},
		{ID: "portable-hole", Name: "Portable Hole", BaseItemType: optStr("wondrous"), Rarity: "rare",
			Description: "This fine black cloth, soft as silk, is folded up to the dimensions of a handkerchief. It unfolds into a circular sheet 6 feet in diameter. You can use an action to unfold and place the portable hole on a solid surface, whereupon it creates an extradimensional hole 10 feet deep."},
		{ID: "ring-of-protection", Name: "Ring of Protection", BaseItemType: optStr("ring"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "modify_ac", "modifier": 1}, {"type": "modify_saving_throw", "modifier": 1}}),
			Description:        "You gain a +1 bonus to AC and saving throws while wearing this ring."},
		{ID: "ring-of-spell-storing", Name: "Ring of Spell Storing", BaseItemType: optStr("ring"), Rarity: "rare",
			RequiresAttunement: optBool(true),
			Description:        "This ring stores spells cast into it, holding them until the attuned wearer uses them. The ring can store up to 5 levels worth of spells at a time. Any creature can cast a spell of 1st through 5th level into the ring by touching the ring as the spell is cast."},
		{ID: "robe-of-the-archmagi", Name: "Robe of the Archmagi", BaseItemType: optStr("wondrous"), Rarity: "legendary",
			RequiresAttunement: optBool(true), AttunementRestriction: optStr("by a sorcerer, warlock, or wizard"),
			PassiveEffects: optJSON([]map[string]any{{"type": "set_ac", "value": 15, "condition": "no_armor"}, {"type": "advantage", "on": "saving_throws_vs_spells"}, {"type": "modify_spell_save_dc", "modifier": 2}}),
			Description:    "This elegant garment is made from exquisite cloth and adorned with runes. Your base AC is 15 + your Dexterity modifier if you aren't wearing armor. You have advantage on saving throws against spells and other magical effects. Your spell save DC and spell attack bonus each increase by 2."},
		{ID: "scarab-of-protection", Name: "Scarab of Protection", BaseItemType: optStr("wondrous"), Rarity: "legendary",
			RequiresAttunement: optBool(true),
			PassiveEffects:     optJSON([]map[string]any{{"type": "advantage", "on": "saving_throws_vs_spells"}}),
			Charges:            optJSON(map[string]any{"max": 12, "recharge": "never"}),
			Description:        "If you fail a saving throw against a necromancy spell or a harmful effect originating from an undead creature, you can use your reaction to expend 1 charge and instead succeed on the saving throw. The scarab has 12 charges and crumbles into powder when the last charge is expended."},
		{ID: "winged-boots", Name: "Winged Boots", BaseItemType: optStr("wondrous"), Rarity: "uncommon",
			RequiresAttunement: optBool(true),
			ActiveAbilities:    optJSON([]map[string]any{{"name": "Fly", "action_type": "free", "description": "Gain a flying speed equal to your walking speed for up to 4 hours, usable in 1-minute increments."}}),
			Description:        "While you wear these boots, you have a flying speed equal to your walking speed. You can use the boots to fly for up to 4 hours, all at once or in several shorter flights, each one using a minimum of 1 minute from the duration. The boots regain 2 hours of flying capability for every 12 hours they aren't in use."},

		// ── Wands / Staves / Rods ───────────────────────────────────
		{ID: "rod-of-the-pact-keeper-plus-1", Name: "Rod of the Pact Keeper +1", BaseItemType: optStr("rod"), Rarity: "uncommon",
			RequiresAttunement: optBool(true), AttunementRestriction: optStr("by a warlock"), MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_spell_attack", "modifier": 1}, {"type": "modify_spell_save_dc", "modifier": 1}}),
			ActiveAbilities: optJSON([]map[string]any{{"name": "Recover Spell Slot", "action_type": "action", "description": "While holding the rod, you can use an action to regain one warlock spell slot. You can't use this property again until you finish a long rest."}}),
			Description:     "While holding this rod, you gain a +1 bonus to spell attack rolls and to the saving throw DCs of your warlock spells. In addition, you can regain one warlock spell slot as an action while holding the rod. You can't use this property again until you finish a long rest."},
		{ID: "staff-of-the-magi", Name: "Staff of the Magi", BaseItemType: optStr("staff"), Rarity: "legendary",
			RequiresAttunement: optBool(true), AttunementRestriction: optStr("by a sorcerer, warlock, or wizard"),
			MagicBonus:     optInt(2),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_spell_attack", "modifier": 2}, {"type": "modify_spell_save_dc", "modifier": 2}, {"type": "advantage", "on": "saving_throws_vs_spells"}}),
			Charges:        optJSON(map[string]any{"max": 50, "recharge": "dawn", "recharge_dice": "4d6+2"}),
			ActiveAbilities: optJSON([]map[string]any{
				{"name": "Spell Absorption", "action_type": "reaction", "description": "When targeted by a spell, negate the spell and absorb its energy, regaining charges equal to the spell's level."},
				{"name": "Cast Spell", "action_type": "action", "description": "Expend charges to cast various spells including fireball (7th-level, 7 charges), lightning bolt (7th-level, 7 charges), and more."},
			}),
			Description: "This staff has 50 charges and can be wielded as a magic quarterstaff that grants a +2 bonus to attack and damage rolls. While holding it, you gain a +2 bonus to spell attack rolls and to the saving throw DCs of your spells. You have advantage on saving throws against spells."},
		{ID: "wand-of-fireballs", Name: "Wand of Fireballs", BaseItemType: optStr("wand"), Rarity: "rare",
			RequiresAttunement: optBool(true), AttunementRestriction: optStr("by a spellcaster"),
			Charges: optJSON(map[string]any{"max": 7, "recharge": "dawn", "recharge_dice": "1d6+1", "destroy_on_zero": true}),
			ActiveAbilities: optJSON([]map[string]any{{"name": "Fireball", "charges_cost": 1, "action_type": "action", "spell_id": "fireball", "description": "Expend 1 or more charges to cast fireball (save DC 15). For each additional charge, the spell level increases by 1."}}),
			Description:     "This wand has 7 charges. While holding it, you can use an action to expend 1 or more of its charges to cast the fireball spell (save DC 15) from it. For 1 charge, you cast the 3rd-level version. You can increase the spell slot level by one for each additional charge you expend."},
		{ID: "wand-of-magic-missiles", Name: "Wand of Magic Missiles", BaseItemType: optStr("wand"), Rarity: "uncommon",
			Charges: optJSON(map[string]any{"max": 7, "recharge": "dawn", "recharge_dice": "1d6+1", "destroy_on_zero": true}),
			ActiveAbilities: optJSON([]map[string]any{{"name": "Magic Missile", "charges_cost": 1, "action_type": "action", "spell_id": "magic-missile", "description": "Expend 1 or more charges to cast magic missile. For 1 charge, you cast the 1st-level version. You can increase the spell slot level by one for each additional charge."}}),
			Description:     "This wand has 7 charges. While holding it, you can use an action to expend 1 or more of its charges to cast the magic missile spell from it. For 1 charge, you cast the 1st-level version of the spell. You can increase the spell slot level by one for each additional charge you expend."},
		{ID: "wand-of-the-war-mage-plus-1", Name: "Wand of the War Mage +1", BaseItemType: optStr("wand"), Rarity: "uncommon",
			RequiresAttunement: optBool(true), AttunementRestriction: optStr("by a spellcaster"), MagicBonus: optInt(1),
			PassiveEffects: optJSON([]map[string]any{{"type": "modify_spell_attack", "modifier": 1}}),
			Description:    "While holding this wand, you gain a +1 bonus to spell attack rolls. In addition, you ignore half cover when making a spell attack."},

		// ── Potions ─────────────────────────────────────────────────
		{ID: "potion-of-healing", Name: "Potion of Healing", BaseItemType: optStr("potion"), Rarity: "common",
			ActiveAbilities: optJSON([]map[string]any{{"name": "Heal", "action_type": "action", "description": "Regain 2d4+2 hit points when you drink this potion."}}),
			Description:     "You regain 2d4+2 hit points when you drink this potion. The potion's red liquid glimmers when agitated."},
		{ID: "potion-of-greater-healing", Name: "Potion of Greater Healing", BaseItemType: optStr("potion"), Rarity: "uncommon",
			ActiveAbilities: optJSON([]map[string]any{{"name": "Heal", "action_type": "action", "description": "Regain 4d4+4 hit points when you drink this potion."}}),
			Description:     "You regain 4d4+4 hit points when you drink this potion."},
		{ID: "potion-of-superior-healing", Name: "Potion of Superior Healing", BaseItemType: optStr("potion"), Rarity: "rare",
			ActiveAbilities: optJSON([]map[string]any{{"name": "Heal", "action_type": "action", "description": "Regain 8d4+8 hit points when you drink this potion."}}),
			Description:     "You regain 8d4+8 hit points when you drink this potion."},
		{ID: "potion-of-supreme-healing", Name: "Potion of Supreme Healing", BaseItemType: optStr("potion"), Rarity: "very_rare",
			ActiveAbilities: optJSON([]map[string]any{{"name": "Heal", "action_type": "action", "description": "Regain 10d4+20 hit points when you drink this potion."}}),
			Description:     "You regain 10d4+20 hit points when you drink this potion."},
	}
}
