package refdata

func srdLevel8() []sp {
	return []sp{
		{ID: "animal-shapes", Name: "Animal Shapes", Level: 8, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V", "S"}, Duration: "Concentration, up to 24 hours", Concentration: optBool(true), Description: "Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower.", ResolutionMode: "dm_required", Classes: []string{"druid"}},
		{ID: "antimagic-field", Name: "Antimagic Field", Level: 8, School: "abjuration", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a pinch of powdered iron or iron filings"), Duration: "Concentration, up to 1 hour", Concentration: optBool(true), Description: "A 10-foot-radius invisible sphere of antimagic surrounds you. Within the sphere, spells can't be cast, summoned creatures disappear, and even magic items become mundane.", ResolutionMode: "dm_required", Classes: []string{"cleric", "wizard"}, AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 10})},
		{ID: "antipathy-sympathy", Name: "Antipathy/Sympathy", Level: 8, School: "enchantment", CastingTime: "1 hour", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect"), Duration: "10 days", Description: "This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area that is no larger than a 200-foot cube.", ResolutionMode: "dm_required", Classes: []string{"druid", "wizard"}, SaveAbility: optStr("wis"), SaveEffect: optStr("no_effect")},
		{ID: "clone", Name: "Clone", Level: 8, School: "necromancy", CastingTime: "1 hour", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a diamond worth at least 1000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2000 gp that has a sealable lid"), MaterialCostGp: optFloat(3000), Duration: "Instantaneous", Description: "This spell grows an inert duplicate of a living creature as a safeguard against death.", ResolutionMode: "dm_required", Classes: []string{"wizard"}},
		{ID: "control-weather", Name: "Control Weather", Level: 8, School: "transmutation", CastingTime: "10 minutes", RangeType: "self", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("burning incense and bits of earth and wood mixed in water"), Duration: "Concentration, up to 8 hours", Concentration: optBool(true), Description: "You take control of the weather within 5 miles of you for the duration.", ResolutionMode: "dm_required", Classes: []string{"cleric", "druid", "wizard"}},
		{ID: "demiplane", Name: "Demiplane", Level: 8, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"S"}, Duration: "1 hour", Description: "You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to allow Medium creatures to pass through unhindered.", ResolutionMode: "dm_required", Classes: []string{"warlock", "wizard"}},
		{ID: "dominate-monster", Name: "Dominate Monster", Level: 8, School: "enchantment", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Concentration, up to 1 hour", Concentration: optBool(true), Description: "You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}, SaveAbility: optStr("wis"), SaveEffect: optStr("no_effect"), ConditionsApplied: []string{"charmed"}},
		{ID: "earthquake", Name: "Earthquake", Level: 8, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(500), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a pinch of dirt, a piece of rock, and a lump of clay"), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "You create a seismic disturbance at a point on the ground that you can see within range. Each creature on the ground in the area must make a Dexterity saving throw or be knocked prone.", ResolutionMode: "dm_required", Classes: []string{"cleric", "druid", "sorcerer"}, SaveAbility: optStr("dex"), SaveEffect: optStr("no_effect"), ConditionsApplied: []string{"prone"}, AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 100})},
		{ID: "feeblemind", Name: "Feeblemind", Level: 8, School: "enchantment", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(150), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a handful of clay, crystal, glass, or mineral spheres"), Duration: "Instantaneous", Description: "You blast the mind of a creature that you can see within range, attempting to shatter its intellect and personality. The target takes 4d6 psychic damage and must make an Intelligence saving throw.", ResolutionMode: "auto", Classes: []string{"bard", "druid", "warlock", "wizard"}, Damage: optJSON(map[string]any{"dice": "4d6", "type": "psychic"}), SaveAbility: optStr("int"), SaveEffect: optStr("special")},
		{ID: "glibness", Name: "Glibness", Level: 8, School: "transmutation", CastingTime: "1 action", RangeType: "self", Components: []string{"V"}, Duration: "1 hour", Description: "Until the spell ends, when you make a Charisma check, you can replace the number you roll with a 15. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful.", ResolutionMode: "auto", Classes: []string{"bard", "warlock"}},
		{ID: "holy-aura", Name: "Holy Aura", Level: 8, School: "abjuration", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a tiny reliquary worth at least 1000 gp containing a sacred relic, such as a scrap of cloth from a saint's robe or a piece of parchment from a religious text"), MaterialCostGp: optFloat(1000), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you. Creatures you choose in that radius have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them.", ResolutionMode: "auto", Classes: []string{"cleric"}, AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 30})},
		{ID: "incendiary-cloud", Name: "Incendiary Cloud", Level: 8, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(150), Components: []string{"V", "S"}, Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "A swirling cloud of smoke shot through with white-hot embers appears in a 20-foot-radius sphere centered on a point within range. A creature that starts its turn in the area takes 10d8 fire damage on a failed Dexterity save, or half as much on a successful one.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "10d8", "type": "fire"}), SaveAbility: optStr("dex"), SaveEffect: optStr("half_damage"), AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 20})},
		{ID: "maze", Name: "Maze", Level: 8, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Concentration, up to 10 minutes", Concentration: optBool(true), Description: "You banish a creature that you can see within range into a labyrinthine demiplane. The target remains there for the duration or until it escapes the maze.", ResolutionMode: "auto", Classes: []string{"wizard"}},
		{ID: "mind-blank", Name: "Mind Blank", Level: 8, School: "abjuration", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S"}, Duration: "24 hours", Description: "Until the spell ends, one willing creature you touch is immune to psychic damage, any effect that would sense its emotions or read its thoughts, divination spells, and the charmed condition.", ResolutionMode: "auto", Classes: []string{"bard", "wizard"}},
		{ID: "power-word-stun", Name: "Power Word Stun", Level: 8, School: "enchantment", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V"}, Duration: "Instantaneous", Description: "You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned.", ResolutionMode: "auto", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}, ConditionsApplied: []string{"stunned"}},
		{ID: "sunburst", Name: "Sunburst", Level: 8, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(150), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("fire and a piece of sunstone"), Duration: "Instantaneous", Description: "Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute.", ResolutionMode: "auto", Classes: []string{"druid", "sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "12d6", "type": "radiant"}), SaveAbility: optStr("con"), SaveEffect: optStr("half_damage"), ConditionsApplied: []string{"blinded"}, AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 60})},
		{ID: "telepathy", Name: "Telepathy", Level: 8, School: "evocation", CastingTime: "1 action", RangeType: "unlimited", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a pair of linked silver rings"), Duration: "24 hours", Description: "You create a telepathic link between yourself and a willing creature with which you are familiar. The creature can be anywhere on the same plane of existence as you.", ResolutionMode: "dm_required", Classes: []string{"wizard"}},
		{ID: "tsunami", Name: "Tsunami", Level: 8, School: "conjuration", CastingTime: "1 minute", RangeType: "sight", Components: []string{"V", "S"}, Duration: "Concentration, up to 6 rounds", Concentration: optBool(true), Description: "A wall of water springs into existence at a point you choose within range. Each creature in the wall's area must make a Strength saving throw. On a failure, a creature takes 6d10 bludgeoning damage, or half as much on a success.", ResolutionMode: "dm_required", Classes: []string{"druid"}, Damage: optJSON(map[string]any{"dice": "6d10", "type": "bludgeoning"}), SaveAbility: optStr("str"), SaveEffect: optStr("half_damage")},
		{ID: "abi-dalzims-horrid-wilting", Name: "Abi-Dalzim's Horrid Wilting", Level: 8, School: "necromancy", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(150), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a bit of sponge"), Duration: "Instantaneous", Description: "You draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution saving throw. A creature takes 12d8 necrotic damage on a failed save, or half as much on a successful one.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "12d8", "type": "necrotic"}), SaveAbility: optStr("con"), SaveEffect: optStr("half_damage"), AreaOfEffect: optJSON(map[string]any{"shape": "cube", "side_ft": 30})},
	}
}
