package refdata

func srdLevel7() []sp {
	return []sp{
		{ID: "conjure-celestial", Name: "Conjure Celestial", Level: 7, School: "conjuration", CastingTime: "1 minute", RangeType: "ranged", RangeFt: optInt(90), Components: []string{"V", "S"}, Duration: "Concentration, up to 1 hour", Concentration: optBool(true), Description: "You summon a celestial of challenge rating 4 or lower, which appears in an unoccupied space that you can see within range.", ResolutionMode: "dm_required", Classes: []string{"cleric"}},
		{ID: "delayed-blast-fireball", Name: "Delayed Blast Fireball", Level: 7, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(150), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a tiny ball of bat guano and sulfur"), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead. When the spell ends, the bead erupts. Each creature in a 20-foot-radius sphere must make a Dexterity saving throw. It takes 12d6 fire damage on a failed save, or half as much on a successful one.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "12d6", "type": "fire", "higher_level_dice": "1d6"}), SaveAbility: optStr("dex"), SaveEffect: optStr("half_damage"), AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 20})},
		{ID: "divine-word", Name: "Divine Word", Level: 7, School: "evocation", CastingTime: "1 bonus action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V"}, Duration: "Instantaneous", Description: "You utter a divine word, imbued with the power that shaped the world at the dawn of creation. Each creature of your choice within range that can hear you is affected based on its current hit points.", ResolutionMode: "auto", Classes: []string{"cleric"}},
		{ID: "etherealness", Name: "Etherealness", Level: 7, School: "transmutation", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S"}, Duration: "Up to 8 hours", Description: "You step into the border regions of the Ethereal Plane, in the area where it overlaps with your current plane.", ResolutionMode: "dm_required", Classes: []string{"bard", "cleric", "sorcerer", "warlock", "wizard"}},
		{ID: "finger-of-death", Name: "Finger of Death", Level: 7, School: "necromancy", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much on a successful one.", ResolutionMode: "auto", Classes: []string{"sorcerer", "warlock", "wizard"}, Damage: optJSON(map[string]any{"dice": "7d8+30", "type": "necrotic"}), SaveAbility: optStr("con"), SaveEffect: optStr("half_damage")},
		{ID: "fire-storm", Name: "Fire Storm", Level: 7, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(150), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "A storm made up of sheets of roaring flame appears in a location you choose within range. Each creature in the area must make a Dexterity saving throw. It takes 7d10 fire damage on a failed save, or half as much on a successful one.", ResolutionMode: "auto", Classes: []string{"cleric", "druid", "sorcerer"}, Damage: optJSON(map[string]any{"dice": "7d10", "type": "fire"}), SaveAbility: optStr("dex"), SaveEffect: optStr("half_damage")},
		{ID: "forcecage", Name: "Forcecage", Level: 7, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(100), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("ruby dust worth 1500 gp"), MaterialCostGp: optFloat(1500), Duration: "1 hour", Description: "An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range.", ResolutionMode: "dm_required", Classes: []string{"bard", "warlock", "wizard"}},
		{ID: "magnificent-mansion", Name: "Mordenkainen's Magnificent Mansion", Level: 7, School: "conjuration", CastingTime: "1 minute", RangeType: "ranged", RangeFt: optInt(300), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each item worth at least 5 gp"), MaterialCostGp: optFloat(15), Duration: "24 hours", Description: "You conjure an extradimensional dwelling in range that lasts for the duration.", ResolutionMode: "dm_required", Classes: []string{"bard", "wizard"}},
		{ID: "mirage-arcane", Name: "Mirage Arcane", Level: 7, School: "illusion", CastingTime: "10 minutes", RangeType: "sight", Components: []string{"V", "S"}, Duration: "10 days", Description: "You make terrain in an area up to 1 mile square look, sound, smell, and even feel like some other sort of terrain.", ResolutionMode: "dm_required", Classes: []string{"bard", "druid", "wizard"}},
		{ID: "plane-shift", Name: "Plane Shift", Level: 7, School: "conjuration", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence"), MaterialCostGp: optFloat(250), Duration: "Instantaneous", Description: "You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence.", ResolutionMode: "dm_required", Classes: []string{"cleric", "druid", "sorcerer", "warlock", "wizard"}, Teleport: optJSON(map[string]any{"target": "group", "range_ft": 0, "requires_sight": false})},
		{ID: "prismatic-spray", Name: "Prismatic Spray", Level: 7, School: "evocation", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "Eight multicolored rays of light flash from your hand. Each ray is a different color and has a different power and purpose. Each creature in a 60-foot cone must make a Dexterity saving throw.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "10d6", "type": "variable"}), SaveAbility: optStr("dex"), SaveEffect: optStr("special"), AreaOfEffect: optJSON(map[string]any{"shape": "cone", "length_ft": 60})},
		{ID: "project-image", Name: "Project Image", Level: 7, School: "illusion", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(500), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a small replica of you made from materials worth at least 5 gp"), MaterialCostGp: optFloat(5), Duration: "Concentration, up to 1 day", Concentration: optBool(true), Description: "You create an illusory copy of yourself that lasts for the duration.", ResolutionMode: "dm_required", Classes: []string{"bard", "wizard"}},
		{ID: "regenerate", Name: "Regenerate", Level: 7, School: "transmutation", CastingTime: "1 minute", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a prayer wheel and holy water"), Duration: "1 hour", Description: "You touch a creature and stimulate its natural healing ability. The target regains 4d8 + 15 hit points. For the duration of the spell, the target regains 1 hit point at the start of each of its turns.", ResolutionMode: "auto", Classes: []string{"bard", "cleric", "druid"}, Healing: optJSON(map[string]any{"dice": "4d8+15"})},
		{ID: "resurrection", Name: "Resurrection", Level: 7, School: "necromancy", CastingTime: "1 hour", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a diamond worth at least 1000 gp, which the spell consumes"), MaterialCostGp: optFloat(1000), MaterialConsumed: optBool(true), Duration: "Instantaneous", Description: "You touch a dead creature that has been dead for no more than a century, that didn't die of old age, and that isn't undead. If its soul is free and willing, the target returns to life with all its hit points.", ResolutionMode: "auto", Classes: []string{"bard", "cleric"}},
		{ID: "reverse-gravity", Name: "Reverse Gravity", Level: 7, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(100), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a lodestone and iron filings"), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "This spell reverses gravity in a 50-foot-radius, 100-foot high cylinder centered on a point within range.", ResolutionMode: "dm_required", Classes: []string{"druid", "sorcerer", "wizard"}, SaveAbility: optStr("dex"), SaveEffect: optStr("special"), AreaOfEffect: optJSON(map[string]any{"shape": "cylinder", "radius_ft": 50, "height_ft": 100})},
		{ID: "sequester", Name: "Sequester", Level: 7, School: "transmutation", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5000 gp, which the spell consumes"), MaterialCostGp: optFloat(5000), MaterialConsumed: optBool(true), Duration: "Until dispelled", Description: "By means of this spell, a willing creature or an object can be hidden away, safe from detection for the duration.", ResolutionMode: "dm_required", Classes: []string{"wizard"}},
		{ID: "simulacrum", Name: "Simulacrum", Level: 7, School: "illusion", CastingTime: "12 hours", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("snow or ice in quantities sufficient to make a life-size copy of the duplicated creature; some hair, fingernail clippings, or other piece of that creature's body placed inside the snow or ice; and powdered ruby worth 1500 gp, sprinkled over the duplicate and consumed by the spell"), MaterialCostGp: optFloat(1500), MaterialConsumed: optBool(true), Duration: "Until dispelled", Description: "You shape an illusory duplicate of one beast or humanoid that is within range for the entire casting time of the spell.", ResolutionMode: "dm_required", Classes: []string{"wizard"}},
		{ID: "symbol", Name: "Symbol", Level: 7, School: "abjuration", CastingTime: "1 minute", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("mercury, phosphorus, and powdered diamond and opal with a total value of at least 1000 gp, which the spell consumes"), MaterialCostGp: optFloat(1000), MaterialConsumed: optBool(true), Duration: "Until dispelled or triggered", Description: "When you cast this spell, you inscribe a harmful glyph either on a surface or within an object that can be closed.", ResolutionMode: "dm_required", Classes: []string{"bard", "cleric", "wizard"}},
		{ID: "teleport", Name: "Teleport", Level: 7, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(10), Components: []string{"V"}, Duration: "Instantaneous", Description: "This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select.", ResolutionMode: "dm_required", Classes: []string{"bard", "sorcerer", "wizard"}, Teleport: optJSON(map[string]any{"target": "group", "range_ft": 0, "requires_sight": false})},
	}
}
