package refdata

func srdLevel9() []sp {
	return []sp{
		{ID: "astral-projection", Name: "Astral Projection", Level: 9, School: "necromancy", CastingTime: "1 hour", RangeType: "ranged", RangeFt: optInt(10), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("for each creature you affect with this spell, you must provide one jacinth worth at least 1000 gp and one ornately carved bar of silver worth at least 100 gp, all of which the spell consumes"), MaterialCostGp: optFloat(1100), MaterialConsumed: optBool(true), Duration: "Special", Description: "You and up to eight willing creatures within range project your astral bodies into the Astral Plane.", ResolutionMode: "dm_required", Classes: []string{"cleric", "warlock", "wizard"}},
		{ID: "foresight", Name: "Foresight", Level: 9, School: "divination", CastingTime: "1 minute", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a hummingbird feather"), Duration: "8 hours", Description: "You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can't be surprised and has advantage on attack rolls, ability checks, and saving throws.", ResolutionMode: "auto", Classes: []string{"bard", "druid", "warlock", "wizard"}},
		{ID: "gate", Name: "Gate", Level: 9, School: "conjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a diamond worth at least 5000 gp"), MaterialCostGp: optFloat(5000), Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "You conjure a portal linking an unoccupied space you can see within range to a precise location on a different plane of existence.", ResolutionMode: "dm_required", Classes: []string{"cleric", "sorcerer", "wizard"}},
		{ID: "imprisonment", Name: "Imprisonment", Level: 9, School: "abjuration", CastingTime: "1 minute", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a vellum depiction or a carved statuette in the likeness of the target, and a special component that varies according to the version of the spell you choose, worth at least 500 gp per Hit Die of the target"), MaterialCostGp: optFloat(500), Duration: "Until dispelled", Description: "You create a magical restraint to hold a creature that you can see within range.", ResolutionMode: "dm_required", Classes: []string{"warlock", "wizard"}, SaveAbility: optStr("wis"), SaveEffect: optStr("no_effect")},
		{ID: "mass-heal", Name: "Mass Heal", Level: 9, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "A flood of healing energy flows from you into injured creatures around you. You restore up to 700 hit points, divided as you choose among any number of creatures that you can see within range.", ResolutionMode: "auto", Classes: []string{"cleric"}, Healing: optJSON(map[string]any{"dice": "700"})},
		{ID: "meteor-swarm", Name: "Meteor Swarm", Level: 9, School: "evocation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(5280), Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius sphere centered on each point must make a Dexterity saving throw. A creature takes 20d6 fire damage and 20d6 bludgeoning damage on a failed save, or half as much on a successful one.", ResolutionMode: "auto", Classes: []string{"sorcerer", "wizard"}, Damage: optJSON(map[string]any{"dice": "20d6+20d6", "type": "fire/bludgeoning"}), SaveAbility: optStr("dex"), SaveEffect: optStr("half_damage"), AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 40})},
		{ID: "power-word-heal", Name: "Power Word Heal", Level: 9, School: "evocation", CastingTime: "1 action", RangeType: "touch", Components: []string{"V", "S"}, Duration: "Instantaneous", Description: "A wave of healing energy washes over the creature you touch. The target regains all its hit points. If the creature is charmed, frightened, paralyzed, or stunned, the condition ends.", ResolutionMode: "auto", Classes: []string{"bard"}, Healing: optJSON(map[string]any{"dice": "all"})},
		{ID: "power-word-kill", Name: "Power Word Kill", Level: 9, School: "enchantment", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V"}, Duration: "Instantaneous", Description: "You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies.", ResolutionMode: "auto", Classes: []string{"bard", "sorcerer", "warlock", "wizard"}},
		{ID: "prismatic-wall", Name: "Prismatic Wall", Level: 9, School: "abjuration", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(60), Components: []string{"V", "S"}, Duration: "10 minutes", Description: "A shimmering, multicolored plane of light forms a vertical opaque wall—up to 90 feet long, 30 feet high, and 1 inch thick—centered on a point you can see within range.", ResolutionMode: "dm_required", Classes: []string{"wizard"}},
		{ID: "shapechange", Name: "Shapechange", Level: 9, School: "transmutation", CastingTime: "1 action", RangeType: "self", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a jade circlet worth at least 1500 gp, which you must place on your head before you cast the spell"), MaterialCostGp: optFloat(1500), Duration: "Concentration, up to 1 hour", Concentration: optBool(true), Description: "You assume the form of a different creature for the duration. The new form can be of any creature with a challenge rating equal to your level or lower.", ResolutionMode: "dm_required", Classes: []string{"druid", "wizard"}},
		{ID: "storm-of-vengeance", Name: "Storm of Vengeance", Level: 9, School: "conjuration", CastingTime: "1 action", RangeType: "sight", Components: []string{"V", "S"}, Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "A churning storm cloud forms, centered on a point you can see and spreading to a radius of 360 feet. Each creature under the cloud must make a Constitution saving throw. On a failed save, a creature takes 2d6 thunder damage and becomes deafened for 5 minutes.", ResolutionMode: "auto", Classes: []string{"druid"}, Damage: optJSON(map[string]any{"dice": "2d6", "type": "thunder"}), SaveAbility: optStr("con"), SaveEffect: optStr("half_damage"), AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 360})},
		{ID: "time-stop", Name: "Time Stop", Level: 9, School: "transmutation", CastingTime: "1 action", RangeType: "self", Components: []string{"V"}, Duration: "Instantaneous", Description: "You briefly stop the flow of time for everyone but yourself. No time passes for other creatures, while you take 1d4 + 1 turns in a row.", ResolutionMode: "dm_required", Classes: []string{"sorcerer", "wizard"}},
		{ID: "true-polymorph", Name: "True Polymorph", Level: 9, School: "transmutation", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(30), Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a drop of mercury, a dollop of gum arabic, and a wisp of smoke"), Duration: "Concentration, up to 1 hour", Concentration: optBool(true), Description: "Choose one creature or nonmagical object that you can see within range. You transform the creature into a different creature, the creature into an object, or the object into a creature.", ResolutionMode: "dm_required", Classes: []string{"bard", "warlock", "wizard"}, SaveAbility: optStr("wis"), SaveEffect: optStr("no_effect")},
		{ID: "true-resurrection", Name: "True Resurrection", Level: 9, School: "necromancy", CastingTime: "1 hour", RangeType: "touch", Components: []string{"V", "S", "M"}, MaterialDescription: optStr("a sprinkle of holy water and diamonds worth at least 25000 gp, which the spell consumes"), MaterialCostGp: optFloat(25000), MaterialConsumed: optBool(true), Duration: "Instantaneous", Description: "You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age. If the creature's soul is free and willing, the creature is restored to life with all its hit points.", ResolutionMode: "auto", Classes: []string{"cleric", "druid"}},
		{ID: "weird", Name: "Weird", Level: 9, School: "illusion", CastingTime: "1 action", RangeType: "ranged", RangeFt: optInt(120), Components: []string{"V", "S"}, Duration: "Concentration, up to 1 minute", Concentration: optBool(true), Description: "Drawing on the deepest fears of a group of creatures, you create illusory creatures in their minds, visible only to them. Each creature in a 30-foot-radius sphere centered on a point of your choice within range must make a Wisdom saving throw. On a failed save, a creature becomes frightened. It takes 4d10 psychic damage at the end of each of its turns.", ResolutionMode: "auto", Classes: []string{"wizard"}, Damage: optJSON(map[string]any{"dice": "4d10", "type": "psychic"}), SaveAbility: optStr("wis"), SaveEffect: optStr("no_effect"), ConditionsApplied: []string{"frightened"}, AreaOfEffect: optJSON(map[string]any{"shape": "sphere", "radius_ft": 30})},
		{ID: "wish", Name: "Wish", Level: 9, School: "conjuration", CastingTime: "1 action", RangeType: "self", Components: []string{"V"}, Duration: "Instantaneous", Description: "Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires.", ResolutionMode: "dm_required", Classes: []string{"sorcerer", "wizard"}},
	}
}
