// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shops.sql

package refdata

import (
	"context"

	"github.com/google/uuid"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (campaign_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, name, description, created_at, updated_at
`

type CreateShopParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, createShop, arg.CampaignID, arg.Name, arg.Description)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShopItem = `-- name: CreateShopItem :one
INSERT INTO shop_items (shop_id, item_id, name, description, price_gp, quantity, type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, item_id, name, description, price_gp, quantity, type, created_at, updated_at
`

type CreateShopItemParams struct {
	ShopID      uuid.UUID `json:"shop_id"`
	ItemID      string    `json:"item_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceGp     int32     `json:"price_gp"`
	Quantity    int32     `json:"quantity"`
	Type        string    `json:"type"`
}

func (q *Queries) CreateShopItem(ctx context.Context, arg CreateShopItemParams) (ShopItem, error) {
	row := q.db.QueryRowContext(ctx, createShopItem,
		arg.ShopID,
		arg.ItemID,
		arg.Name,
		arg.Description,
		arg.PriceGp,
		arg.Quantity,
		arg.Type,
	)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.PriceGp,
		&i.Quantity,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShop = `-- name: DeleteShop :exec
DELETE FROM shops WHERE id = $1
`

func (q *Queries) DeleteShop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShop, id)
	return err
}

const deleteShopItem = `-- name: DeleteShopItem :exec
DELETE FROM shop_items WHERE id = $1
`

func (q *Queries) DeleteShopItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShopItem, id)
	return err
}

const deleteShopItemsByShop = `-- name: DeleteShopItemsByShop :exec
DELETE FROM shop_items WHERE shop_id = $1
`

func (q *Queries) DeleteShopItemsByShop(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShopItemsByShop, shopID)
	return err
}

const getShop = `-- name: GetShop :one
SELECT id, campaign_id, name, description, created_at, updated_at FROM shops WHERE id = $1
`

func (q *Queries) GetShop(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRowContext(ctx, getShop, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShopItems = `-- name: ListShopItems :many
SELECT id, shop_id, item_id, name, description, price_gp, quantity, type, created_at, updated_at FROM shop_items WHERE shop_id = $1 ORDER BY name
`

func (q *Queries) ListShopItems(ctx context.Context, shopID uuid.UUID) ([]ShopItem, error) {
	rows, err := q.db.QueryContext(ctx, listShopItems, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShopItem{}
	for rows.Next() {
		var i ShopItem
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.PriceGp,
			&i.Quantity,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopsByCampaign = `-- name: ListShopsByCampaign :many
SELECT id, campaign_id, name, description, created_at, updated_at FROM shops WHERE campaign_id = $1 ORDER BY name
`

func (q *Queries) ListShopsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]Shop, error) {
	rows, err := q.db.QueryContext(ctx, listShopsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, description, created_at, updated_at
`

type UpdateShopParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, updateShop, arg.ID, arg.Name, arg.Description)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShopItem = `-- name: UpdateShopItem :one
UPDATE shop_items SET name = $2, description = $3, price_gp = $4, quantity = $5, updated_at = now()
WHERE id = $1
RETURNING id, shop_id, item_id, name, description, price_gp, quantity, type, created_at, updated_at
`

type UpdateShopItemParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceGp     int32     `json:"price_gp"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) UpdateShopItem(ctx context.Context, arg UpdateShopItemParams) (ShopItem, error) {
	row := q.db.QueryRowContext(ctx, updateShopItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceGp,
		arg.Quantity,
	)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.PriceGp,
		&i.Quantity,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
