// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spells.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countSpells = `-- name: CountSpells :one
SELECT count(*) FROM spells
`

func (q *Queries) CountSpells(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpells)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSpell = `-- name: GetSpell :one
SELECT id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes, created_at, updated_at FROM spells WHERE id = $1
`

func (q *Queries) GetSpell(ctx context.Context, id string) (Spell, error) {
	row := q.db.QueryRowContext(ctx, getSpell, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.School,
		&i.CastingTime,
		&i.RangeFt,
		&i.RangeType,
		pq.Array(&i.Components),
		&i.MaterialDescription,
		&i.MaterialCostGp,
		&i.MaterialConsumed,
		&i.Duration,
		&i.Concentration,
		&i.Ritual,
		&i.Description,
		&i.HigherLevels,
		&i.Damage,
		&i.Healing,
		&i.SaveAbility,
		&i.SaveEffect,
		&i.AttackType,
		&i.AreaOfEffect,
		pq.Array(&i.ConditionsApplied),
		&i.Teleport,
		&i.ResolutionMode,
		pq.Array(&i.Classes),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpells = `-- name: ListSpells :many
SELECT id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes, created_at, updated_at FROM spells ORDER BY name
`

func (q *Queries) ListSpells(ctx context.Context) ([]Spell, error) {
	rows, err := q.db.QueryContext(ctx, listSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.RangeFt,
			&i.RangeType,
			pq.Array(&i.Components),
			&i.MaterialDescription,
			&i.MaterialCostGp,
			&i.MaterialConsumed,
			&i.Duration,
			&i.Concentration,
			&i.Ritual,
			&i.Description,
			&i.HigherLevels,
			&i.Damage,
			&i.Healing,
			&i.SaveAbility,
			&i.SaveEffect,
			&i.AttackType,
			&i.AreaOfEffect,
			pq.Array(&i.ConditionsApplied),
			&i.Teleport,
			&i.ResolutionMode,
			pq.Array(&i.Classes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpellsByClass = `-- name: ListSpellsByClass :many
SELECT id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes, created_at, updated_at FROM spells WHERE $1::text = ANY(classes) ORDER BY level, name
`

func (q *Queries) ListSpellsByClass(ctx context.Context, dollar_1 string) ([]Spell, error) {
	rows, err := q.db.QueryContext(ctx, listSpellsByClass, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.RangeFt,
			&i.RangeType,
			pq.Array(&i.Components),
			&i.MaterialDescription,
			&i.MaterialCostGp,
			&i.MaterialConsumed,
			&i.Duration,
			&i.Concentration,
			&i.Ritual,
			&i.Description,
			&i.HigherLevels,
			&i.Damage,
			&i.Healing,
			&i.SaveAbility,
			&i.SaveEffect,
			&i.AttackType,
			&i.AreaOfEffect,
			pq.Array(&i.ConditionsApplied),
			&i.Teleport,
			&i.ResolutionMode,
			pq.Array(&i.Classes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpellsByLevel = `-- name: ListSpellsByLevel :many
SELECT id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes, created_at, updated_at FROM spells WHERE level = $1 ORDER BY name
`

func (q *Queries) ListSpellsByLevel(ctx context.Context, level int32) ([]Spell, error) {
	rows, err := q.db.QueryContext(ctx, listSpellsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.RangeFt,
			&i.RangeType,
			pq.Array(&i.Components),
			&i.MaterialDescription,
			&i.MaterialCostGp,
			&i.MaterialConsumed,
			&i.Duration,
			&i.Concentration,
			&i.Ritual,
			&i.Description,
			&i.HigherLevels,
			&i.Damage,
			&i.Healing,
			&i.SaveAbility,
			&i.SaveEffect,
			&i.AttackType,
			&i.AreaOfEffect,
			pq.Array(&i.ConditionsApplied),
			&i.Teleport,
			&i.ResolutionMode,
			pq.Array(&i.Classes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpellsByResolutionMode = `-- name: ListSpellsByResolutionMode :many
SELECT id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes, created_at, updated_at FROM spells WHERE resolution_mode = $1 ORDER BY level, name
`

func (q *Queries) ListSpellsByResolutionMode(ctx context.Context, resolutionMode string) ([]Spell, error) {
	rows, err := q.db.QueryContext(ctx, listSpellsByResolutionMode, resolutionMode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.RangeFt,
			&i.RangeType,
			pq.Array(&i.Components),
			&i.MaterialDescription,
			&i.MaterialCostGp,
			&i.MaterialConsumed,
			&i.Duration,
			&i.Concentration,
			&i.Ritual,
			&i.Description,
			&i.HigherLevels,
			&i.Damage,
			&i.Healing,
			&i.SaveAbility,
			&i.SaveEffect,
			&i.AttackType,
			&i.AreaOfEffect,
			pq.Array(&i.ConditionsApplied),
			&i.Teleport,
			&i.ResolutionMode,
			pq.Array(&i.Classes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpellsBySchool = `-- name: ListSpellsBySchool :many
SELECT id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes, created_at, updated_at FROM spells WHERE school = $1 ORDER BY level, name
`

func (q *Queries) ListSpellsBySchool(ctx context.Context, school string) ([]Spell, error) {
	rows, err := q.db.QueryContext(ctx, listSpellsBySchool, school)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.RangeFt,
			&i.RangeType,
			pq.Array(&i.Components),
			&i.MaterialDescription,
			&i.MaterialCostGp,
			&i.MaterialConsumed,
			&i.Duration,
			&i.Concentration,
			&i.Ritual,
			&i.Description,
			&i.HigherLevels,
			&i.Damage,
			&i.Healing,
			&i.SaveAbility,
			&i.SaveEffect,
			&i.AttackType,
			&i.AreaOfEffect,
			pq.Array(&i.ConditionsApplied),
			&i.Teleport,
			&i.ResolutionMode,
			pq.Array(&i.Classes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSpell = `-- name: UpsertSpell :exec
INSERT INTO spells (id, name, level, school, casting_time, range_ft, range_type, components, material_description, material_cost_gp, material_consumed, duration, concentration, ritual, description, higher_levels, damage, healing, save_ability, save_effect, attack_type, area_of_effect, conditions_applied, teleport, resolution_mode, classes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    level = EXCLUDED.level,
    school = EXCLUDED.school,
    casting_time = EXCLUDED.casting_time,
    range_ft = EXCLUDED.range_ft,
    range_type = EXCLUDED.range_type,
    components = EXCLUDED.components,
    material_description = EXCLUDED.material_description,
    material_cost_gp = EXCLUDED.material_cost_gp,
    material_consumed = EXCLUDED.material_consumed,
    duration = EXCLUDED.duration,
    concentration = EXCLUDED.concentration,
    ritual = EXCLUDED.ritual,
    description = EXCLUDED.description,
    higher_levels = EXCLUDED.higher_levels,
    damage = EXCLUDED.damage,
    healing = EXCLUDED.healing,
    save_ability = EXCLUDED.save_ability,
    save_effect = EXCLUDED.save_effect,
    attack_type = EXCLUDED.attack_type,
    area_of_effect = EXCLUDED.area_of_effect,
    conditions_applied = EXCLUDED.conditions_applied,
    teleport = EXCLUDED.teleport,
    resolution_mode = EXCLUDED.resolution_mode,
    classes = EXCLUDED.classes,
    updated_at = now()
`

type UpsertSpellParams struct {
	ID                  string                `json:"id"`
	Name                string                `json:"name"`
	Level               int32                 `json:"level"`
	School              string                `json:"school"`
	CastingTime         string                `json:"casting_time"`
	RangeFt             sql.NullInt32         `json:"range_ft"`
	RangeType           string                `json:"range_type"`
	Components          []string              `json:"components"`
	MaterialDescription sql.NullString        `json:"material_description"`
	MaterialCostGp      sql.NullFloat64       `json:"material_cost_gp"`
	MaterialConsumed    sql.NullBool          `json:"material_consumed"`
	Duration            string                `json:"duration"`
	Concentration       sql.NullBool          `json:"concentration"`
	Ritual              sql.NullBool          `json:"ritual"`
	Description         string                `json:"description"`
	HigherLevels        sql.NullString        `json:"higher_levels"`
	Damage              pqtype.NullRawMessage `json:"damage"`
	Healing             pqtype.NullRawMessage `json:"healing"`
	SaveAbility         sql.NullString        `json:"save_ability"`
	SaveEffect          sql.NullString        `json:"save_effect"`
	AttackType          sql.NullString        `json:"attack_type"`
	AreaOfEffect        pqtype.NullRawMessage `json:"area_of_effect"`
	ConditionsApplied   []string              `json:"conditions_applied"`
	Teleport            pqtype.NullRawMessage `json:"teleport"`
	ResolutionMode      string                `json:"resolution_mode"`
	Classes             []string              `json:"classes"`
}

func (q *Queries) UpsertSpell(ctx context.Context, arg UpsertSpellParams) error {
	_, err := q.db.ExecContext(ctx, upsertSpell,
		arg.ID,
		arg.Name,
		arg.Level,
		arg.School,
		arg.CastingTime,
		arg.RangeFt,
		arg.RangeType,
		pq.Array(arg.Components),
		arg.MaterialDescription,
		arg.MaterialCostGp,
		arg.MaterialConsumed,
		arg.Duration,
		arg.Concentration,
		arg.Ritual,
		arg.Description,
		arg.HigherLevels,
		arg.Damage,
		arg.Healing,
		arg.SaveAbility,
		arg.SaveEffect,
		arg.AttackType,
		arg.AreaOfEffect,
		pq.Array(arg.ConditionsApplied),
		arg.Teleport,
		arg.ResolutionMode,
		pq.Array(arg.Classes),
	)
	return err
}
