// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turns.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearTurnTimeout = `-- name: ClearTurnTimeout :one
UPDATE turns SET timeout_at = NULL WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

func (q *Queries) ClearTurnTimeout(ctx context.Context, id uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, clearTurnTimeout, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const completeTurn = `-- name: CompleteTurn :one
UPDATE turns SET status = 'completed', completed_at = now() WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

func (q *Queries) CompleteTurn(ctx context.Context, id uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, completeTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns (encounter_id, combatant_id, round_number, status, movement_remaining_ft, attacks_remaining, started_at, timeout_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

type CreateTurnParams struct {
	EncounterID         uuid.UUID    `json:"encounter_id"`
	CombatantID         uuid.UUID    `json:"combatant_id"`
	RoundNumber         int32        `json:"round_number"`
	Status              string       `json:"status"`
	MovementRemainingFt int32        `json:"movement_remaining_ft"`
	AttacksRemaining    int32        `json:"attacks_remaining"`
	StartedAt           sql.NullTime `json:"started_at"`
	TimeoutAt           sql.NullTime `json:"timeout_at"`
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRowContext(ctx, createTurn,
		arg.EncounterID,
		arg.CombatantID,
		arg.RoundNumber,
		arg.Status,
		arg.MovementRemainingFt,
		arg.AttacksRemaining,
		arg.StartedAt,
		arg.TimeoutAt,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const getActiveTurnByEncounterID = `-- name: GetActiveTurnByEncounterID :one
SELECT id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at FROM turns WHERE encounter_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveTurnByEncounterID(ctx context.Context, encounterID uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, getActiveTurnByEncounterID, encounterID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at FROM turns WHERE id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const listActiveTurnsByEncounterID = `-- name: ListActiveTurnsByEncounterID :many
SELECT id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at FROM turns WHERE encounter_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveTurnsByEncounterID(ctx context.Context, encounterID uuid.UUID) ([]Turn, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTurnsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.RoundNumber,
			&i.Status,
			&i.MovementRemainingFt,
			&i.ActionUsed,
			&i.BonusActionUsed,
			&i.BonusActionSpellCast,
			&i.ActionSpellCast,
			&i.ReactionUsed,
			&i.FreeInteractUsed,
			&i.AttacksRemaining,
			&i.HasDisengaged,
			&i.ActionSurged,
			&i.StartedAt,
			&i.TimeoutAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.HasStoodThisTurn,
			&i.NudgeSentAt,
			&i.WarningSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnsByEncounterAndRound = `-- name: ListTurnsByEncounterAndRound :many
SELECT id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at FROM turns WHERE encounter_id = $1 AND round_number = $2 ORDER BY created_at ASC
`

type ListTurnsByEncounterAndRoundParams struct {
	EncounterID uuid.UUID `json:"encounter_id"`
	RoundNumber int32     `json:"round_number"`
}

func (q *Queries) ListTurnsByEncounterAndRound(ctx context.Context, arg ListTurnsByEncounterAndRoundParams) ([]Turn, error) {
	rows, err := q.db.QueryContext(ctx, listTurnsByEncounterAndRound, arg.EncounterID, arg.RoundNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.RoundNumber,
			&i.Status,
			&i.MovementRemainingFt,
			&i.ActionUsed,
			&i.BonusActionUsed,
			&i.BonusActionSpellCast,
			&i.ActionSpellCast,
			&i.ReactionUsed,
			&i.FreeInteractUsed,
			&i.AttacksRemaining,
			&i.HasDisengaged,
			&i.ActionSurged,
			&i.StartedAt,
			&i.TimeoutAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.HasStoodThisTurn,
			&i.NudgeSentAt,
			&i.WarningSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnsNeedingNudge = `-- name: ListTurnsNeedingNudge :many
SELECT id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at FROM turns
WHERE status = 'active'
  AND timeout_at IS NOT NULL
  AND started_at IS NOT NULL
  AND nudge_sent_at IS NULL
  AND now() >= started_at + (timeout_at - started_at) * 0.5
ORDER BY started_at ASC
`

func (q *Queries) ListTurnsNeedingNudge(ctx context.Context) ([]Turn, error) {
	rows, err := q.db.QueryContext(ctx, listTurnsNeedingNudge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.RoundNumber,
			&i.Status,
			&i.MovementRemainingFt,
			&i.ActionUsed,
			&i.BonusActionUsed,
			&i.BonusActionSpellCast,
			&i.ActionSpellCast,
			&i.ReactionUsed,
			&i.FreeInteractUsed,
			&i.AttacksRemaining,
			&i.HasDisengaged,
			&i.ActionSurged,
			&i.StartedAt,
			&i.TimeoutAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.HasStoodThisTurn,
			&i.NudgeSentAt,
			&i.WarningSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnsNeedingWarning = `-- name: ListTurnsNeedingWarning :many
SELECT id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at FROM turns
WHERE status = 'active'
  AND timeout_at IS NOT NULL
  AND started_at IS NOT NULL
  AND warning_sent_at IS NULL
  AND now() >= started_at + (timeout_at - started_at) * 0.75
ORDER BY started_at ASC
`

func (q *Queries) ListTurnsNeedingWarning(ctx context.Context) ([]Turn, error) {
	rows, err := q.db.QueryContext(ctx, listTurnsNeedingWarning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CombatantID,
			&i.RoundNumber,
			&i.Status,
			&i.MovementRemainingFt,
			&i.ActionUsed,
			&i.BonusActionUsed,
			&i.BonusActionSpellCast,
			&i.ActionSpellCast,
			&i.ReactionUsed,
			&i.FreeInteractUsed,
			&i.AttacksRemaining,
			&i.HasDisengaged,
			&i.ActionSurged,
			&i.StartedAt,
			&i.TimeoutAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.HasStoodThisTurn,
			&i.NudgeSentAt,
			&i.WarningSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTurnTimeout = `-- name: SetTurnTimeout :one
UPDATE turns SET timeout_at = $2, started_at = COALESCE(started_at, now()) WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

type SetTurnTimeoutParams struct {
	ID        uuid.UUID    `json:"id"`
	TimeoutAt sql.NullTime `json:"timeout_at"`
}

func (q *Queries) SetTurnTimeout(ctx context.Context, arg SetTurnTimeoutParams) (Turn, error) {
	row := q.db.QueryRowContext(ctx, setTurnTimeout, arg.ID, arg.TimeoutAt)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const skipTurn = `-- name: SkipTurn :one
UPDATE turns SET status = 'skipped', completed_at = now() WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

func (q *Queries) SkipTurn(ctx context.Context, id uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, skipTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const updateTurnActions = `-- name: UpdateTurnActions :one
UPDATE turns SET
    movement_remaining_ft = $2,
    action_used = $3,
    bonus_action_used = $4,
    bonus_action_spell_cast = $5,
    action_spell_cast = $6,
    reaction_used = $7,
    free_interact_used = $8,
    attacks_remaining = $9,
    has_disengaged = $10,
    action_surged = $11,
    has_stood_this_turn = $12
WHERE id = $1
RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

type UpdateTurnActionsParams struct {
	ID                   uuid.UUID `json:"id"`
	MovementRemainingFt  int32     `json:"movement_remaining_ft"`
	ActionUsed           bool      `json:"action_used"`
	BonusActionUsed      bool      `json:"bonus_action_used"`
	BonusActionSpellCast bool      `json:"bonus_action_spell_cast"`
	ActionSpellCast      bool      `json:"action_spell_cast"`
	ReactionUsed         bool      `json:"reaction_used"`
	FreeInteractUsed     bool      `json:"free_interact_used"`
	AttacksRemaining     int32     `json:"attacks_remaining"`
	HasDisengaged        bool      `json:"has_disengaged"`
	ActionSurged         bool      `json:"action_surged"`
	HasStoodThisTurn     bool      `json:"has_stood_this_turn"`
}

func (q *Queries) UpdateTurnActions(ctx context.Context, arg UpdateTurnActionsParams) (Turn, error) {
	row := q.db.QueryRowContext(ctx, updateTurnActions,
		arg.ID,
		arg.MovementRemainingFt,
		arg.ActionUsed,
		arg.BonusActionUsed,
		arg.BonusActionSpellCast,
		arg.ActionSpellCast,
		arg.ReactionUsed,
		arg.FreeInteractUsed,
		arg.AttacksRemaining,
		arg.HasDisengaged,
		arg.ActionSurged,
		arg.HasStoodThisTurn,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const updateTurnNudgeSent = `-- name: UpdateTurnNudgeSent :one
UPDATE turns SET nudge_sent_at = now() WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

func (q *Queries) UpdateTurnNudgeSent(ctx context.Context, id uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, updateTurnNudgeSent, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const updateTurnTimeout = `-- name: UpdateTurnTimeout :one
UPDATE turns SET timeout_at = $2 WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

type UpdateTurnTimeoutParams struct {
	ID        uuid.UUID    `json:"id"`
	TimeoutAt sql.NullTime `json:"timeout_at"`
}

func (q *Queries) UpdateTurnTimeout(ctx context.Context, arg UpdateTurnTimeoutParams) (Turn, error) {
	row := q.db.QueryRowContext(ctx, updateTurnTimeout, arg.ID, arg.TimeoutAt)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}

const updateTurnWarningSent = `-- name: UpdateTurnWarningSent :one
UPDATE turns SET warning_sent_at = now() WHERE id = $1 RETURNING id, encounter_id, combatant_id, round_number, status, movement_remaining_ft, action_used, bonus_action_used, bonus_action_spell_cast, action_spell_cast, reaction_used, free_interact_used, attacks_remaining, has_disengaged, action_surged, started_at, timeout_at, completed_at, created_at, has_stood_this_turn, nudge_sent_at, warning_sent_at
`

func (q *Queries) UpdateTurnWarningSent(ctx context.Context, id uuid.UUID) (Turn, error) {
	row := q.db.QueryRowContext(ctx, updateTurnWarningSent, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CombatantID,
		&i.RoundNumber,
		&i.Status,
		&i.MovementRemainingFt,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.BonusActionSpellCast,
		&i.ActionSpellCast,
		&i.ReactionUsed,
		&i.FreeInteractUsed,
		&i.AttacksRemaining,
		&i.HasDisengaged,
		&i.ActionSurged,
		&i.StartedAt,
		&i.TimeoutAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.HasStoodThisTurn,
		&i.NudgeSentAt,
		&i.WarningSentAt,
	)
	return i, err
}
