// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weapons.sql

package refdata

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countWeapons = `-- name: CountWeapons :one
SELECT count(*) FROM weapons
`

func (q *Queries) CountWeapons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeapons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHomebrewWeapon = `-- name: DeleteHomebrewWeapon :execrows
DELETE FROM weapons WHERE id = $1 AND homebrew = true AND campaign_id = $2
`

type DeleteHomebrewWeaponParams struct {
	ID         string        `json:"id"`
	CampaignID uuid.NullUUID `json:"campaign_id"`
}

func (q *Queries) DeleteHomebrewWeapon(ctx context.Context, arg DeleteHomebrewWeaponParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHomebrewWeapon, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWeapon = `-- name: GetWeapon :one
SELECT id, name, damage, damage_type, weight_lb, properties, range_normal_ft, range_long_ft, versatile_damage, weapon_type, created_at, updated_at, campaign_id, homebrew, source FROM weapons WHERE id = $1
`

func (q *Queries) GetWeapon(ctx context.Context, id string) (Weapon, error) {
	row := q.db.QueryRowContext(ctx, getWeapon, id)
	var i Weapon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Damage,
		&i.DamageType,
		&i.WeightLb,
		pq.Array(&i.Properties),
		&i.RangeNormalFt,
		&i.RangeLongFt,
		&i.VersatileDamage,
		&i.WeaponType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
		&i.Homebrew,
		&i.Source,
	)
	return i, err
}

const listWeapons = `-- name: ListWeapons :many
SELECT id, name, damage, damage_type, weight_lb, properties, range_normal_ft, range_long_ft, versatile_damage, weapon_type, created_at, updated_at, campaign_id, homebrew, source FROM weapons ORDER BY name
`

func (q *Queries) ListWeapons(ctx context.Context) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, listWeapons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Weapon{}
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Damage,
			&i.DamageType,
			&i.WeightLb,
			pq.Array(&i.Properties),
			&i.RangeNormalFt,
			&i.RangeLongFt,
			&i.VersatileDamage,
			&i.WeaponType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignID,
			&i.Homebrew,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWeapon = `-- name: UpsertWeapon :exec
INSERT INTO weapons (id, name, damage, damage_type, weight_lb, properties, range_normal_ft, range_long_ft, versatile_damage, weapon_type, campaign_id, homebrew, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    damage = EXCLUDED.damage,
    damage_type = EXCLUDED.damage_type,
    weight_lb = EXCLUDED.weight_lb,
    properties = EXCLUDED.properties,
    range_normal_ft = EXCLUDED.range_normal_ft,
    range_long_ft = EXCLUDED.range_long_ft,
    versatile_damage = EXCLUDED.versatile_damage,
    weapon_type = EXCLUDED.weapon_type,
    campaign_id = EXCLUDED.campaign_id,
    homebrew = EXCLUDED.homebrew,
    source = EXCLUDED.source,
    updated_at = now()
`

type UpsertWeaponParams struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Damage          string          `json:"damage"`
	DamageType      string          `json:"damage_type"`
	WeightLb        sql.NullFloat64 `json:"weight_lb"`
	Properties      []string        `json:"properties"`
	RangeNormalFt   sql.NullInt32   `json:"range_normal_ft"`
	RangeLongFt     sql.NullInt32   `json:"range_long_ft"`
	VersatileDamage sql.NullString  `json:"versatile_damage"`
	WeaponType      string          `json:"weapon_type"`
	CampaignID      uuid.NullUUID   `json:"campaign_id"`
	Homebrew        sql.NullBool    `json:"homebrew"`
	Source          sql.NullString  `json:"source"`
}

func (q *Queries) UpsertWeapon(ctx context.Context, arg UpsertWeaponParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeapon,
		arg.ID,
		arg.Name,
		arg.Damage,
		arg.DamageType,
		arg.WeightLb,
		pq.Array(arg.Properties),
		arg.RangeNormalFt,
		arg.RangeLongFt,
		arg.VersatileDamage,
		arg.WeaponType,
		arg.CampaignID,
		arg.Homebrew,
		arg.Source,
	)
	return err
}
