// gen_backgrounds generates internal/portal/backgrounds_gen.go from the
// canonical background data in portal/svelte/src/lib/backgrounds.json, so the
// Go backend and the Svelte builder share ONE source of truth for background
// skills and starting equipment (the drift between hand-maintained copies
// caused the guild-artisan / folk-hero submit 400; see docs/live-play
// ISSUE-013).
//
// Run via `go generate ./internal/portal/...` or `make backgrounds-check`
// (which also fails CI when the committed generated file drifts from the JSON).
//
// Flags:
//
//	-in   path to backgrounds.json   (default ../../portal/svelte/src/lib/backgrounds.json)
//	-out  generated Go file to write (default backgrounds_gen.go)
//
// Defaults assume the working directory is internal/portal (where the
// //go:generate directive lives). Exit codes: 0 ok, non-zero on IO/parse error.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"text/template"
)

// background is the subset of each backgrounds.json entry the Go side needs.
// The JSON carries more (tools, languages, feature) for the frontend; those are
// intentionally ignored here.
type background struct {
	Skills    []string `json:"skills"`
	Equipment []string `json:"equipment"`
}

const fileTmpl = `// Code generated by scripts/gen_backgrounds; DO NOT EDIT.
// Source: portal/svelte/src/lib/backgrounds.json
// Regenerate: go generate ./internal/portal/...  (or: make backgrounds-check)

package portal

// backgroundSkillsByID holds each background's two fixed PHB skill
// proficiencies, keyed by the builder's kebab-case slug.
var backgroundSkillsByID = map[string][]string{
{{- range .}}
	{{printf "%q" .ID}}: {{goStrings .Skills}},
{{- end}}
}

// backgroundEquipmentByID holds each background's SRD starting-equipment pack,
// keyed by the builder's kebab-case slug.
var backgroundEquipmentByID = map[string][]string{
{{- range .}}
	{{printf "%q" .ID}}: {{goStrings .Equipment}},
{{- end}}
}
`

type entry struct {
	ID        string
	Skills    []string
	Equipment []string
}

func goStrings(items []string) string {
	if len(items) == 0 {
		return "nil"
	}
	var b bytes.Buffer
	b.WriteByte('{')
	for i, s := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", s)
	}
	b.WriteByte('}')
	return b.String()
}

func run(inPath, outPath string) error {
	raw, err := os.ReadFile(inPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", inPath, err)
	}
	var data map[string]background
	if err := json.Unmarshal(raw, &data); err != nil {
		return fmt.Errorf("parse %s: %w", inPath, err)
	}

	ids := make([]string, 0, len(data))
	for id := range data {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	entries := make([]entry, 0, len(ids))
	for _, id := range ids {
		entries = append(entries, entry{ID: id, Skills: data[id].Skills, Equipment: data[id].Equipment})
	}

	tmpl := template.Must(template.New("gen").Funcs(template.FuncMap{"goStrings": goStrings}).Parse(fileTmpl))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, entries); err != nil {
		return fmt.Errorf("render template: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

func main() {
	in := flag.String("in", "../../portal/svelte/src/lib/backgrounds.json", "path to canonical backgrounds.json")
	out := flag.String("out", "backgrounds_gen.go", "generated Go file to write")
	flag.Parse()
	if err := run(*in, *out); err != nil {
		fmt.Fprintln(os.Stderr, "gen_backgrounds:", err)
		os.Exit(1)
	}
}
