package levelup

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"

	"github.com/ab/dndnd/internal/character"
	"github.com/ab/dndnd/internal/refdata"
)

// characterStoreAdapter bridges *refdata.Queries onto levelup.CharacterStore,
// translating between json.RawMessage (used by the service) and
// pqtype.NullRawMessage (generated by sqlc).
type characterStoreAdapter struct {
	queries *refdata.Queries
}

// NewCharacterStoreAdapter returns a CharacterStore backed by refdata.Queries.
func NewCharacterStoreAdapter(q *refdata.Queries) CharacterStore {
	return &characterStoreAdapter{queries: q}
}

func (a *characterStoreAdapter) GetCharacterForLevelUp(ctx context.Context, id uuid.UUID) (*StoredCharacter, error) {
	row, err := a.queries.GetCharacterForLevelUp(ctx, id)
	if err != nil {
		return nil, err
	}
	return &StoredCharacter{
		ID:               row.ID,
		Name:             row.Name,
		DiscordUserID:    row.DiscordUserID,
		Level:            row.Level,
		HPMax:            row.HpMax,
		HPCurrent:        row.HpCurrent,
		ProficiencyBonus: row.ProficiencyBonus,
		Classes:          row.Classes,
		AbilityScores:    row.AbilityScores,
		SpellSlots:       rawFromNullable(row.SpellSlots),
		PactMagicSlots:   rawFromNullable(row.PactMagicSlots),
		Features:         rawFromNullable(row.Features),
		Proficiencies:    rawFromNullable(row.Proficiencies),
	}, nil
}

func (a *characterStoreAdapter) UpdateCharacterStats(ctx context.Context, id uuid.UUID, update StatsUpdate) error {
	// Preload the row so nil optional JSONB fields from Service.ApplyLevelUp
	// (common for non-casters) don't clobber existing spell slots / features.
	existing, err := a.queries.GetCharacterForLevelUp(ctx, id)
	if err != nil {
		return fmt.Errorf("loading character for stats update: %w", err)
	}

	return a.queries.UpdateCharacterLevelUpStats(ctx, refdata.UpdateCharacterLevelUpStatsParams{
		ID:               id,
		Level:            int32(update.Level),
		HpMax:            int32(update.HPMax),
		HpCurrent:        int32(update.HPCurrent),
		ProficiencyBonus: int32(update.ProficiencyBonus),
		Classes:          update.Classes,
		SpellSlots:       pickNullable(update.SpellSlots, existing.SpellSlots),
		PactMagicSlots:   pickNullable(update.PactMagicSlots, existing.PactMagicSlots),
		Features:         pickNullable(update.Features, existing.Features),
	})
}

// pickNullable returns a NullRawMessage wrapping update when non-empty, else
// falls back to the existing column value. Used by UpdateCharacterStats to
// preserve JSONB fields the caller did not supply.
func pickNullable(update json.RawMessage, existing pqtype.NullRawMessage) pqtype.NullRawMessage {
	if len(update) == 0 {
		return existing
	}
	return pqtype.NullRawMessage{RawMessage: update, Valid: true}
}

func (a *characterStoreAdapter) UpdateAbilityScores(ctx context.Context, id uuid.UUID, scores json.RawMessage) error {
	return a.queries.UpdateCharacterAbilityScores(ctx, refdata.UpdateCharacterAbilityScoresParams{
		ID:            id,
		AbilityScores: scores,
	})
}

func (a *characterStoreAdapter) UpdateFeatures(ctx context.Context, id uuid.UUID, features json.RawMessage) error {
	return a.queries.UpdateCharacterFeaturesOnly(ctx, refdata.UpdateCharacterFeaturesOnlyParams{
		ID:       id,
		Features: pqtype.NullRawMessage{RawMessage: features, Valid: true},
	})
}

func (a *characterStoreAdapter) UpdateProficiencies(ctx context.Context, id uuid.UUID, proficiencies json.RawMessage) error {
	return a.queries.UpdateCharacterProficienciesOnly(ctx, refdata.UpdateCharacterProficienciesOnlyParams{
		ID:            id,
		Proficiencies: pqtype.NullRawMessage{RawMessage: proficiencies, Valid: true},
	})
}

// GetACInputs loads the character's equipped body armor, off-hand shield, and
// Unarmored Defense formula so the service can recompute base AC. Mirrors
// combat's hasEquippedShield / lookupBodyArmor: the off-hand counts as a shield
// only when the equipped item is armor of type "shield", and a body-armor slot
// holding a shield (or an unknown id) is treated as no armor.
func (a *characterStoreAdapter) GetACInputs(ctx context.Context, id uuid.UUID) (ACInputs, error) {
	ch, err := a.queries.GetCharacter(ctx, id)
	if err != nil {
		return ACInputs{}, fmt.Errorf("loading character: %w", err)
	}

	in := ACInputs{}
	if ch.AcFormula.Valid {
		in.ACFormula = ch.AcFormula.String
	}
	if ch.EquippedArmor.Valid && ch.EquippedArmor.String != "" {
		if ar, err := a.queries.GetArmor(ctx, ch.EquippedArmor.String); err == nil && ar.ArmorType != "shield" {
			in.Armor = &character.ArmorInfo{
				ACBase:   int(ar.AcBase),
				DexBonus: ar.AcDexBonus.Valid && ar.AcDexBonus.Bool,
			}
			if ar.AcDexMax.Valid {
				in.Armor.DexMax = int(ar.AcDexMax.Int32)
			}
		}
	}
	if ch.EquippedOffHand.Valid && ch.EquippedOffHand.String != "" {
		oa, err := a.queries.GetArmor(ctx, ch.EquippedOffHand.String)
		in.HasShield = err == nil && oa.ArmorType == "shield"
	}
	return in, nil
}

// UpdateAC persists a recomputed base AC.
func (a *characterStoreAdapter) UpdateAC(ctx context.Context, id uuid.UUID, ac int32) error {
	return a.queries.UpdateCharacterAC(ctx, refdata.UpdateCharacterACParams{ID: id, Ac: ac})
}

// classStoreAdapter wraps *refdata.Queries to satisfy levelup.ClassStore.
type classStoreAdapter struct {
	queries *refdata.Queries
}

// NewClassStoreAdapter returns a ClassStore backed by refdata.Queries.
func NewClassStoreAdapter(q *refdata.Queries) ClassStore {
	return &classStoreAdapter{queries: q}
}

func (a *classStoreAdapter) GetClassRefData(ctx context.Context, classID string) (*ClassRefData, error) {
	row, err := a.queries.GetClass(ctx, classID)
	if err != nil {
		return nil, err
	}

	ref := &ClassRefData{
		HitDie:        row.HitDie,
		SubclassLevel: int(row.SubclassLevel),
	}

	if row.Spellcasting.Valid && len(row.Spellcasting.RawMessage) > 0 {
		sc, scErr := parseClassSpellcasting(row.Spellcasting.RawMessage)
		if scErr != nil {
			return nil, fmt.Errorf("parsing spellcasting for %s: %w", classID, scErr)
		}
		ref.Spellcasting = sc
	}

	attacks, err := parseAttacksPerAction(row.AttacksPerAction)
	if err != nil {
		return nil, fmt.Errorf("parsing attacks_per_action for %s: %w", classID, err)
	}
	ref.AttacksPerAction = attacks

	if len(row.Subclasses) > 0 {
		var subs map[string]any
		if err := json.Unmarshal(row.Subclasses, &subs); err == nil {
			ref.Subclasses = subs
		}
	}

	if len(row.FeaturesByLevel) > 0 {
		var features map[string][]character.Feature
		if err := json.Unmarshal(row.FeaturesByLevel, &features); err == nil {
			ref.FeaturesByLevel = features
		}
	}

	return ref, nil
}

// rawFromNullable collapses a pqtype.NullRawMessage into a json.RawMessage,
// returning nil when the column is SQL NULL.
func rawFromNullable(m pqtype.NullRawMessage) json.RawMessage {
	if !m.Valid {
		return nil
	}
	return m.RawMessage
}

// parseClassSpellcasting decodes spellcasting JSONB into ClassSpellcasting.
// The DB stores {"ability","slot_progression"} but ClassSpellcasting's json
// tags expect "spell_ability", so we translate via an intermediate struct.
func parseClassSpellcasting(data json.RawMessage) (*character.ClassSpellcasting, error) {
	var raw struct {
		Ability         string `json:"ability"`
		SlotProgression string `json:"slot_progression"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	return &character.ClassSpellcasting{
		SpellAbility:    raw.Ability,
		SlotProgression: raw.SlotProgression,
	}, nil
}

// parseAttacksPerAction turns a JSONB blob shaped like `{"1":1,"5":2}` into
// the int->int map the level-up calculator expects.
func parseAttacksPerAction(data json.RawMessage) (map[int]int, error) {
	if len(data) == 0 {
		return map[int]int{}, nil
	}
	var raw map[string]int
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	out := make(map[int]int, len(raw))
	for k, v := range raw {
		lvl, convErr := strconv.Atoi(k)
		if convErr != nil {
			continue
		}
		out[lvl] = v
	}
	return out, nil
}
